### ISSUE TITLE
Push tag problem

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#100]
To push a tag for deployment to "prod" or "stable" it had been suggested to
Make a 'Tag' locally and push it to your remote.  For Github [see](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:ci-push-build-to-git#g_deploy_build_to_github)
```
git tag v1.13.1    <--Create the tag on your local repository
git push origin v1.13.1  <--Push the tag to your remote repository, travis creates build and pushes.

```  
For Plugin Manager it has been suggested that we should use the following commands
See [Deploy to "Prod" repository](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:pi_installer_procedure#deploy_to_prod_repository)
Where the workflow suggested is

```
$ git commit -am "my last changes")
$ git tag v[new version number]
$ git push --tags origin master:master
```

I just did equivalent set of commands for weatherfax and git took ten minutes, downloaded and uploaded 44mb and added a huge number of tags that don't make much sense and look like Opencpn program tags. In short, I don't think this set of commands is very good and I believe it has messed up the tags in weatherfax. I do not understand why this happened.  

We need more reliable and better set of commands for "pushing a tag" that can also be put in the Dev Manual that does not result in the addition of OpenCPN tags.

https://github.com/rgleason/weatherfax_pi/tree/frontend2-new
See attached please.

Where did all the Opencpn version  Tags come from?  How did this happen?
Are there additional files that got added as a consequence of the tags?
Did these tags come from the ocpn_plugins.h file?

 
[wxfax-tags.txt](https://github.com/OpenCPN/plugins/files/4627797/wxfax-tags.txt)

**Comment by bdbcat** [comment]
Rick...
I think you must have accidentally been in the opencpn master branch, somehow.
You will need to delete the unwanted tags, and clean out any unwanted files.

**Comment by rgleason** [comment]
Dave,
I do know I was not in the opencpn master branch.
I was in my weatherfax_pi branch frontend2-new and used the recommended git commands which pushed all tags as suggested. 
I have reviewed the files and they appear to be correct with no extra files.

The only thing I can think of is these tags came from an earlier in-line OpenCPN setup for building, so the tags were added then?   The plugin has been around a long time.

I think the problem is that, I would prefer not to push ALL tags, I just want to push the one new tag, but I want the pushed tag to result in proper deployment.  That would be a much better solution.

**Comment by rgleason** [comment]
$ git push <repo-name> <tag-name>
This command will push a single tag to the remote repo, and it is commonly used.

Alternatively (mainly to solve tag/branch name clashes), you could use:
git push origin refs/tags/tag_a

The other way would be to push all of the tags to the remote repo:
$ git push --tags <repo-name>

"This way is not recommended because it's common for developers to have old or "bad" tags in their local repositories that have no need to be in the remote one, so it's advised to only ever explicitly push a tag using the first method, and not all of your tags at once."

I am going to change the documentation accordingly.
