### ISSUE TITLE
Circleci (TP) Bug: Macos and Macos-wx32 Failures (many)

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#1009]
For example see  https://app.circleci.com/pipelines/github/rgleason/climatology_pi/238/workflows/f755690c-0c7b-441f-a133-e9161f89e7e7/jobs/3318

Also in October, circleci is changing their macos engines.

AI generated 
> Recommended Fixes for
> bash ci/circleci-build-macos.sh
> 
> The error message indicates that the installation process is unable to find the source file named 'packages/Packages.pkg' for the Cask 'packages'. Instead, it found a file named 'Install Packages.pkg'.
> 
> To fix this issue, the user should ensure that the correct PKG source file is provided and located in the expected directory. They should verify the name and location of the source file, as well as check for any typos or incorrect file extensions.
> 
> Example of correct code:
> 
> brew cask install packages --pkgfile=/path/to/packages/Packages.pkg
>

**Comment by rgleason** [comment]
TP ci/circleci-build-macos.sh   has the following

```
set -xe

set -o pipefail
# Check if the cache is with us. If not, re-install brew.
brew list --versions libexif || brew update-reset

for pkg in cairo cmake gettext libarchive libexif python wget; do
    brew list --versions $pkg || brew install $pkg || brew install $pkg || :
    brew link --overwrite $pkg || brew install $pkg
done
```

**Comment by rgleason** [comment]
I believe there are some changes needed. 
What are they?

**Comment by bdbcat** [comment]
Looking now.
PSB.

**Comment by rgleason** [comment]
Some links
https://circleci.com/docs/using-macos/

```
We are deprecating support for all Intel-based macOS resources.

The medium and large resource classes are being deprecated on October 2, 2023. Xcode v14.2 is the latest version that will be supported by these macOS resources.

The macos.x86.medium.gen2 resource class is being deprecated on January 31, 2024. Xcode v15.1 is the latest version that will be supported by this macOS resource.

```
https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718
--
https://discuss.circleci.com/t/how-can-i-use-a-homebrew-package-inside-workflows-the-most-efficient-way/45380/2
https://formulae.brew.sh/formula/circleci

**Comment by bdbcat** [comment]
Waiting on a build.
I note that the "packages" build of MacOS plugins is deprecated, by us.  The only supported method of plugin installation on O562 and O58+ is via PIM.
Why do we not take this opportunity to drop these deprecated builds?
btw, we have the same situation on other platforms.

**Comment by bdbcat** [comment]
My question first, please.
I think only Jon is concerned with .pkg installation.  If we drop the .pkg method, then this problem goes away forever.
I am proposing that now.  
Comments?

**Comment by rgleason** [comment]
Lets drop the pkg installation please.

**Comment by bdbcat** [comment]
Done.
PR posted to testplugin_pi/sublibs

**Comment by rgleason** [comment]
Thanks, will propagate over time.

**Comment by rgleason** [comment]
Linked Title in Circleci

macOS Gen1 being sunsetted on **October 2.** Our “medium”, “large” and **Dedicated Host macOS resource classes will no longer be available after October 2.** Please update your config to avoid build errors. [Learn more](https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718)

**Comment by rgleason** [comment]
I think the questions I have about using M1 are:
1. Is it available for Open Source?
2. Does it support operation on Intel? x86_64?

**Comment by bdbcat** [comment]
Shifting to M! build core is a separate project from current sublibs project.
Of course we will do it, we have no choice if we want to use CCI for MacOS builds
But please, lets disconnect it, and **focus** on sublibs project for all TP plugins.
My experience in coding suggest that too many moving parts inevitable produces red herrings, and lots of wasted effort.

Please close this Issue as complete.

**Comment by rgleason** [comment]
OK, just trying to avoid shifting sands....
