### ISSUE TITLE
 macOS universal build  for plugins

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#1020]
See Pavel's ci-build solution for OpenCPN here
 CI for macOS universal build #3446 
https://github.com/OpenCPN/OpenCPN/pull/3446/commits/3574bb601909c9136d9f23cbb879f77b727edf0d

**Comment by rgleason** [comment]
I don't believe TP template has made these changes, but should this be closed for now? I have left an issue in TP plugins.  Shipdriver Template?  @bdbcat  @leamas @Rasbats

**Comment by leamas** [comment]
For shipdriver, this is fixed in https://github.com/Rasbats/shipdriver_pi/pull/562.
If you have left an issue in TP I suggest that you mention  that issue  here and then closes this issue.

**Comment by rgleason** [comment]
https://github.com/jongough/testplugin_pi/issues/333
