### ISSUE TITLE
Extra spaces found in the xml file

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#12]
After generating a new ocpn_plugins.xml which included weather_routing,xml files
I found extra spaces in the front part of the URL for the weather_routing lines.

I find the spaces in the weather_routing ....xml files.  Is there a way to generate these without the spaces?  Or some way to automatically remove the spaces?
Example
[weather_routing-plugin-darwin-10.13.6 - Copy.xml.txt](https://github.com/OpenCPN/plugins/files/4008913/weather_routing-plugin-darwin-10.13.6.-.Copy.xml.txt)

**Comment by leamas** [comment]
well, anything is possible. But that space is a minimum of formatting which makes the file somewhat more readable.

Why are the spaces a problem? A parser  (or  really, a scanner) shouldn't have any problems removing them ?!

**Comment by rgleason** [comment]
Ok, so I am not to be concerned about it. So, its ok, and this is not a problem. Will close.
