### ISSUE TITLE
Vdr_pi  How do we know the correct version is installed without the full version number?

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#124]
I am not at all sure that I am upgrading to the new version of VDR_pi  the version shows 1.2.2

1. Update the master catalog and there is no change.
2. Pick reinstall. ...reinstall from cache.
3. Pick uninstall.  Then pick install and a second install screen pops up and select install ..reinstall from cache again.
4. What did it install?  I cannot see the full version number (4 digits)

Is the only way to be sure that I have the correct plugin to remove the vdr cache from
C:\ProgramData\opencpn\plugins\cache\tarballs?
There are 5 different files in the cache for vdr.  Which one did it install?
Shouldn't the file name being installed be in the message so we can be sure what is happening?
Which one is picked?
I can't see the full version number either.

![ProgramData-Opencpn-Plugins-Cache](https://user-images.githubusercontent.com/2363959/84513823-078e6380-ac98-11ea-9d2f-ca2968f393a9.png)

**Comment by bdbcat** [comment]
Rick....
"Is the only way to be sure that I have the correct plugin to remove the vdr cache from
C:\ProgramData\opencpn\plugins\cache\tarballs?'
As a developer/packager/tester, the answer is YES.

Now that all is fixed, looks like time to bump the version number to 1.2.3.  That will clarify things.  In real life, we will not publish multiple tarbals with different tweak numbers. (4th digit).

So, just edit the github, update to 1.2.3, and publish.

**Comment by bdbcat** [comment]
btw, I think your cache directory is a mess.  I would delete it entirely, and start over.

**Comment by rgleason** [comment]
Yes it is a mess, that's what happens when testing stuff. I cleaned it out not so long ago. Will do so again.

**Comment by rgleason** [comment]
I still would like to know what version of the file is normally loaded from the cache.
- Is by date or by version number? It might help to know.
- It might be useful to have the file name used show as it is being loaded, if that can be done.

**Comment by rgleason** [comment]
Have incremented the 3 postion of VDR_pi and pushed to plugins.
