### ISSUE TITLE
Plugin Manager - Display shows incorrect installation status when using Experimental

### ISSUE THREAD

**Issue by jongough** [OpenCPN/plugins#17]
On linux mint development (Ubuntu 18.04 base) running a test of the new meta tag for oesen_pi. 
Master:
![image](https://user-images.githubusercontent.com/2803240/71762427-20ddf780-2f23-11ea-82e0-2f6561f5c908.png)
oesenc 3.3.0 is available for install. Change to use the 'Experimental' branch and update the catalog.
Experimental:
![image](https://user-images.githubusercontent.com/2803240/71762443-613d7580-2f23-11ea-8465-222ae3e46491.png)
Install oesenc 3.3.1 successfully, click 'Done' and then redisplay Plugin Manger:
![image](https://user-images.githubusercontent.com/2803240/71762458-95b13180-2f23-11ea-8005-fcc1f759f4a7.png)
Notice the 'Master' version of the plugin (3.3.0) shows as downgrade, is this really the correct indication as the plugin is not installed. Click 'Downgrade' and version 3.3.0 is successfully installed.
Window now shows 'Reinstall' for both versions of oesenc_pi:
![image](https://user-images.githubusercontent.com/2803240/71762471-e6c12580-2f23-11ea-886a-7b93f5fd509f.png)
That seems strange.

**Comment by leamas** [comment]
16 months later: is this still an issue?

**Comment by rgleason** [comment]
Can this be closed now?

**Comment by rgleason** [comment]
@jongough    I am not aware of an experimental branch being used anymore.  Can this be closed now?
