### ISSUE TITLE
Plugin Manager - Meta-url tag causes blank plugin when using Master

### ISSUE THREAD

**Issue by jongough** [OpenCPN/plugins#18]
On Linux Mint (Ubuntu 18.04) with the meta-url tag capable displays a blank plugin. This seems to be caused by a meta-url tag with just a URL that does not point to an XML file. Here is the xml file:
[ocpn-plugins.xml.txt](https://github.com/OpenCPN/plugins/files/4021654/ocpn-plugins.xml.txt)

The offending lines seem to be:
```
  <plugin version="1">
    <meta-url>http://kalle.org</meta-url>
  </plugin>
```
![image](https://user-images.githubusercontent.com/2803240/71762589-26d4d800-2f25-11ea-8cea-a71931cc0a54.png)
If 'Install' is clicked on OCPN hangs due to the invalid xml.

**Comment by rgleason** [comment]
I think invalid xml are a thing of the past now, with all the checking done before a PR is accepted.  Can this be closed now?

**Comment by rgleason** [comment]
@jongough   I think this can be closed now.
