### ISSUE TITLE
Unable to create request to remove plugin with the same name but different case 

### ISSUE THREAD

**Issue by Rasbats** [OpenCPN/plugins#188]
Old metadata items are being left in 'ocpn-plugins.xml'. Found 'OTCurrent' as well as 'otcurrent'. This has resulted in an entry appearing in the managed plugins list 'OTCurrent', that is impossible to remove.  

Have done a resync for my fork but is there a way to commit this?

Is there any way to remove plugins with version 0.0.0 which is how 'OTCurrent' appears after the false plugin is installed?

**Comment by bdbcat** [comment]
Dunno how that happened.
So I just removed all metadata showing "OTCurrent", and pushed.  All well now.
You could have done that, too, I think.

**Comment by Rasbats** [comment]
Cleaned the data but the next stage?

**Comment by rgleason** [comment]
Mike, you can carefully check your metadata entries, you may need to check the content of each xml file until you know what caused it.

**Comment by jongough** [comment]
The main thing here is to make sure you delete the old files in your branch as well as adding the newly downloaded files. If you are doing this on Linux it treats case as important so it happily uses OTCurrent and otcurrent as two different files. If you are doing this on windows it will assume the files are the same. I have had this problem in the past with samba shares when testing with windows but have now forced case consistency i.e. windows sees the difference between the two files and shows them as two files.

The ocpn-plugins.xml build process is running on linux and builds this file based on ALL the files in the metadata directory. It does not care who put the files in there, it just uses them. This then allows developers to delete, modify or add new files and the ocpn-plugins.xml file will always be consistent with what is in the github repository.

I hope this makes sense.

**Comment by Rasbats** [comment]
I think the expression is bang-head. I see a lot of previous version files for 'otcurrent' in 'metadata' as well. Intend taking them out before I make a pull request for the next plugin.

**Comment by jongough** [comment]
Having multiple versions shouldn't harm as you can only have one installed at anyone time. However the dialog box that lets you pick which version needs a little bit of work on some platforms as it is not friendly.
