### ISSUE TITLE
Panel icons not found

### ISSUE THREAD

**Issue by Rasbats** [OpenCPN/plugins#194]
Working with a mix of managed and legacy plugins. Windows OS and OpenCPN 5.1.621.

Activate a legacy plugin. Then 'cross it out' to close it. The display refreshes and a 'jigsaw' appears for a managed plugin. This can also happen for changing from managed to legacy plugin. 

Does not happen consistently but it seems that OpenCPN cannot always find the panel icon in the 'data' folder for the plugin, i.e. distinguish between "C:\Program Files (x86)\OpenCPN 5.1.621+9fbbcfd\plugins\xxxx\data" and "C:\Users\Mike\AppData\Local\opencpn\plugins\xxxx\data". 

![plugin_icons 2](https://user-images.githubusercontent.com/2537240/86565909-a25d2380-bf60-11ea-991a-43faa022745e.jpg)
![plugin_icons](https://user-images.githubusercontent.com/2537240/86565911-a2f5ba00-bf60-11ea-96f5-91b98aa94c68.jpg)
![plugin_icons 1](https://user-images.githubusercontent.com/2537240/86565912-a38e5080-bf60-11ea-9193-9dd2fd85006e.jpg)

Closing and re-opening the plugin clears the 'jigsaw'. Cannot make this happen with other, non-owned, legacy plugins so it may be my code that is causing the issue.

**Comment by rgleason** [comment]
I believe this might be a "commonname" problem.   Are you sure you are using the right commonname?

in dr_pi.cpp  search for "getcommonname"  what is being used?

For example, right now in climatology we have

wxString climatology_pi::GetCommonName()
{
    //  return _("Climatology");
	  return _T(PLUGIN_COMMON_NAME);
}

**Comment by Rasbats** [comment]
#define PLUGIN_COMMON_NAME "DR" in 'version.h'

wxString DR_pi::GetCommonName() in 'DR_pi.cpp'
{
      return _("DR");
}

Does the difference affect the location of the icons?

**Comment by rgleason** [comment]
You could try it. When there are multiple puzzle icons for the plugin, this is usually the problem., but it might be something else too.

**Comment by bdbcat** [comment]
@Rasbats 
Most likely related to the toolbar update logic, especially if it works correctly on initial startup with either legacy or managed plugin active.
I would not worry about it too much, since switching legacy->managed and vice-versa is a pretty rare thing for real users.
Anyway, lets leave this open for O5.2++

**Comment by rgleason** [comment]
Try cleaning out your plugins/cache?

**Comment by Rasbats** [comment]
Nope... Leaving this one open for now.

**Comment by leamas** [comment]
> return _("DR");

In any case, this is really wrong. The CommonName should always be the same and not translated. If there form some reason is a translation for "DR" this will fail.

>return _T(PLUGIN_COMMON_NAME);

A bit suspicious also about this, is the _T() macro really needed? There should be a wxString(const char*) constructor...

**Comment by rgleason** [comment]
A number of Sean's plugins use this:

`return _T(PLUGIN_COMMON_NAME);`

I have not had any problem related to this.  Can you suggest a better line?

**Comment by leamas** [comment]
just use `return PLUGIN_COMMON_NAME`. The _T() macro is deprecated stuff since before wxWidgets 3.0.

See https://docs.wxwidgets.org/3.0.5/group__group__funcmacro__string.html#ga7dfc2888539861afe6c4337ef315472b

**Comment by rgleason** [comment]
Thanks

**Comment by Rasbats** [comment]
This plugin is pretty old and does need attention. However I think there is a problem with toolbar icons appearing as jigsaw pieces, apart from DR_pi.

**Comment by leamas** [comment]
@rasbats: still an issue?

**Comment by Rasbats** [comment]
Not seen recently. I will close this one.
