### ISSUE TITLE
Climatology   Legacy & Plugin Manager version have different unreadable "data"  WHY?

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#208]
Why would the Plugin Manager version download a divergent version of data, and why does the new version of plugin fail to read the original data?

This is a PITA for users.  Makes them have to uninstall all traces (data) of climatology before installation of the new Plugin Manager version.

Is a different compression/decompression being used now, creating this problem?

**Comment by bdbcat** [comment]
Rick...
First things first.
The managed plugin has a different common name than the legacy plugin.
"Climatology" is not the same as "climatology".

So, fix this first....

**Comment by rgleason** [comment]
That's is surprising, that was the intent... to be compatible.
That is fixed now.  Flatpak failed do download essential files.
Cloudsmith has them here https://cloudsmith.io/~opencpn/repos/climatology-alpha/packages/?q=1.4.6.0*tarball

**Comment by rgleason** [comment]
Hold on there is a problem with zufile I am fixing.

**Comment by bdbcat** [comment]
Rick...
With the correct commonName, I am not finding any problem on Win10 or linux.  The managed version uses the existing data, as expected.  No new download needed.

If you are still failing on Windows, please try again on Windows, and report results.
Flatpak is another problem....
Thanks
Dave

**Comment by rgleason** [comment]
Jeez I was on a different local repository than I should have been.... I have to clean this up. Its not building locally now. What a mess. 1.4.7.0 is from the right local repository, but that is not building locally right now... I am going to label the others better, then delete them when I get it straightened out! Sorry.

**Comment by rgleason** [comment]
I tested 1.4.7.0 msvc and it works now when installing over the older version.
So I am still in wonderment, why would changing one little "c" to a big "C" fix this problem??  Does not make sense to me.

Now I have to go back and fix the local build problem somehow, and the manual plugin has a better icon....

Thanks very much.

**Comment by rgleason** [comment]
Is finding the path case sensitive, and is the routing using "commonname" for that purpose?

**Comment by bdbcat** [comment]
Probably.  I did not read the code.
Anyway, the common name is THE handle to a plugin.  If you mean to replace a legacy plugin with a managed plugin, using the same data, then you MUST use **exactly the same** common name.

**Comment by rgleason** [comment]
Ok, I think that is a RULE, I should put in my list.

**Comment by rgleason** [comment]
Closing
