### ISSUE TITLE
Climatology not showing the correct icons

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#209]
I see in icons.cpp that the switch to use svg icons is OCPN_USE_SVG
https://github.com/rgleason/climatology_pi/blob/a83761373107f39d9363c5b8f9e32fbc419ec4c2/src/icons.cpp

However the CMakeLists.txt file does not use that switch, it seems to use at Line 97

option(PLUGIN_USE_SVG "Use SVG graphics" ON)
  
https://github.com/rgleason/climatology_pi/blob/a83761373107f39d9363c5b8f9e32fbc419ec4c2/CMakeLists.txt

How can I get climatology using the correct icons like the 1.4.2.-ov50 version? Should the line be

option(OCPN_USE_SVG "Use SVG graphics" ON)

climatology_pi.svg
climatology_pi-rollover.svg
cliimatology_pi-toggled.svg
all located in the "data" directory (both legacy and managed"

![Climatology_pi-rollover-svg](https://user-images.githubusercontent.com/2363959/88115497-43182980-cb84-11ea-9090-11b4f26eff79.png)
![Climatology_pi-toggled-svg](https://user-images.githubusercontent.com/2363959/88115499-43b0c000-cb84-11ea-9f1d-8d3f69dbac51.png)
![Climatology_pi-svg](https://user-images.githubusercontent.com/2363959/88115501-44495680-cb84-11ea-9c68-c48d1bdbcfbe.png)

**Comment by rgleason** [comment]
PS or should the #ifdef  OCPN_USE_SVG's be changed to be PLUGIN_USE_SVG?

**Comment by rgleason** [comment]
I tried changing cmakelists.txt  LIne 97 to
option(PLUGIN_USE_SVG "Use SVG graphics" ON)

I did not seem to make a difference even when restart.

**Comment by jongough** [comment]
If you have run cmake with the option off, you will either need to delete CMakeCache.txt or set the option on in a cmake editor. 

Your code in CMakeLists.txt line 146 is fine, if you want to use OCPN_USE_SVG change line 149 to reflect that, if you want to use PLUGIN_USE_SVG change the source code to reflect that.

**Comment by rgleason** [comment]
Ok, so PLUGIN_USE_SVG is 

on line 97 CMakeLists.txt
option(PLUGIN_USE_SVG "Use SVG graphics" ON)

and on line 146  CMakeLists.txt
IF(PLUGIN_USE_SVG)
    MESSAGE(STATUS "${CMLOC}SVG support enabled...")

If I am using that as the trigger, I need to change icons.cpp
https://github.com/rgleason/climatology_pi/blob/fe2-newest/src/icons.cpp
Icons.cpp  Line 11
#ifdef OCPN_USE_SVG   to  PLUGIN_USE_SVG
#include "ocpn_plugin.h"
wxString _svg_climatology;
wxString _svg_climatology_rollover;
wxString _svg_climatology_toggled;
#endif

and Line 25
#ifdef OCPN_USE_SVG   to PLUGIN _USE_SVG

and src/icons.h  Line 17
#ifdef OCPN_USE_SVG  to PLUGIN_USE_SVG

climatology_pi.cpp   Line 107
#ifdef OCPN_USE_SVG  to PLUGIN_USE_SVG

Ok I've made those changes.  Thanks.
Should go in notes.

**Comment by rgleason** [comment]
ok  That worked, We are now ready to add this to plugins master!
Thank you Dave and Jon.
