### ISSUE TITLE
Flatpak script for Plugins not building

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#211]
Did someone turn something off? How do we fix this?
What is the deal here?
ocpn_draw and testplugin build flatpak
Sean's plugiins have the same frontend2

**Comment by bdbcat** [comment]
Rick...
Specific problem observation, please.
What plugin:?
Link to build script?

etc.
Thanks
Dave

**Comment by jongough** [comment]
Fixed with jg_fe2-newest. CMakeLists.txt was missing GIT_REPOSITORY_SERVER so when the flatpak yaml file was created it did not point to a git repository.

**Comment by rgleason** [comment]
Yes, I turned it off (commented it out) trying to get climatology to deploy. Turned out that was a different problem. Then did not reset this. Very sorry. Thanks Jon.

**Comment by jongough** [comment]
Next version of frontend2 will handle this condition by setting the default to github.com
