### ISSUE TITLE
Where is the ocpn_plugin.xml that Opencpn uses?  It is not the cache metadata file

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#220]
I've replaced the  cache metadata 

C:\ProgramData\opencpn\plugins\cache\metadata

with this file and started opencpn. The versions are not right in plugin manager.

[ocpn-plugins.zip](https://github.com/OpenCPN/plugins/files/5038631/ocpn-plugins.zip)

Where is the ocpn-plugins.xml that is actually used by Plugin Manager. 

I am getting tired of screwing around all day trying to get this to work properly.

Everything is so bizantine.

**Comment by bdbcat** [comment]
The ocpn_plugins.xml that is live, and actually used, is in the same directory that contains the config file, and the logfile.
Will you describe the problems you are seeing again?

**Comment by rgleason** [comment]
I was unable to find that file to overwrite with the locally built ocpn-plugins.xml that I wanted to test.
So I will need to remember this. the ocpn-plugins.xml file that is active is in
C:\ProgramData\opencpn

found it.

Now I notice that this version of Climatology has no toolbar icon, probably because I moved it to the data directory. Is that a problem?

**Comment by rgleason** [comment]
Thank you.
