### ISSUE TITLE
Watchdog 2.4.20   Alarms not working properly 

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#235]
Inclusion alarm does not work.
https://www.cruisersforum.com/forums/f134/watchdog-plugin-150313.html#post3218000

**Comment by rgleason** [comment]
I believe the inclusion alarm has not worked since before the ov50 version.
https://github.com/rgleason/watchdog_pi/releases/tag/v2.4.0-ov50

However since we have turned on JSON Validation, there is a notice in the log file about this problem, which is quite repetitive.

```
19:39:13.211 MESSAGE ODJSON.cpp:150 Validation of message against schema failed, here is why: At  of {"BoundaryState":"Any","BoundaryType":"Any","Msg":"FindPointInAnyBoundary","MsgId":"distance","Source":"WATCHDOG_PI","Type":"Request","lat":45.038878366382896,"lon":13.640262017615518} - at least one schema has failed, but ALLOF them are required to validate.

19:39:13.211 MESSAGE ODJSON.cpp:150 Validation of message against schema failed, here is why: At  of {"BoundaryState":"Any","BoundaryType":"Any","Msg":"FindPointInAnyBoundary","MsgId":"distance","Source":"WATCHDOG_PI","Type":"Request","lat":45.03769997581425,"lon":13.64095039961007} - at least one schema has failed, but ALLOF them are required to validate. 
```

Perhaps this will provide a clue where to fix it.  The  message is malformed, from somewhere.
I wonder if I turn off JSON validation if the message will work.

**Comment by rgleason** [comment]
From the message, I don't understand which schema failed.  For a moment I thought the failure was a message coming from Ocpn_draw, but this appears to be coming from WatchDog, sending position information, probably to determine if the boat is inside the inclusive boundary still.  However the message appears to be missing some necessary information.

**Comment by rgleason** [comment]
```
odjson.cpp is in ocpn_draw_pi/src 

       if(!bFail) {
            try {
                json message = json::parse(static_cast<const char*>(message_body));
                gODJSONMsgValidator->validate(message);
            } catch (const std::exception &e) {
                DEBUGST("Validation of message against schema failed, here is why: ");
                DEBUGEND(e.what());
                wxString l_errorMsg;
                l_errorMsg.Append("Validation of message against schema failed, here is why: ");
                l_errorMsg.Append(e.what());
                wxLogMessage( l_errorMsg );    <------LINE 150
                bFail = true;
            }
        }
#endif
```

**Comment by rgleason** [comment]
The error is stated to be at  " of {"BoundaryState":"Any","BoundaryType":"Any","Msg":"FindPointIn...

**Comment by jongough** [comment]
I thought watchdog used ODAPI rather than ODjson. The Json message should be used to find the API addresses, so I am not sure what is happening here.
Try rebuilding ODraw without the Json schema validation and see if it works. Also you could try a debug build and see why Json rather than the API is being used.

**Comment by rgleason** [comment]
In watchdog_pi  I found these two references to "findpointinboundary"

```
watchdog_pi\src\Alarm.cpp  (1 hit)
	Line 1713:                 jMsg["Msg"] = "FindPointInBoundary";
watchdog_pi\src\watchdog_pi.cpp  (1 hit)
	Line 468:                 } else if(root["Msg"].asString() == "FindPointInBoundary" ) {
```

**Comment by rgleason** [comment]
The line 1713 is part of a "case" Anchor which sends a msgid "anchor" so I don't thinkk the error is coming from that.

The line 468 in watchdog_pi.cpp which has findpointinboundary 

```
                } else if(root["Msg"].asString() == "FindPointInBoundary" ) {
                    if(root["MsgId"].asString() == "anchor") {
                        g_ReceivedBoundaryAnchorJSONMsg = root;
                        g_ReceivedBoundaryAnchorMessage = message_body;
                    }

```

**Comment by rgleason** [comment]
"I thought watchdog used ODAPI rather than ODjson. The Json message should be used to find the API addresses, so I am not sure what is happening here."
Jon, I don't know, I was just following the path.  

"Try rebuilding ODraw without the Json schema validation and see if it works. Also you could try a debug build and see why Json rather than the API is being used."

I'll try to do this, not quite sure how.

**Comment by rgleason** [comment]
Maybe I should try disabling the JSON validation for WatchDog first?

**Comment by rgleason** [comment]
Rebuilt ocpn_draw as version 1.8.0.19  with all the JSON validation commented out and now the inclusion alarm seems to be working acceptably.

**Comment by rgleason** [comment]
So how do I fix the message so it is accepted by JSON validation? 

PS I haven't checked the other alarms yet, but the Anchor alarm seems to be quite persistant with no reason to be.

**Comment by rgleason** [comment]
Should I give a tester this version of ocpn_draw 1.8.0.19 to test and advise which ones are not working?

**Comment by rgleason** [comment]
I've checked  inclusion boundary, exclusion boundary, anchor, wind, course, landfall and they seem to be working now.  This is with ocpn_draw  version v1.8.019  and watchdog v2.4.20.13.

Do you want me to push ocpn_draw to cloudsmith and add both to the master catalog as a temporary fix?

**Comment by rgleason** [comment]
Also, since Alec eliminated the use of  -fPIC I have not been able to get the linux builds to work.

**Comment by rgleason** [comment]
Using the older  technique  "pluginJSON" instead, now the "fastwriter" warnings are gone, however all the Ubuntu builds are still failing due to some nmea issue.  I may go back to the OpenCPN nmea lib to see if that helps, but it has much fewer files and was not what watchdog was build with.

**Comment by rgleason** [comment]
After checking nmeao183 The ubuntu errors are still showing up requesting the use of -fPIC

```
[100%] Linking CXX shared library libwatchdog_pi.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/watchdog_pi.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC  -pthread -g -Wl,-Bsymbolic -shared -Wl,-soname,libwatchdog_pi.so -o libwatchdog_pi.so CMakeFiles/watchdog_pi.dir/src/watchdog_pi.cpp.o CMakeFiles/watchdog_pi.dir/src/WatchdogDialog.cpp.o CMakeFiles/watchdog_pi.dir/src/WatchdogPropertiesDialog.cpp.o CMakeFiles/watchdog_pi.dir/src/ConfigurationDialog.cpp.o CMakeFiles/watchdog_pi.dir/src/NewAlarmDialog.cpp.o CMakeFiles/watchdog_pi.dir/src/EditAlarmDialog.cpp.o CMakeFiles/watchdog_pi.dir/src/Alarm.cpp.o CMakeFiles/watchdog_pi.dir/src/signalk_client.cpp.o CMakeFiles/watchdog_pi.dir/src/WatchdogUI.cpp.o CMakeFiles/watchdog_pi.dir/src/icons.cpp.o CMakeFiles/watchdog_pi.dir/src/wddc.cpp.o CMakeFiles/watchdog_pi.dir/src/TexFont.cpp.o libs/wxJSON/libWXJSON.a libs/nmea0183/libNMEA0183.a libwatchdog_pi_LIB_PLUGINJSON.a -L/usr/lib/x86_64-linux-gnu -pthread -lwx_baseu-3.0 -lwx_gtk2u_core-3.0 -lwx_baseu_net-3.0 -lwx_baseu_xml-3.0 -lwx_gtk2u_html-3.0 -lwx_gtk2u_adv-3.0 -lwx_gtk2u_aui-3.0 -lwx_gtk2u_gl-3.0 -lglib-2.0 -lgobject-2.0 -latk-1.0 -lgio-2.0 -lgthread-2.0 -lgmodule-2.0 -lgdk_pixbuf-2.0 -lcairo -lpango-1.0 -lpangocairo-1.0 -lpangoft2-1.0 -lpangoxft-1.0 -lgdk-x11-2.0 -lgtk-x11-2.0 -lbz2 -lz -ltinyxml 
/usr/bin/ld: libs/nmea0183/libNMEA0183.a(rte.cpp.o): relocation R_X86_64_PC32 against symbol `wxTheAssertHandler@@WXU_3.0' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: libs/nmea0183/libNMEA0183.a(sentence.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN8wxString4nposE@@WXU_3.0' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: libwatchdog_pi_LIB_PLUGINJSON.a(json_reader.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTISt13runtime_error@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: libwatchdog_pi_LIB_PLUGINJSON.a(json_value.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTISt13runtime_error@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: libwatchdog_pi_LIB_PLUGINJSON.a(json_writer.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTISt13runtime_error@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
```

**Comment by jongough** [comment]
It sounds like the JSON validation error is coming from the schema. This in the include directory of ODraw. Schema validation is turned on in cmakelists.txt near the bottom. Turning this off reverts to the old behavior of individual checks. This should be OK, but test it with testplugin_pi. In fact test the current version with validation using test plugin. That will let you know if ODraw is working. If it is then you can look at test plugin to see the Json message being used and make sure watchdog is using it.

**Comment by jongough** [comment]
Looking at alarm.cpp there is a test for the version of ODraw, see line 1277, I wonder if that test (ODVersionNewerThan) is failing so it is falling back to json?

**Comment by jongough** [comment]
Just looked at testplugin_pi but it doesn't have the call being used in it. Also the Json schema doesn't have the required call defined in it. Watchdog should be using the API, so need to find out why it isn't. The API should work ok.

**Comment by jongough** [comment]
Try using the latest ODAPI.h and see it that helps.

**Comment by rgleason** [comment]
Jon,  I tried this but did not know how to make it work...
"That will let you know if ODraw is working. If it is then you can look at test plugin to see the Json message being used and make sure watchdog is using it."

"Test for the version of ODraw, see line 1277, I wonder if that test (ODVersionNewerThan) is failing so it is falling back to json?"
alarm.cpp  Line 1277
```
                if(wxIsNaN(lastfix.Lat) || wxIsNaN(lastfix.Lon) ||wxIsNaN(lastfix.Cog) || wxIsNaN(lastfix.Sog)) break;
                if(ODVersionNewerThan( 1, 1, 1)) {
                    dist = lastfix.Sog * ( m_TimeMinutes / 60 );
                    PositionBearingDistanceMercator_Plugin(lastfix.Lat, lastfix.Lon, lastfix.Cog, dist, &lat, &lon);
                    if(l_bUseODAPI_FCBLC) {
                        FindClosestBoundaryLineCrossing_t *pFCPIAB = new FindClosestBoundaryLineCrossing_t;
                        pFCPIAB->dStartLat = lastfix.Lat;
                        pFCPIAB->dStartLon = lastfix.Lon;
                        pFCPIAB->dEndLat = lat;
                        pFCPIAB->dEndLon = lon;
                        switch (m_BoundaryType) {
```

I don't know if it fails back too json.


"Just looked at testplugin_pi but it doesn't have the call being used in it.   - Confirmed.   
" Also the Json schema doesn't have the required call defined in it. Watchdog should be using the API, so need to find out why it isn't. The API should work ok."   

"Try using the latest ODAPI.h and see it that helps."
OK from ocpn_draw....

**Comment by rgleason** [comment]
Have used ODAPI.h  8kb from ocpn_draw and copied it into watchdog over the 4kb file, then rebuilt it with validation commented out and used ocpn_draw with json validation off too. 
It appears inclusion boundary is still working.
Should I now turn on json validation in both plugins?

**Comment by jongough** [comment]
Please try with Json validation, it should work if the odapi is being used, If not then it will fail as the Json schema is incomplete in ODraw.

**Comment by leamas** [comment]
Havn't read all of this, but: Why don't you just log the complete message, available in message_body?

**Comment by rgleason** [comment]
This is a reasonable suggestion, and I think Jon has some other improvements in mind too, for when he gets back from sailing.  Jon I will try with Json Validation on for both watchdog and ocpn_draw, using the newer version of ODAPI.h in watchdog..  (..Is it likely that I should update that file in weather_routing too?)

**Comment by rgleason** [comment]
@jongough  When I rebuilt  watchdog and ocpn_draw locally, I find that ocpn_draw has some validator messages that I think you should review when you get a chance. I include them below, this happens towards the end of the build.  I will now test watchdog using local files.

```
  tinyxmlerror.cpp
C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp(426): warning C4244: 'argument': conversion from 'T' to 'double', possible loss of data [C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\build\ocpn_draw_pi.vcxproj]
          with
          [
              T=__int64
          ]
  C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp(422): note: while compiling class template member function 'void `anonymous-namespace'::numeric<__int64>::validate(const nlohmann::json &,nlohmann::json_schema::basic_error_handler &) const'
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(616): note: see reference to class template instantiation '`anonymous-namespace'::numeric<__int64>' being compiled (compiling source file C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp)
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\memory(1227): note: see reference to class template instantiation 'std::is_convertible<_Yty *,_Ty *>' being compiled
          with
          [
              _Yty=`anonymous-namespace'::numeric<__int64>,
              _Ty=`anonymous-namespace'::schema
          ] (compiling source file C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp)
  C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp(825): note: see reference to class template instantiation 'std::_SP_pointer_compatible<`anonymous-namespace'::numeric<__int64>,`anonymous-namespace'::schema>' being compiled
C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp(426): warning C4244: 'argument': conversion from 'T' to 'double', possible loss of data [C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\build\ocpn_draw_pi.vcxproj]
          with
          [
              T=unsigned __int64
          ]
  C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp(422): note: while compiling class template member function 'void `anonymous-namespace'::numeric<unsigned __int64>::validate(const nlohmann::json &,nlohmann::json_schema::basic_error_handler &) const'
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(616): note: see reference to class template instantiation '`anonymous-namespace'::numeric<unsigned __int64>' being compiled (compiling source file C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp)
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\memory(1227): note: see reference to class template instantiation 'std::is_convertible<_Yty *,_Ty *>' being compiled
          with
          [
              _Yty=`anonymous-namespace'::numeric<unsigned __int64>,
              _Ty=`anonymous-namespace'::schema
          ] (compiling source file C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp)
  C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp(823): note: see reference to class template instantiation 'std::_SP_pointer_compatible<`anonymous-namespace'::numeric<unsigned __int64>,`anonymous-namespace'::schema>' being compiled
     Creating library C:/Users/Rick/Documents/GitHub/ocpn_draw_pi/build/Release/ocpn_draw_pi.lib and object C:/Users/Rick/Documents/GitHub/ocpn_draw_pi/build/Release/ocpn_draw_pi.exp
  ocpn_draw_pi.vcxproj -> C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\build\Release\ocpn_draw_pi.dll
```

**Comment by rgleason** [comment]
Tested local builds of watchdog 2.4.20.16 and ocpn_draw 1.8.0.20 which both have JSON validate turned on.
Inclusion and Boundaries seem to be working nicely in Watchdog now.
I find no JSON Validation errors for this session in opencpn.log.   Now that watchdog seems to  be working, I will increment version and push it.   The existing Ocpn_plugin on master catalog should be fine.

Should I check weather_routing odapi.h?

![Screenshot (10)](https://user-images.githubusercontent.com/2363959/92027153-2e58b500-ed30-11ea-850a-314e60d2c489.png)

**Comment by rgleason** [comment]
Closing, fixed

**Comment by jongough** [comment]
Yes, weather routing uses the same code (it was built Sean's plugins). The odapi was updated for this release to add new capabilities and I tried, unsuccessfully, to avoid impacting older plugins. I also implemented a proper Json schema, but I forgot to add a couple of messages types which is why the Json gave the failure message.

**Comment by rgleason** [comment]
Thanks, weather_routing is next.
