### ISSUE TITLE
Watchdog 2.4.21.0  fails to build Flatpak

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#239]
Last call, will make new PR to opencpn/plugins in an hour.

Flatpak fails https://app.circleci.com/pipelines/github/rgleason/watchdog_pi/92/workflows/35e6efa2-ff04-4ba8-b70d-258767beec1d/jobs/1053
Flatpak installs are 10mb when all the others are considerably less than 1mb

```
+ flatpak install --user -y http://opencpn.duckdns.org/opencpn/opencpn.flatpakref
GLib-GIO-Message: 19:42:50.818: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
error: Unable to load summary from remote org.opencpn.OpenCPN-origin: GPG signatures found, but none are in trusted keyring

```

**Comment by jongough** [comment]
I get this message at times and just rerun the job. It appears that the DNS being used fails to find the site needed. It is normally fixed after an hour, but sometimes takes longer.

**Comment by rgleason** [comment]
Well, I've tried 3x's  again, with the same result:
"error: Unable to load summary from remote org.opencpn.OpenCPN-origin: GPG signatures found, but none are in trusted keyring"  

Maybe AL changed something or circleci changed.

**Comment by rgleason** [comment]
When I added the metadata files to plugins, oddly I found a flatpak metadata file.
