### ISSUE TITLE
testplugin metadata: <name> does not match GetCommonName()

### ISSUE THREAD

**Issue by leamas** [OpenCPN/plugins#24]
As heading says. The name reported by testplugin is _Testplugin_ whereas the name in the xml metadata is _testplugin_. 

I suspect that the culprit is the following:

```
wxString testplugin_pi::GetCommonName()
{
      return _("testplugin");
}
```

I suspect that the intent is to return _testplugin_, but that this is translated to _Testplugin_. Removing the _() macro should fix this. Translating the plugin name is a bad idea anyway, since the metadata must match and isn't translated

I had to add additional logging to reveal the returned name.

**Comment by rgleason** [comment]
Opencpn compile today. Then trying in alpha, beta, master catalogs.

Master catalog List shows two instances of testplugin:  
- "testplugin 1.0.45" managed with no enable/disable  [green puzzle icon] (reinstall 1.0.45)
- "Testplugin 1.0" unmanaged with enable/disable  [TP Icon]

Beta catalog List shows two instances of testplugin:
- "testplugin 1.0.43" managed with no enable/disable  [puzzle icon]  (Downgrade to 1.0..43)
- "Testplugin 1.0" unmanaged with enable/disable   [TP icon]

Alpha catalog List shows to instances of testplugin:
- "testplugin 1.0.43" managed with no enable/disable  [puzzle icon]  (Downgrade to 1.0..41)
- "Testplugin 1.0" unmanaged with enable/disable   [TP icon]

There are other plugins that do similar things now, and I believe weather_routing is doing this again. Attached are a couple screenshots.

![Screenshot (548)](https://user-images.githubusercontent.com/2363959/74884884-3fb51380-5342-11ea-8708-7c3bea8c4a9a.png)
![Screenshot (547)](https://user-images.githubusercontent.com/2363959/74884896-45125e00-5342-11ea-94d4-013d39b037ff.png)

**Comment by rgleason** [comment]
Well actually, weather_routing works properly in the Plugin Manager List now (with some toolbar icon issues).

- Alpha catalog has the xml and "WeatherRouting 1.13.1" shows as managed and can be reinstalled.
- Beta catalog it shows as "WeatherRouting 1.13" unmanaged with the correct icon in the list, but 3 green puzzle icons in the toolbar. 
- Master catalog is similar to Beta

(Also note that there are 3  Squiddio Icons in the toolbar)

![Screenshot (551)](https://user-images.githubusercontent.com/2363959/74886056-206bb580-5345-11ea-91c4-39bec04aaf05.png)

![Screenshot (549)](https://user-images.githubusercontent.com/2363959/74886064-2792c380-5345-11ea-8308-8616222bde30.png)

**Comment by rgleason** [comment]
When I Hide the toolbar and then unhide, there are black squares in place of the green puzzle icons.
When I close Opencpn and reopen it, the toolbar seems to now be normal.

**Comment by bdbcat** [comment]
Rick...

Plugin catalogs were scrambled.  My mistake.  Fixed now.
master:  Squiddio only
Beta: oeSENC, oeRNC, Radar, and test-plugin.

Please retest and report.
Thanks for your patience
Dave

**Comment by bdbcat** [comment]
Rick...

More:
WeatherRouting exists only in Alpha catalog.  I am waiting fro your PR to plugins, Beta branch, to promote it to Beta status.

**Comment by leamas** [comment]
Could we please get some order here? This bug was about testplugin vs Testplugin. Can we keep it that way? Other issues: please file separeate bugs.

**Comment by rgleason** [comment]
```
Rick...
Plugin catalogs were scrambled. My mistake. Fixed now.
```
It was also my mistake too! I had testplugin xml's in my alpha catalog  "meta-url" as a part of the original testing for the meta-url!   So since Jon has added testplugin to Beta, some of the duplication may be from the alpha versions!

Sorry, I will remove those shortly.

**Comment by rgleason** [comment]
Testplugin 1.0.45  on Windows10 and Beta catalog appears to now be working properly.
Same with Testplugin 1.0.45 on Ubuntu 18.04

-Also BTW, the Testplugin Icon seems to work normally without showing the green puzzle when the PI Manager is on a catalog that does not have a  Testplugin xml reference like Alpha right now. I may try to find out how this works.

I think this can be closed after someone else checks it.

**Comment by rgleason** [comment]
Can close.

**Comment by leamas** [comment]
The upstream bug as described in https://github.com/OpenCPN/plugins/issues/24#issue-566423316  i. e., the plugin name is marked for translation is perhaps not fixed. However, this is an upstream issue. Closing.
