### ISSUE TITLE
testplugin 1.0.133.0 add android fix flatpak #242

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#243]
https://github.com/OpenCPN/plugins/pull/242

Github actions needs to be edited for android I think.

**Comment by jongough** [comment]
The xsd needs updating to include android. The action just checks against the xsd.

**Comment by rgleason** [comment]
Thanks Jon for clarification. I think Dave can do this.

**Comment by bdbcat** [comment]
Rick...
Done.  Master catalog now contains android builds of testplugin_pi, properly verified.  
Testing now on actual Android devices, all seems well, at least for installation and activation.
Thanks for pushing this forward.
VDR is next, then some more Seans plugins based on Frontend-2...

**Comment by rgleason** [comment]
Good, ,glad testing on android devices seem to work!  
This is going to be a good improvement I hope. 
I will get to VDR tomorrow, then get Watchdog working following your lead.
Then Sean's other plugins etc. He will be very pleased.
Thank you for setting us on the right path here!
I hope my PR to Jon's testplugin will be ok....
Going to close now.
