### ISSUE TITLE
Vdr_pi  add Android builds

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#244]
Dave, I've started this  https://github.com/rgleason/vdr_pi/tree/master.
When I updated vdr_pi to the current frontend1   with multiple builds  using  Oesenc_pi as an example,, I gradually was able to remove the  oserverd stuff that was not used at all in vdr_pi.

Now I am getting confused because there are these directories in oesenc_pi

- buiildno-local *
- buildandroid *
- buildlinux *
- buildlinux64 *
- buildllinuxarm *
- buildlinuxarm64 *
- buildosx   (remove the oeserved folder and other support files)
- buildwin   (remove the oeserved folder and other support files)

all with oserved directories, which I had removed before.  So do I even need the ones above with astericks for vdr_pi?

**Comment by bdbcat** [comment]
Rick...
You may safely remove the "asterisk" directories.  They relate only to oeserverd.

**Comment by rgleason** [comment]
Thanks.   One more question further down.

vdr_pi and oesenc_pi have an "include" directory with GL and GLES folders that appear to be identical.
However vdr_pi has an addition directory  include/android  with subdir "wx" and two files datectrl.h and timectrl.h.
Is folder include/android needed in vdr_pi or is this leftover from previous?

**Comment by bdbcat** [comment]
May be leftover.  Leave it for now, does no harm.

**Comment by rgleason** [comment]
appveyor..yml  .travis.yml, mingw dir etc all pretty much the same, just different deployment.
Now comparing cmakelists.txt

**Comment by rgleason** [comment]
In  CMakeLists.txt   oesenc_pi  LINE 344 and 345

else ()
  INCLUDE_DIRECTORIES(BEFORE ${PROJECT_SOURCE_DIR}/api-13)

but the directory does not exist?

**Comment by rgleason** [comment]
I am able to create  vdr_pi-1.2.4-1_msvc-10.0.19041.tar.gz   locally in the build directory, with this batch file:
  bld.bat
   cd build
   cmake -T v141_xp ..
   cmake --build . --target package --config release 
   rem  bash ./cloudsmith-upload.sh

but the file does not seem to have the metadata included in it, so I am reluctant to test it with "Import Plugin" or to push it up to Cloudsmith.   Is there some step I am missing?

**Comment by rgleason** [comment]
Now going to just push it to my remote fork and get it building, to see what happens.

**Comment by bdbcat** [comment]
Off line for a few hours, back this evening.

**Comment by rgleason** [comment]
OK, 

 xenial, trusty and appveyor msvc  failed because they need a valid UTC timestamp:
```
File "/usr/local/lib/python3.5/dist-packages/cloudsmith_cli/cli/config.py", line 14, in <module>
    from . import utils, validators
  File "/usr/local/lib/python3.5/dist-packages/cloudsmith_cli/cli/validators.py", line 165
    f"{param.name} must be a valid utc timestamp formatted as `%Y-%m-%dT%H:%M:%SZ` e.g. `2020-12-31T00:00:00Z`",
```
https://app.circleci.com/pipelines/github/rgleason/vdr_pi/104/workflows/97b5a536-baf6-4996-b9ca-49b867eac376/jobs/783

and I have to chmod the two new ci builds for android.
Otherwise they seem to be building.

**Comment by rgleason** [comment]
While using circleci search I find that it is difficult to filter out everything except the recent tarballs.
This search kind of works   https://cloudsmith.io/~opencpn/repos/vdr-beta/packages/?q=*1.2.4.3
but metadata is included.   I have tried  this search and others  "*1.2.4.3*tarball  and *tarball*1.2.3.4 but they don't work.
I think it would be helpful if the version number was in the name directly after the vdr, then maybe we could use Jon's script for uploading to plugins too  "cloudsmith_xml_bash.sh".

**Comment by rgleason** [comment]
A number of builds fail due to invalid timestamp.  Any thoughts? 
https://github.com/rgleason/vdr_pi/commits/android-ci
```
File "c:\python27\lib\site-packages\cloudsmith_cli\cli\config.py", line 14, in <module>
    from . import utils, validators
  File "c:\python27\lib\site-packages\cloudsmith_cli\cli\validators.py", line 165
    f"{param.name} must be a valid utc timestamp formatted as `%Y-%m-%dT%H:%M:%SZ` e.g. `2020-12-31T00:00:00Z`",
                                                                                                              ^
SyntaxError: invalid syntax
Command exited with code 1

```

**Comment by rgleason** [comment]
Now it is finding wxJSON and we have another error

 No rule to make target '/build_arm64/qtbase/lib/libQt5Core.so', needed by 'libvdr_pi.so'.  Stop.

```
[ 97%] Building CXX object CMakeFiles/vdr_pi.dir/src/wxJSON/jsonwriter.cpp.o
/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++  -DANDROID -DARMHF -DBUILDING_PLUGIN -DOCPN_USE_WRAPPER -DQT_WIDGETS_LIB -DTIXML_USE_STL -DUSE_ANDROID_GLES2 -DUSE_GLSL -D__OCPN__ANDROID__ -D__WXQT__ -DocpnUSE_GL -DocpnUSE_GLES -Dvdr_pi_EXPORTS -I/home/circleci/project/api-16 -I/home/circleci/project -I/home/circleci/project/src -I/home/circleci/project/src/wxJSON -I/home/circleci/project/build/CMakeFiles/include -I/home/circleci/project/include -I/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include -I/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtCore -I/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtWidgets -I/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtGui -I/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtOpenGL -I/home/circleci/project/OCPNAndroidCommon-master/qt5/build_arm64_O3/qtbase/include/QtTest -I/home/circleci/project/OCPNAndroidCommon-master/wxWidgets/libarm64/wx/include/arm-linux-androideabi-qt-unicode-static-3.1 -I/home/circleci/project/OCPNAndroidCommon-master/wxWidgets/include -I/home/circleci/project/src/tinyxml  -pthread -fPIC -O2 -g   -Wall -Wno-unused-result -g -O2 -fexceptions -Wno-inconsistent-missing-override -Wno-potentially-evaluated-expression -Wall -g -fexceptions -O2 -Wno-unused -fno-strict-aliasing  -o CMakeFiles/vdr_pi.dir/src/wxJSON/jsonwriter.cpp.o -c /home/circleci/project/src/wxJSON/jsonwriter.cpp
make[2]: *** No rule to make target '/build_arm64/qtbase/lib/libQt5Core.so', needed by 'libvdr_pi.so'.  Stop.
make[2]: Leaving directory '/home/circleci/project/build'
make[1]: *** [CMakeFiles/Makefile2:108: CMakeFiles/vdr_pi.dir/all] Error 2
make[1]: Leaving directory '/home/circleci/project/build'
make: *** [Makefile:155: all] Error 2
```

**Comment by rgleason** [comment]
Trusty failure
```
+ sudo python3 -m pip install -q cloudsmith-cli
*** Error compiling '/tmp/pip_build_root/cloudsmith-cli/cloudsmith_cli/cli/validators.py'...
  File "/tmp/pip_build_root/cloudsmith-cli/cloudsmith_cli/cli/validators.py", line 165
    f"{param.name} must be a valid utc timestamp formatted as `%Y-%m-%dT%H:%M:%SZ` e.g. `2020-12-31T00:00:00Z`",
                                                                                                              ^
SyntaxError: invalid syntax
```

.travis  buster armhf
```
  File "/home/travis/.local/lib/python3.5/site-packages/cloudsmith_cli/cli/validators.py", line 165
    f"{param.name} must be a valid utc timestamp formatted as `%Y-%m-%dT%H:%M:%SZ` e.g. `2020-12-31T00:00:00Z`",
```                                                                                                              ^

android
```
[/OCPNAndroidCommon-master/wxWidgets/libarmhf/wx/include/arm-linux-androideabi-qt-unicode-static-3.1 -I/home/circleci/project/OCPNAndroidCommon-master/wxWidgets/include -I/home/circleci/project/src/tinyxml  -pthread -fPIC -O2 -g   -Wall -Wno-unused-result -g -O2 -fexceptions -Wno-inconsistent-missing-override -Wno-potentially-evaluated-expression -Wall -g -fexceptions -O2 -Wno-unused -fno-strict-aliasing  -o CMakeFiles/vdr_pi.dir/src/wxJSON/jsonwriter.cpp.o -c /home/circleci/project/src/wxJSON/jsonwriter.cpp
make[2]: *** No rule to make target '/build_arm32_19_O3/qtbase/lib/libQt5Core.so', needed by 'libvdr_pi.so'.  Stop.
```

**Comment by bdbcat** [comment]
Rick...
I pushed a small change to CMakeLists.txt, which totally fixes the Android builds.
I have no idea why cicleci-upload is failing for some platforms, and passing for others.  Something in the cloudsmith-cli python code.  The exact same code works in oesenc_pi.  Maybe try again later?
Meanwhile, I will test the Android builds by tarball import.

**Comment by rgleason** [comment]
Nor do I.  It seems to come from 
cloudsmith_cli/cli/validators.py", line 165    f"{param.name} must be a valid utc timestamp formatted

**Comment by rgleason** [comment]
Sent an inquiry to Cloudssmith

**Comment by bdbcat** [comment]
The Android builds seem to work fine by tarball import.  Good job!
I am tweaking for better Android UI presentation.  Done soon. I'll let you know.

**Comment by bdbcat** [comment]
Rick...
Done now.  Confirmed OK on Android actual devices.
I'll stop poking around now, pending more info on the python question.
I'm going to publish O5.2 for Android very soon now, and the managed plugins will all follow in due course, as they are completed and tested.
Thanks

**Comment by rgleason** [comment]
Lee advised:

`Hey Rick - Could you try again now with the latest Cloudsmith CLI release? We had an issue that broke Python2 compatibility, which you were probably running within; sorry about that. The 0.24.2 release should fix the issue now.
`
Now, we have testplugin and vdr_pi working.  
Merged vdr_pi android-ci into master branch, and will increment version number once it completes
https://github.com/rgleason/vdr_pi

**Comment by rgleason** [comment]
The metadata files for VDR have to be downloaded by hand and then added to plugins.
For frontend2 Jon has a very handy script that works very nicely from the  github.com/<user>/plugins  directory.
From the bash prompt:
"cloudsmith_xml_bash.sh  <pluginname (no pi)> <version no.>  opencpn <repository (alpha, beta, prod OR stable unstable)>"

For example from bash prompt:
"cloudsmith_xml_bash.sh  vdr 1.2.5.0 opencpn prod"
Then the metadata files are copied over to the metadata directory.

**Comment by rgleason** [comment]
Vdr_pi v1.2.5.0  https://github.com/rgleason/vdr_pi
has completed.  I'll make a PR now.

**Comment by rgleason** [comment]
I had the command wrong. Tried it with vdr, but because of the naming it did not work.

```
Rick@Dart MINGW64 ~/documents/github/plugins (rg-master)
$ download_xml_bash.sh vdr 1.2.5.0 opencpn prod
Issuing command: wget -q -O - https://cloudsmith.io/~opencpn/repos/vdr-prod/packages/?q=*1.2.5.0*.xml
Show current files that match criteria
ls: cannot access 'metadata/vdr*-1.2.5.0*xml': No such file or directory
Deleting current files that match criteria
rm: cannot remove 'metadata/vdr*-1.2.5.0*xml': No such file or directory
Finding files on remote cloudsmith repository
```

**Comment by rgleason** [comment]
I figured out how to search for metadata  with version  1.2.5.0
In the search bar simply put "metadata 1.2.5.0" which will bring up all version 1.2.5.0  metadata files.
Then they have to be downloaded and copied to plugins metadata directory.

**Comment by bdbcat** [comment]
Rick...
Your latest PR to master catalog DID NOT INCLUDE the VDR_pi for Android-armhf.
The Android-arm64 plugin is included, and works fine.
Dave

**Comment by rgleason** [comment]
Sorry, here it is. I guess I missed it when copying
https://github.com/OpenCPN/plugins/pull/246

**Comment by rgleason** [comment]
PR accepted.
