### ISSUE TITLE
Watchdog 2.4.21.9  add Android builds and other questions

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#247]
https://github.com/rgleason/watchdog_pi   branch: Master

Disabled Alec's submodules nmea and json due to errors and 
then used PluginNemaCmake and PluginJsonCmake instead.
All builds except android succeeded, but not all tested. 
Did test windows version, trying many of the alarms and the ones I tried all worked and sound worked.

**Problem:** 
Android builds are failing due to a missing directory "src/glshim"  called by PluginConfigureCmake
Have looked for this glshim folder and files in plugins everywhere weather_routing, weatherfax, oesenc, etc.

```
-- PluginConfigure: Optimisation: -O2
-- PluginConfigure: Using GLESv1 for Android
CMake Error at cmake/PluginConfigure.cmake:326 (add_subdirectory):
  add_subdirectory given source "src/glshim" which is not an existing
  directory.
Call Stack (most recent call first):
  CMakeLists.txt:151 (include)

-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- CMakeLists: Using JSON Schema validation - warning this changes the 'flavour' of the executable and it may not be compatible with OpenCPN
-- CMakeLists: Adding JSON Schema validation

```

**One other Problem:**
I need some direction about this.  The plugin only builds with USE_GL turned "ON"
v2.4.21.8 

When CMakeLists.txt  Line 114  "USE_GL" is OFF we get GL errors.
```
option(USE_GL "Enable OpenGL support" OFF)  
#Turn ON, only fix found for GL_texture2d, glDisable, GL_BLEND  errors

```
Typical Errors
```
C:\Users\Rick\Documents\GitHub\watchdog_pi\src\wddc.cpp(223): error C2065: 'GL_TEXTURE_2D': undeclared identifier [C:\Users\Rick\Documents\GitHub\watchdog_pi\build\watchdog_pi.vcxproj]
C:\Users\Rick\Documents\GitHub\watchdog_pi\src\wddc.cpp(223): error C3861: 'glDisable': identifier not found [C:\Users\Rick\Documents\GitHub\watchdog_pi\build\watchdog_pi.vcxproj]
C:\Users\Rick\Documents\GitHub\watchdog_pi\src\wddc.cpp(225): error C2065: 'GL_BLEND': undeclared identifier [C:\Users\Rick\Documents\GitHub\watchdog_pi\build\watchdog_pi.vcxproj]
C:\Users\Rick\Documents\GitHub\watchdog_pi\src\wddc.cpp(225): error C3861: 'glDisable': identifier not found [C:\Users\Rick\Documents\GitHub\watchdog_pi\build\watchdog_pi.vcxproj]

```
So I have turned USE_GL   ON !   Is this ok?  What are the rules about changing this?

Also I am using 

```
if(UNIX)
    add_definitions("-fPIC")
endif(UNIX)
```

**Comment by bdbcat** [comment]
Android builds OK now, with my latest patches.
Have no idea if it works, though.  Tomorrow, I will try to import the tarball, and see what happens.
Any chance of getting Sean involved in debugging/testing these plugins?

**Comment by rgleason** [comment]
I think Jon is involved now, he wanted me to build a version of Pypilot with android and all the environments and make a PR back to his repos. I built that last night. The two android built. The conversion to frontend2 went through without a hitch.   I have to fix MacOS, this morning, the only one that didn't build.  I will mention you needed some help testing android.

https://github.com/rgleason/watchdog_pi

https://cloudsmith.io/~opencpn/repos/pypilot-alpha/packages/

Should I add the android to opencpn/plugins without testing?

**Comment by rgleason** [comment]
Sorry, left wrong link. Thankyou Dave for your fix of android!

Is your fix to the cmake file specific to WD or should I use it for other PI?  Note that Pypilot android did build.

**Comment by bdbcat** [comment]
Rick...
You should integrate the changes I made for WD in all plugins that need GL, or JSON validator, or both.

**Comment by bdbcat** [comment]
Rick...
I tested Watchdog on Android. It installs and runs, at least to some degree.
But the UI is very poor on Android.  Dialogs too small, not movable, etc.
I expect that this will be the case for almost all plugins that have some UI elements.  We will need the plugin author to engage with an Android device(or several, with different screen sizes, versions, etc), and make the UI changes necessary to actually run effectively on Android.  I know this is a lot of work, across all possible plugins.  In fact, that is the main reason why Android release of OCPN always lags the desktop release .  There is lots to check and fix.  But that is the state of play today.

I cannot recommend that Watchdog for Android be released to plugin master catalog today.

**Comment by rgleason** [comment]
Dave, Thank you. I will wait and will see if Sean can fix the UI for Android and then move the android builds to the master plugin.

Thank you for gettting it runniing!

**Comment by rgleason** [comment]
Dave, can I use the Alpha or Beta Channel for the Android plugins that need work?
Sean has only an Android Cell phone and it going to try to find good wifi tomorrow to test the plugins.
I am going to try Ann's small tablet, but it would be easier if I could put these up on the beta catalog or alpha.. 
and then add the opencpn , config trigger.

**Comment by bdbcat** [comment]
Rick...
I would try using the Beta channel, for now.
To access the channel selector on Android, and also the "Import Plugin" button, you must manually edit the config file:

[Plugins]
CatalogExpert=1

Also, you will need a copy of OA 5.5.2(Beta)
https://www.dropbox.com/s/fzvbtaoqefzoydq/org.opencpn.opencpn-v56%285.2.2%29-release.apk?dl=0

**Comment by rgleason** [comment]
Thank you Dave!

**Comment by rgleason** [comment]
Dave I tried to make a PR to beta and got this error.
Does the validation for Beta need to be updated perhaps?  Sorry.

```
check xml files
0s
##[error]Process completed with exit code 3.
Run bash ./validate_xml.sh
Processing file: metadata/pypilot_pi-0.22.0.0-android-arm64-16.xml
metadata/pypilot_pi-0.22.0.0-android-arm64-16.xml:19: element target-arch: Schemas validity error : Element 'target-arch': This element is not expected. Expected is ( tarball-url ).
metadata/pypilot_pi-0.22.0.0-android-arm64-16.xml fails to validate
Processing file: metadata/pypilot_pi-0.22.0.0-android-armhf-16.xml
metadata/pypilot_pi-0.22.0.0-android-armhf-16.xml:19: element target-arch: Schemas validity error : Element 'target-arch': This element is not expected. Expected is ( tarball-url ).
metadata/pypilot_pi-0.22.0.0-android-armhf-16.xml fails to validate
Processing file: metadata/watchdog_pi-2.4.21.9-android-arm64-16.xml
metadata/watchdog_pi-2.4.21.9-android-arm64-16.xml:19: element target-arch: Schemas validity error : Element 'target-arch': This element is not expected. Expected is ( tarball-url ).
Processing file: metadata/watchdog_pi-2.4.21.9-android-armhf-16.xml
metadata/watchdog_pi-2.4.21.9-android-arm64-16.xml fails to validate
metadata/watchdog_pi-2.4.21.9-android-armhf-16.xml:19: element target-arch: Schemas validity error : Element 'target-arch': This element is not expected. Expected is ( tarball-url ).
metadata/watchdog_pi-2.4.21.9-android-armhf-16.xml fails to validate
##[error]Process completed with exit code 3.
```

**Comment by rgleason** [comment]
Oh you merged it. Thanks.

**Comment by bdbcat** [comment]
Rick...
The merge is happening OK.  But the XML validation is failing, probably due to using the Beta branch.  Something for Jon to look at, when he gets a chance.

**Comment by jongough** [comment]
Dave, just checked and the xsd needs updating in all branches to match master. The beta version is 8 months old.

So each time the xsd is updated it probably should go through alpha to beta to master as a test process to ensure master is correct. This also allows new tags/values to be tested before they potentially block pushes to master. But that process is up to you.

**Comment by rgleason** [comment]
Dave wrote
```
I would try using the Beta channel, for now.
To access the channel selector on Android, and also the "Import Plugin" button, you must manually edit the config file:

[Plugins]
CatalogExpert=1

Also, you will need a copy of OA 5.5.2(Beta)
https://www.dropbox.com/s/fzvbtaoqefzoydq/org.opencpn.opencpn-v56%285.2.2%29-release.apk?dl=0
```

Downloaded and installed OA 5.5.2 to old S4 Samsung phone  It supposedly installed alongside my current install.
Opened up ? and found  Ov5.2.2 [56]

Downloaded Old School text editor and made the  [Plugins]   CatalogExpert=1 change to opencpn.org

I can now select "Beta" catalog and have picked and updated  Beta catalog.  "Update successfull"
The 5 internal plugins + Squiddio show, but not the watchdog and pypilot that is now in the beta catalog.
I wonder why.

**Comment by bdbcat** [comment]
Rick...
Study the OCPN logfile on the device.  It will show, in detail what plugins were found, and any load problems.

**Comment by bdbcat** [comment]
Rick...
I am getting the same result.  Will debug later today.
Meanwhile, you should be able to import the tarball.  Download from cloudsmith, copy to the Android device in some common location ( e.g. /storage)  and select "Import".
Dave

**Comment by rgleason** [comment]
Dave,  
I did manage to find the android log file and cut out the part where I tried to install. I had trouble installing from both Beta catalog and using the Install Plugin.  I assumed it was the armhf files for both pllugins. Peerhaps that is not correct?
See attached..

[android-test.log](https://github.com/OpenCPN/plugins/files/5211160/android-test.log)

**Comment by rgleason** [comment]
Found this log note for pypilot

```
I/OpenCPN (28900): isFileChooserFinished:  returning file:/storage/emulated/0/Download/pypilot_pi-0.21.3.0-android-armhf-16.xml
I/OpenCPN (28900): FileChooserDialog
I/OpenCPN (28900): /storage/emulated/0/Android/data/org.opencpn.opencpn/files
E/OpenCPN (28900): Found SDK 19 or greater
E/OpenCPN (28900): eSL not null
E/OpenCPN (28900): 0/ 2
....
I/OpenCPN (28900): invokeDelegateMethod onWindowFocusChanged
I/OpenCPN (28900): isFileChooserFinished:  returning cancel:
W/libgorp.so(28900): This plugin does not support grabbing the keyboard
W/libgorp.so(28900): This plugin does not support grabbing the keyboard
```

Is is unclear what the problem is with watchdog

```
I/OpenCPN (28900): FileChooserDialog selected: watchdog_pi-2.4.21.9-android-armhf-16.xml
I/OpenCPN (28900): invokeDelegateMethod onWindowFocusChanged
I/OpenCPN (28900): isFileChooserFinished:  returning file:/storage/emulated/0/Download/watchdog_pi-2.4.21.9-android-armhf-16.xml
```

**Comment by rgleason** [comment]
More logs:

```
E/OpenCPN (27766): SD Card's directory: /storage/extSdCard/Android/data/org.opencpn.opencpn/files
E/OpenCPN (27766): FileChooserCore::m_sdcardDir: /storage/extSdCard/Android/data/org.opencpn.opencpn/files
I/OpenCPN (27766): invokeDelegateMethod onWindowFocusChanged
I/OpenCPN (27766): FileChooserDialog selected: watchdog_pi-2.4.21.9-android-armhf-16.xml
I/OpenCPN (27766): invokeDelegateMethod onWindowFocusChanged
I/OpenCPN (27766): isFileChooserFinished:  returning file:/storage/emulated/0/Download/watchdog_pi-2.4.21.9-android-armhf-16.xml
I/OpenCPN (27766): setBackButtonState1
I/OpenCPN (27766): enableOptionsMenu 1
I/OpenCPN (27766): FileNotFound: 
I/OpenCPN (27766): FileNotFound: 
I/OpenCPN (27766): FileNotFound: 
I/OpenCPN (27766): FileNotFound: 
I/OpenCPN (27766): FileNotFound: 
I/OpenCPN (27766): FileNotFound: 
I/OpenCPN (27766): ShowBusyDismiss
D/OpenCPN (27766): scanSerialPorts Port: Vendor 05C6 Product 904C CdcAcmSerialDriver
D/OpenCPN (27766): scanSerialPorts results:AUSBSerial:USBDP-05C6/904C;
I/OpenCPN (27766):   getAndroidLocaleString language ID is: en_US
```


```
E/OpenCPN (27766): SD Card's directory: /storage/extSdCard/Android/data/org.opencpn.opencpn/files
E/OpenCPN (27766): FileChooserCore::m_sdcardDir: /storage/extSdCard/Android/data/org.opencpn.opencpn/files
I/OpenCPN (27766): invokeDelegateMethod onWindowFocusChanged
I/OpenCPN (27766): FileChooserDialog selected: pypilot_pi-0.21.3.0-android-armhf-16.xml
I/OpenCPN (27766): invokeDelegateMethod onWindowFocusChanged
I/OpenCPN (27766): isFileChooserFinished:  returning file:/storage/emulated/0/Download/pypilot_pi-0.21.3.0-android-armhf-16.xml
I/OpenCPN (27766): FileChooserDialog
I/OpenCPN (27766): /storage/emulated/0/Android/data/org.opencpn.opencpn/files
E/OpenCPN (27766): Found SDK 19 or greater
E/OpenCPN (27766): eSL not null
E/OpenCPN (27766): 0/ 2
E/OpenCPN (27766): eSL content: 0 /storage/emulated/0/Android/data/org.opencpn.opencpn/files
E/OpenCPN (27766): 1/ 2
E/OpenCPN (27766): eSL content: 1 /storage/extSdCard/Android/data/org.opencpn.opencpn/files
E/OpenCPN (27766): Found SDK 21 or greater
E/OpenCPN (27766): Checking directory: /storage/emulated/0/Android/data/org.opencpn.opencpn/files
E/OpenCPN (27766): Checking directory: /storage/extSdCard/Android/data/org.opencpn.opencpn/files
E/OpenCPN (27766): ... is removable
E/OpenCPN (27766): ... only need R/O

```

**Comment by bdbcat** [comment]
Rick...
1.  I meant the normal opencpn logfile, as on the desktop version.  You have found the Android debug log, useful for other purposes, but not so much for plugin debugging.
2.  Anyway, the trouble was in the plugins Beta branch.  The validation errors prevented the merged XML from being created, so there was nothing to load.  Fixed now.  Watchdog and pypilot both appear after installing the Beta catalog.  I have tested neither.

**Comment by rgleason** [comment]
Last night when I plugged into Windows USB to transfer the xml files, Verizon started automatically updating USB drivers, then it went on to "updating" my cell software, then failed and tried to "repair" my cell phone such that I could not get out of it. After several tries the phone software was installed, and my contacts retrieved which was good. Then I had to reconfig email and my programs.  I now have considerably more space available so I am very happy about that, but if you have an old s4 verizon watch those programs like a hawk. The prompts are very bad/non existent.  The phone and setup is all back now, better and faster than ever.

I am going to reinstall the android beta version now..

**Comment by rgleason** [comment]
I sent the O beta android link to myself on the cell phone and downloaded the apk to downloads, under security enabled installing apps not from the Playstore, and found I could install a new installation next to my existing one, but I am not finding another icon for my original installation. Perhaps I misunderstood the menus.  I guess I'll have to set up the charts again.

Anyway, after setting [pluginss]  catalogexpert=1 in opencpn.conf,  I was able to select the "beta" channel, update that channel, and then download, install and enable both plugins.  

Pypilot preferences is greyed out and I did not see an icon in the toolbar for pypilot so that was the end of testing for pypilot.

Watchdog has a toolbar icon and the initial menu is a small sliver of white and is too small and reluctant to be stretched out into a real menu.  Even when I was able to carefully double tap and select "New" alarm from the popupp menu, this small silver of a screen did not resize to show the new alarm. I added several alarms and found that several alarm bells turned on..  That was the extent of my testing at this point. I believe that watchdog alarms are working but they are unusable at this point due to the UI whiich needs some improvement for Android. I believe these improvements may also make it clearer to Windows, Liniux and other users how this great tool is initially setup.

I concur with Dave that the UI needs some work for Android.
I would like to know how or what I should do to further test pypilot.

Perhaps Sean can step in here and help us get these plugins across the goal line so they can be deployed.

**Comment by rgleason** [comment]
I guess I found the android logfile because the other one did not seem to be present.  Now I have found it using the Samsung Folder Browser.

**Comment by rgleason** [comment]
watchdog_pi  ci  circleci-builld-android-armhf.sh   has this change
https://github.com/rgleason/watchdog_pi/commit/3de83c5d63d4e65aa1c6229bb42f9176dc499302 

 ```
remove  -DCMAKE_AR=/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-android-ar \
add  -DCMAKE_AR=/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar \
```

Is this a change that should propagate or should it be only for watchdog?
I tried it with pypilot thinking it should be propagated and it failed.

**Comment by bdbcat** [comment]
Rick...
Should be propagated.

**Comment by rgleason** [comment]
Ok, that is good to know, but the new change is failing in testplugin and pypilot  (see pypilot issue)

https://github.com/OpenCPN/plugins/issues/249

and for testplugin
https://github.com/rgleason/testplugin_pi
Build Log https://app.circleci.com/pipelines/github/rgleason/testplugin_pi/210/workflows/9bc02633-6759-402f-9a0b-0d9f474d013f/jobs/1998

Missing cmakelists.txt
CMake Error: The source directory "/home/circleci/project/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by rgleason** [comment]
It was failing because I commented out using "#" and the end of the line had  "\"  you cannot do that!

Currently  Watchdog android works, but the menu  is frozen. 
I am closing this now because that is a separate matter.
