### ISSUE TITLE
pypilot  change to circleci-build-android-armhf.sh fails, then revert and it fails

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#249]
Thinking the change to watchdog_pi  circleci-build-android-armhf.sh   should be propagated,
I changed the same line in pypilot  and it failed 3 times.
So I reverted it and it still failed!
https://github.com/rgleason/pypilot_pi/tree/frontend2/ci 

Both of these lines are failing now.
```
DCMAKE_AR=/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-android-ar \
#  -DCMAKE_AR=/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar \    
```

**Comment by bdbcat** [comment]
Where is the buildlog?

**Comment by rgleason** [comment]
I am sorry, wrong branch  should be frontend2 on this plugin
https://github.com/rgleason/pypilot_pi/tree/frontend2

https://app.circleci.com/pipelines/github/rgleason/pypilot_pi?branch=frontend2
BUILD LOG  (one of them)  
https://app.circleci.com/pipelines/github/rgleason/pypilot_pi/9/workflows/584b2606-9d84-4c99-978f-e08fc3033757/jobs/107

```
CMake Error: The source directory "/home/circleci/project/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

```

**Comment by bdbcat** [comment]
rick...
In something like this (circelci android build script)
```
  -DCMAKE_AR=/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-android-ar \
#  -DCMAKE_AR=/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar \    
  -DCMAKE_CXX_COMPILER=/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++ \
  -DCMAKE_C_COMPILER=/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang \
  -DOCPN_Android_Common=OCPNAndroidCommon-master \

```

You cannot make "#" comments, because of the last character continuation signal "\"
So, to fix, just remove the line with the "#" as first character.

**Comment by rgleason** [comment]
I just learned something. Thank you.    No #  with \ !!!! 

So consider this fixed and stripping symbols from flatpak done in testplugin (frontend2)
I've kind of lost track. Is there anything else to change/fix (provided everything builds?)

**Comment by bdbcat** [comment]
There should be no more changes (famous last words...)
To debug pypilot, take a close look at the OCPN logfile.  You will probably find some indication of a problem as it tries to load the plugin.

**Comment by rgleason** [comment]
I am learning it is like swimming, there is always more water!
I think these are all building for all environments now (maybe just one last one for pypilot that is running)
https://cloudsmith.io/~opencpn/repos/pypilot-beta/packages/?q=0.22.4.0*metadata
https://cloudsmith.io/~opencpn/repos/testplugin-prod/packages/?q=1.0.137.0*metadata
https://cloudsmith.io/~opencpn/repos/watchdog-prod/packages/?q=2.4.22.0*metadata

I am going to use the metadata to load the plugiins in Windows10 and Android next to test.
Do I need a special version of OpenCPN for Windows10 that supports Android?  Where would I find that?

**Comment by rgleason** [comment]
Import Plugin in Android does not seem to be working for me. I have tried testplugin, pypilot and watchdog metada files, trying both  armhf and arm644

I am going to use the Plugins Beta Channel now or maybe make my own opencpn-plugins.xml.  I was also unsure that the Beta channel actually changes when there is an update. It seems to me that plugins that are loaded and enabled remain even when you switch to Beta, but I may have that wrong.

[Watchdog-Testplugin-Pypilot.zip](https://github.com/OpenCPN/plugins/files/5214573/Watchdog-Testplugin-Pypilot.zip)

**Comment by bdbcat** [comment]
"Import Plugin in Android does not seem to be working for me. "
How so?  What happens?

Works for me.

**Comment by rgleason** [comment]
I click on the metadata file and there is no message of success.
Which android version (armhf  or arm64?) is likely to work with a old Samsung S4 phone?

**Comment by rgleason** [comment]
The "?" shows v5.2.2   and dowload of the link is

org.opencpn.opencpn-v56(5.2.2)-release.apk

**Comment by rgleason** [comment]
I made an opencp-plugins.xml for the beta catalog, set Android O on the beta catalog and closed it, then pasted the version I had built over the one in the program.  The new plugins show and install with the correct messages. The internal pllugins also show, so I guess that is the way it should be.

Testplugin has a wx asssert (see photos) and because ODraw is not loaded and there are no objects from ODAPI.h there is a message about that.

Watchdog works and alarms sound, but still has a frozen menu and is a pain to work with now.

Pypilot installs and shows completed installation message, but it does not show in the toolbar when enabled.

So I guess I am going to quit on this at this point.  

I did put all the metadata for each pllugiin in a PR to the beta branch.

**Comment by rgleason** [comment]
Testplugin has these first screens, perhaps because ODraw is not installed.

![20200913_141015_resized](https://user-images.githubusercontent.com/2363959/93026524-81562600-f5d4-11ea-8769-5023ecdc6de8.jpg)
![20200913_140926_resized](https://user-images.githubusercontent.com/2363959/93026541-a5b20280-f5d4-11ea-95bf-b0c19fe31b1c.jpg)

**Comment by jongough** [comment]
The second one shows what was found, nothing in this case. OD would need to be installed. It does show that test plugin is installed and working as a plugin.

The first picture shows there is an issue that needs sorting with the code, but as it is developer only plugin that is not a major issue.

Thanks for building the plugin.

**Comment by rgleason** [comment]
I would be interested if these work as intended on flatpak and android.  I have neither.

**Comment by bdbcat** [comment]
Rick...
You have Android.  You are seeing what I am seeing....
Also, Import plugin works on the tarball, not the XML file alone.

**Comment by rgleason** [comment]
Darn, how could I forget that! I will try it next.

Sean has made his Cloudsmith name public and I have been able to invite him to join Opencpn org!
I hope he likes it.

**Comment by rgleason** [comment]
Dave, do you have any idea which android tarball my S4 phone will like?
Is it unlikely to be arm64?

**Comment by bdbcat** [comment]
Rick...
Most likely armhf.

**Comment by rgleason** [comment]
Thanks, yes that version works.  All 3, testplugin, watchdog and pypilot  "TARBALLS" installed properly with the prompts expected, one when importing and another action to actually install the downloaded tarball.  Sometimes I had to uninstall the plugin if the version was the same.

So next we need to know if the flatpak symbol stripping is working and flatpak installs properly.  I can't do that.  Maybe Leamas will check?

Then the last thing that needs to be done is fix the frozen Watchdog screen.  I will ask Sean at the proper time, once he gets comfortable with the process.
