### ISSUE TITLE
pypilot  android builds

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#251]
@bdbcat 
We now have all the pypilot builds working with Sean's changes except Android.
https://github.com/rgleason/pypilot_pi/tree/frontend2

I believe I have applied your glshim additions to enable the Android builds, from watchdog unsuccessfully.  There are some errors which I am unable to fix.
https://github.com/rgleason/pypilot_pi/tree/frontend2   see android build records/logs.

Do you think you can help us out?  I've sent out an invite to be collaborator.  
It is the frontend2 branch.

**Comment by rgleason** [comment]
This morning I've double checked the glshim changes in watchdog and I believe I have done them in pypilot
This is the error

```
-- PluginConfigure: Using GLESv1 for Android
CMake Warning (dev) at src/glshim/CMakeLists.txt:3 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
    PROJECT_VERSION_TWEAK
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Not on Linux: building without GLX support.
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
CMake Error at CMakeLists.txt:189 (target_link_libraries):
  Cannot specify link libraries for target "pypilot_pi" which is not built by
  this project.


-- Configuring incomplete, errors occurred!
```

**Comment by bdbcat** [comment]
Rick...
I'll take a look, but it might be a couple of days until I can get to it.

**Comment by rgleason** [comment]
Thanks, in the meantime I will try to figure it out. I don't know where Sean is right now.

**Comment by rgleason** [comment]
Seans recent email:

```
I don't really know what to do either.   I can't develop these locally
so the build are remote, and it seems like it will take forever to
work this way.   I also have yet to figure out how to load the plugins
on android.   Have you?  Adding the catalogexpert option didn't help
me and I still have only vdr and test plugin in addition to the
builtin plugins.

The glshim problem is unclear because I thought we don't need glshim
anymore and can just use glesv2.   So it's my understanding that this
could be removed from the cmakelists since the plugin relies on
plugingl directory for rendering.

This isn't going to work on pypilot just yet, I'll try to at least
ifdef it so that it can build without the calibration plots

```

Perhaps you can understand what he is suggesting?

**Comment by bdbcat** [comment]
Rick...
For Sean:  "catalogexpert" must  be spelled exactly "CatalogExpert".  I think that plugin import works for you, so please teach Sean so that you and he are at the same point.

Also, please suggest to Sean that he study the ci scripts and resulting buildlogs for Android builds.  With some local modification to the build scripts, the builds can be done locally, once the workflow is understood.  And then the plugin tarball can be imported.  I do this regularly for oeSENC, in process now.
I'm following all, and hope to have something concrete tomorrow.  Other priority stuff in the meantime.

**Comment by rgleason** [comment]
I've passed that on to Sean. I have tested the current v0.22.4.7 on Windows and I am now getting a toolbar icon and all the menus.  The plugin seems to be landing in the right place for windows %localappdata%\openpcn\plugins\pypilot_pi.dll  but there is no data directory, perhaps it is not needed.
The directory functions start at pypilot_pi.cpp Line 589 and uses

`wxString pypilot_pi::StandardPath()`

rather than the newer API 1.16
`
extern DECL_EXP wxString GetPluginDataDir(const char* plugin_name);`

or the older
`
 extern "C"  DECL_EXP wxString *GetpSharedDataLocation();`

The plugin dll seems to land in the proper place so perhaps it is ok.

I am going to make a PR to the Beta directory for this new Version of Pypilot, just for testing purposes.

**Comment by rgleason** [comment]
BTW  I added the PR to the master catalog because the plugin is working from all appearances and it does not include the Android builds.

**Comment by bdbcat** [comment]
Rick
I succeeded to build for Android by removing the "Calibration" modules, and friend classes.
I am not sure what will happen at run-time, but it should be ready for an "Import tarball" test now.
Let me know how it goes.
Dave

**Comment by rgleason** [comment]
Yes, they all built except flatpak which failed to install freedesktop... I have instructed it to "Rerun from Fail"
and will make a PR to plugins shortly.  Thank you. I think Sean has some work to do on Calibration to make it compatible and will advise him.

Thank you!

**Comment by bdbcat** [comment]
Rick...
Please advise Sean that he should implement the calibration methods without using GL at all. " Android cannot support multiple wxGLCanvas windows as he has implemented.  Use a simple wxDC drawing window."

**Comment by rgleason** [comment]
Thank you Dave, will close this now. Have made an issue  under pypilot on github for Sean.

**Comment by seandepagnier** [comment]
> Rick...
> Please advise Sean that he should implement the calibration methods without using GL at all. " Android cannot support multiple wxGLCanvas windows as he has implemented. Use a simple wxDC drawing window."

Dave,

How does the radar plugin work then?

I need 3d for these plots so it's not really possible to do using wxpaint.   It's best this is just disabled on android and I'm implementing it in webgl so it works in a browser and that should work on android.

**Comment by bdbcat** [comment]
Sean...
Android seems to support only one GL context, at least as far as I have been able to test.
The RADAR overlay on the chart simply executes GL commands against the existing chartdisplay GLcontext, so this function could probably work on Android.  Not yet tested.

I doubt the separate PPI display of the RADAR plugin will work on Android without serious modification, since I think it tries to open a new wxGLCanvas window class, with of course a new GL context.  That will not work directly.

**Comment by seandepagnier** [comment]
I find it strange that multiple gl contexts are not supported, but I wouldn't be surprised if it doesn't work in our environment.

It's fine if the plots don't work on android.
