### ISSUE TITLE
ocpn-plugins.xml in .gitignore

### ISSUE THREAD

**Issue by bdbcat** [OpenCPN/plugins#261]
If "ocpn-plugins.xml" is in .gitignore, then the XML generation process fails.
There is an override ("force") parameter available, but I think this will need to be done in the ocpn-metadata python tool code?
I did temporary workaround by removing "ocpn-plugins.xml" from .gitignore
Thoughts?

**Comment by leamas** [comment]
@bdbcat : This is outdated. Can you please close?
