### ISSUE TITLE
Plugins: All, current issues

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#262]
Use Shipdriver as an example for these changes: https://github.com/Rasbats/shipdriver_pi

- mingw: wrong metadata target. #55    (fixed in rgleason/testplugin_pi frontend2 v1.0.139)
- Unstripped mingw plugin way too big. #56
- [MacOS updates to use XCode 11.0  (by Nov 1)](https://github.com/OpenCPN/OpenCPN/issues/2066)
- Support PluginManager for Ubuntu2004/ARM64 (beta) [#2047](https://github.com/OpenCPN/OpenCPN/issues/2047)
- Checksum support for downloaded tarballs.[ #2046](https://github.com/OpenCPN/OpenCPN/pull/2046)   (Future?)

Also Nov 1 plugin devs will need to have a docker account and pw to use docker MacOS 11.0 builds

**Comment by leamas** [comment]
Just an administrative note: When we discover bugs affecting all plugins, filing bugs is IMHO a better way than to create lists. A bug is a point where we can cooperate in a much better way than a TODO-list

See for example how I handled the unstripped mingw issue in #2065. Also note that this is already filed against testplugin_pi.

Also note the there is no decision on if/when to move the Xcode version.  If possible, we need input from Pavel.

Besides the obvious bugs (which should be filed), the shipdriver_pi contains a lot of changes related to cleaning up and simplifying the code. This input is IMHO only useful for someone able to make PRs based on them.  Practically, when it comes to testplugin and the framework this should IMHO be Jon's task to decide. 

You can perhaps be helpful by making PRs based on shipdriver, primarily in the ci/ directory and related configuration.

**Comment by leamas** [comment]
To be somewhat more clear: Fixing testplugin so it works is fine. But you really, really should make a PR against Jons testplugin repo since this is the point where testplugin is maintained.

Unless, of course, you intend to maintain  testplugin yourselt. You should the declare officially that you are forking Jons's project. I don't think this is what you want, though.

**Comment by rgleason** [comment]
Your point is good, the list is intended to be helpful. 

I have updated many plugins of others and pushed them to plugins master, however the PI owners don't always want to merge my pr, even when bdbcat is helping out. So we just continue, and it is clear that things are not black and white.

**Comment by rgleason** [comment]
Closing
