### ISSUE TITLE
Climatology no longer builds for Android

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#289]
Android builds fail now, previously they built and did not require glshim.

1. In the previous version the glslim directory and files were not needed. Is this now required because of the way FrontEnd2 is now written>
2. There are RenderOverelay and Hidden overloaded functionss
3. There are warning assciatedd with pidc.cpp

https://app.circleci.com/pipelines/github/rgleason/climatology_pi/71/workflows/121ab195-43af-456a-b38a-209b64012baa/jobs/790
https://app.circleci.com/pipelines/github/rgleason/climatology_pi/71/workflows/121ab195-43af-456a-b38a-209b64012baa/jobs/790

How can I fix these?

**Comment by rgleason** [comment]
From the build log  
```
CMake Error at cmake/PluginConfigure.cmake:336 (add_subdirectory):
  add_subdirectory given source "src/glshim" which is not an existing
  directory.
Call Stack (most recent call first):
  CMakeLists.txt:126 (include)

```
So I copied glshim over from one of Sean's other plugiins, but climatology did not use glshim in the previous version which did compile for Android, but had some unresolved interface issues. 
Now Android does not work.

Then I thought that perhaps Frontend2 had changed to require glshim in order to build for Android and I found [cmake/PluginConfigure.cmake  ](https://github.com/rgleason/climatology_pi/blob/1e2eb3f7f9a0e6e91464683455696e12cf41dda8/cmake/PluginConfigure.cmake) 
Line 202 and 203
```
      set(wxWidgets_USE_LIBS ${wxWidgets_USE_LIBS} gl)
        add_subdirectory(src/glshim)

```
I am wondering if this was added for a previous plugin, and if it is really needed for climatology.
I looked at the previous version of[ PluginConfigure.cmake  in Climatology](https://github.com/rgleason/climatology_pi/blob/2466d9f3bc2cbdd4679b3d47c11c303660280828/cmake/PluginConfigure.cmake)) and found these lines further down at LIne 277 and 278  

```
        set(wxWidgets_USE_LIBS ${wxWidgets_USE_LIBS} gl)
        add_subdirectory(src/glshim)

```

So now I am wondering why this is a problem now, It worked before!

**Comment by bdbcat** [comment]
I'll try to take a look at this tomorrow.

**Comment by bdbcat** [comment]
Rick...
I cannot login to your circleci account to look at the build logs.
Please copy somewhere else for my analysis.

**Comment by bdbcat** [comment]
I guess I will need to fork your repo. Tomorrow....

**Comment by rgleason** [comment]
The links to cloudsmith accounts are somewhat strange, but this is to the main account for Opencpn
https://cloudsmith.io/~opencpn/repos/
I ended up making bookmarks in my browser for all the ones I am aware of.
Here is the [link ](https://cloudsmith.io/~opencpn/repos/climatology-prod/packages/)to the repository for the recent climatology deployment

You, Jon and Leamas has access to my [climatology_pi fork](https://github.com/rgleason/climatology_pi)  
I hope these links work and help:
[Android arm64 failed build report](https://app.circleci.com/pipelines/github/rgleason/climatology_pi/71/workflows/121ab195-43af-456a-b38a-209b64012baa/jobs/790)
[Android armhf failed build report](https://app.circleci.com/pipelines/github/rgleason/climatology_pi/71/workflows/680d9a44-d3e2-4918-90db-b3e65b9300f8/jobs/786)

**Comment by bdbcat** [comment]
Rick...
Working on this now.  Some progress. More later.
Thanks

**Comment by bdbcat** [comment]
Fixed now.
The change in
` ci/circleci-build-android-armhf.sh`

https://github.com/rgleason/climatology_pi/commit/2d6250b91bfe29179147dd4bab800b3ccc492d99

 probably applies to other Frontend2 builds as well.

Dave

**Comment by jongough** [comment]
Frontend1 1.0.144.0 has a change to allow the use of 'precompiled' headers within wxFormBuilder. This means that the generated header file does not need to be changed. Just add "extra_formbuilder_headers.h" to the Project/C++ Properties/class_decoration/header . Then add a new file to the in-files folder called "extra_formbuilder_headers.h.in" with the header code you need included, in this case:
```
#ifdef __OCPN__ANDROID__
#include "android/wx/datectrl.h"
#else
class wxDatePickerCtrl;
#endif
```
You may want to put a bit more in there, i.e. an explanation.
wxFormBuilder will then create an include for this file in its generated header file.

**Comment by rgleason** [comment]
Thank you David and Jon for all your help. I look forward to seeing how this is done.

PS: I will close this after I get into it further and have uploaded new files to plugins.

**Comment by rgleason** [comment]
This worked for awhile. Now it isn't. Will investigate.  Closing now.
