### ISSUE TITLE
ci - fails due to unavailable 'http://opencpn.navnux.org/build_deps' files

### ISSUE THREAD

**Issue by Rasbats** [OpenCPN/plugins#292]
Is the server down?

Appveyor:
```
Start-FileDownload http://opencpn.navnux.org/build_deps/wxWidgets-3.1.2.7z
Start-FileDownloadInternal : Error downloading remote file: One or more errors occurred.
Inner Exception: Remote server returned 403: Forbidden
```
CircleCI:
MacOSX build
```
+ wget -q http://opencpn.navnux.org/build_deps/wx312_opencpn50_macos109.tar.xz
+ tar xJf wx312_opencpn50_macos109.tar.xz -C /tmp
tar: Unrecognized archive format
```

**Comment by rgleason** [comment]
Mike Location of this file has changed. See https://www.cruisersforum.com/forums/f134/beta-test-technical-30929.html#post3291791

**Comment by Rasbats** [comment]
Searching now for wxWidgets-3.1.2.7z.

**Comment by rgleason** [comment]
Keep an eye on this Issue for necessary updates to the location for vital building files.
https://github.com/OpenCPN/OpenCPN/i...ment-740649256
Perhaps someone will soon publish on CF Beta thread,  the new paths for these vital files for building, when known.

**Comment by Rasbats** [comment]
Discussion continued here:
[https://github.com/OpenCPN/OpenCPN/issues/2125](url)

Closing this issue.
