### ISSUE TITLE
Climatology link broken

### ISSUE THREAD

**Issue by mbdb** [OpenCPN/plugins#298]
Hi everyone,
I recently downloaded opencpn 5.2.4 on ubuntu 20.04, using ppa.
I tried to download the climatology plugin from plugin manager, and it says: "Download Error".
Indeed, when I have a look in ocpn-plugins.xml, the tarball file does not exist:
https://dl.cloudsmith.io/public/opencpn/climatology-beta/raw/names/climatology_pi-1.4.16.0-msvc-x86_64-10.0.14393-MSVC-tarball/versions/1.4.16.0+117.7501f36/climatology_pi-1.4.16.0-msvc-x86_64-10.0.14393-MSVC.tar.gz

Regards,
Max

**Comment by rgleason** [comment]
Thanks
Sorry I should remove that file. I was waiting until certain multiple build files were improved and updated. This process has become more prolonged, so I will remove this file now.

**Comment by rgleason** [comment]
I believe the links are now fixed, but we there is no flatpak or android armhf build.
Also working on icon problem,  however the plgin workss

**Comment by rgleason** [comment]
Should be fiixed. Please close.

**Comment by mbdb** [comment]
Thanks !!
