### ISSUE TITLE
Deployment: How?

### ISSUE THREAD

**Issue by leamas** [OpenCPN/plugins#3]
While OpenCPN could be modified to download ocpn-plugins.xml from the master branch I doubt this is the right strategy. Maintainers should have a chance to review a generated catalogue before it goes into production.

One solution could be to deploy the catalogue on github, cloudsmith or elsewhere. Works, but adds some complexity.

Personally, I think the easiest solution is to use a separate branch called *release* or so. This way, the catalogue could be generated on the master branch, reviewed and finally committed to the release branch. To make ocpn download from a specific branch should be trivial -- after all, this is just text.

**Comment by leamas** [comment]
I have been playing with a GUI mockup recently.  Revising ideas:

  - We use two or more branches for the catalogue. This could reflect e. g., a stable  and an
    experimental branch. Other options includes master (latest available) etc.
  - Clients checks dynamically for available branches
  - There is a an option to select branch for users.
  - There is an option to select a custom URL focused on plugins devs which publishes an own catalogue.
    This sort of advanced, normally hidden and obsoletes the branch option.

This should be flexible enough while reasonable simple for users and for devs. Using git branches this way is also seems to be quite common these days.

**Comment by rgleason** [comment]
I think the stable and experimental branches will help with confirmation and testing recent changes in the xml.
You're giving greater flexibility than I had even thought off, but perhaps it is needed.

**Comment by leamas** [comment]
I have been playing with some code. The more I explore the way to just use git branches on this repo (OpenCPN/plugins) the better it looks, actually.

If no one chimes in here I will close this bug and go for the initial proposal. Note that the branches, their name and the actual numbers of them, is dynamic. The idea is to reflect whatever branches being available in the git repo.

**Comment by rgleason** [comment]
Each plugin has some branches dedicated to the catalog (xml) such as master, release, stable,  experimental (or test?).  Sounds reasonable.

However it works out, I think this is a reasonable necessity:
"Maintainers should have a chance to review a generated catalogue before it goes into production."

I think Dave is asking/assuming that the PI authors will double check their plugins first.

**Comment by leamas** [comment]
> Each plugin has some branches dedicated to the catalog (xml) such as [...]

Perhaps,  but his has nothing to do with this. This is about the overall ocpn-plugins.xml which has exactly one version covering all plugins.

The idea is that users should be able to select a channel from which they update their catalog, similar to how browser users select their browser update channel. One channel represents for example the released version, another just nightly builds. There will be time to flesh out the details. The point is that a user channel is just a git branch.

**Comment by rgleason** [comment]
Good point, I incorrectly thought that applied to the individual plugins. Got it now. Thanks.

In thinking about the Plugin author, testing his deployment and his own xml file, is there going to be a way for him to aim the PI Installer at a particular xml file to see if it installs properly? Or should we just assume that the xml works?

**Comment by leamas** [comment]
> Or should we just assume that the xml works?

Certainly not. Sources and tools to make local testing exists within this (plugins) project. However, we need some docs -- this is basically #2.

**Comment by leamas** [comment]
Seems like we have more or less decided how this works. In summary

   - ocpn-plugins.xml is maintained within this project.
   - Users can download updated versions directly from github (=this project).
   - Devs can clone this repo and create their own variant which is accessible from the GU using a custom URL.
   - Devs can issue PR:s against this repo to have their updates incorporated in the main ocpn-plugins-xml. 

We're done. closing
