### ISSUE TITLE
weather_routing -  Issues with 10 environments

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#30]
https://github.com/rgleason/weather_routing_pi/runs/456711375
"permission denied" for buster, fedora, bionic, and xenial 

buster - /bin/bash: ci/circleci-build-debian.sh: Permission denied
Exited with code exit status 126  CircleCI received exit code 126

fedora - /bin/bash: ci/circleci-build-fedora.sh: Permission denied
Exited with code exit status 126   CircleCI received exit code 126

bionic - /bin/bash: ci/circleci-build-debian.sh: Permission denied
Exited with code exit status 126  CircleCI received exit code 126

xenial - /bin/bash: ci/circleci-build-debian.sh: Permission denied
Exited with code exit status 1   CircleCI received exit code 1

What have I forgotten/not done?  Any ideas?
-Exit code 126 is "Command invoked cannot execute"
https://support.circleci.com/hc/en-us/articles/360002341673-Identifying-Exit-Codes-and-their-meanings

Yet testplugin which these changes are based on,  is building these environments.
https://github.com/jongough/testplugin_pi/commits/cmake_flatpak_test

**Comment by bdbcat** [comment]
Check the permissions on your scripts, especially "x" flag.

**Comment by rgleason** [comment]
In windows the scripts files are "everyone"  allow everything as near as I can determine.

**Comment by rgleason** [comment]
my circleci settings don't seem to have any related settings.

**Comment by bdbcat** [comment]
Rick...
All these CI scripts run on a linux environment.  So linux permission model prevails.

Easiest fix is to clone your repo on a linux box, fix the permissions for the scripts, and then commit the result.

**Comment by rgleason** [comment]
I guess that means I need git and github in my little old virtualbox linux ubuntu... so little space left. Must clean out and up HD now... maybe there is a workaround.

**Comment by rgleason** [comment]
Found this.  https://stackoverflow.com/questions/21691202/how-to-create-file-execute-mode-permissions-in-git-on-windows

https://stackoverflow.com/questions/6476513/git-file-permissions-on-windows
```
Handy one-liner for Git Bash:
find . -name '*.sh' | xargs git update-index --chmod=+x
It will mark all .sh file as executable. After that, you just have to git commit.
```

**Comment by rgleason** [comment]
I opened the msvc command prompt
```
cd  C:\Users\Rick\Documents\GitHub\weather_routing_pi
bash
find . -name '*.sh' | xargs git update-index --chmod=+x
error: build/apppveyor-upload.sh: cannot add to the index - missing --add option?
fatal: unable to process path /build/appveyor-upload.sh
```

**Comment by rgleason** [comment]
Thanks Dave, using Bash from the git directory
bash
find . -name '*.sh' | xargs git update-index --chmod=+x  --add
and then making a commit and pushing, fixed the builds.

https://github.com/rgleason/weather_routing_pi/runs/458031896

Now need to check cloudsmith and make the ocpn_plugins.xml
