### ISSUE TITLE
PR to beta catalog results in error when check is made

### ISSUE THREAD

**Issue by Rasbats** [OpenCPN/plugins#301]
![failure advice from github](https://user-images.githubusercontent.com/2537240/102774222-7ef92a00-4382-11eb-800c-6a9c07ae7d75.jpg)
![pul request failed check](https://user-images.githubusercontent.com/2537240/102774224-802a5700-4382-11eb-9c72-a2f14b4d64ce.jpg)

**Comment by Rasbats** [comment]
Fixed by Dave. Thanks.

**Comment by rgleason** [comment]
Actually fixed by Jon, PR accepted by Dave
