### ISSUE TITLE
ci: flatpak: Broken link

### ISSUE THREAD

**Issue by leamas** [OpenCPN/plugins#309]
A lot of of plugin ci scripts has (perhaps) been failing lately. The problem is (was) a link like http://mumin.crabdance.com/opencpn/repo which returned an "Access denied" status.

This is problem is now fixed, and the link is available again. So technically, tis bug should be closed. However, keeping it open for some time to the problem visible.

Just rebuilding the flatpak plugin should be fine.

**Comment by rgleason** [comment]
Thanks, Alex, much appreciated. I will try climatology again.  Hope you had a peaceful Xmas.

**Comment by rgleason** [comment]
Alec, it worked. Thanks.

**Comment by leamas** [comment]
time to close...
