### ISSUE TITLE
Plugin Catalogs scrambled - reports

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#31]
Rick...

> Plugin catalogs were scrambled. Fixed now.
> 
> Current contents:
> master: Squiddio only
> Beta: oeSENC, oeRNC, Radar, and test-plugin.
> 
> Please retest and report.
https://github.com/OpenCPN/plugins/issues/24#issuecomment-588562086

Yes, Master is as above.
However Squiddio needs some attention and improvment re CommonName I think.

There are two instances in the PI List

- "squiddio 1.0.17" managed which has the reinstall, but no enable/disable
- "Squiddio 1.0"  unmanaged which has the enable/disable

It will eventually get fixed I hope!
Someone should give Mauro Calvi a PR to fix it. I am still finding my way otherwise I would do it.
https://github.com/mauroc/squiddio_pi 

![Screenshot (553)](https://user-images.githubusercontent.com/2363959/74939130-5a789e00-53bd-11ea-83e3-545669aefa9a.png)
![Screenshot (552)](https://user-images.githubusercontent.com/2363959/74939143-5fd5e880-53bd-11ea-92b2-86559885a559.png)

**Comment by rgleason** [comment]
Yes, just checked using Master catalog with Windows 10 and squiddio as shown above.
I think Squiddio needs some attention and improvement re CommonName, because there are two instances shown in the Plugin List:
    "squiddio 1.0.17" managed which has the reinstall, but no enable/disable
    "Squiddio 1.0" unmanaged which has the enable/disable

This is a "commonname" problem. The 1.0..17 version is not using the plugin's actual "common_name" which is found in src/squiddio_pi.cpp I believe.
Found this in squiddio_pi.ccp at about line 944
```
wxString squiddio_pi::GetCommonName() {
    return _("Squiddio");
```

So squiddio v1.0.17 should be using "Squiddio"

**Comment by bdbcat** [comment]
Rick...
1.  Yes, Squiddio needs work.  At the moment, the managed plugin was built by Alec, and has had no further attention.  We should ping Mauro, and send a PR to his github repo, with instructions on how to build, etc.  Would you care to tackle that?
2.  The current Squiddio unmanaged build, available from opencpn.org, uses an older pluginAPI.  So it knows where to get icons.  However, if it is adapted to your current workflow, it will show puzzle pieces.  
Kees gets around this problem in Radar by maintaining two branches in github;
  a) master, to build an unmanaged plugin using older API.
  b) "ci", to build a managed plugin using new API.

I do the same for oeSENC and oeRNC, although they do not have toolbar icons.
Developer choice...

Dave

**Comment by rgleason** [comment]
This is very helpful. Thank you. Will contact Mauro in a day or so.

**Comment by rgleason** [comment]
Closing, Mauro is working on NDBC Bouys feature.
I have forked that project and changed it to the PI Manager FrontEnd Opt 1
in my repository, branch ci

This problem has been fixed and can be used from the Alpha catalog
