### ISSUE TITLE
beta branch: Outdated ocpn-plugins.xsd

### ISSUE THREAD

**Issue by leamas** [OpenCPN/plugins#313]
The ocpn-plugins.xsd file in the beta branch is very old  and outdated, Please update using the files in master branch, something like

    $ git checkout beta
    $ git checkout master ocpn-plugins.xsd ocpn-plugin.xsd
    $ git commit -am "Updaiting xsd files from master"

EDIT: Wrong filename (!): ocpnm-plugins-xml -> ocpn-plugins.xsd

**Comment by bdbcat** [comment]
Done, also for Alpha branch.

**Comment by leamas** [comment]
Right, thanks. Closing
