### ISSUE TITLE
Adding a beta version to OpenCPN/plugins beta branch

### ISSUE THREAD

**Issue by Rasbats** [OpenCPN/plugins#314]
When trying to merge a beta for UKTides the mingw metadata file was not accepted.

![102797529-b6c69880-43a7-11eb-9790-5eefc77e5a60](https://user-images.githubusercontent.com/2537240/103313423-eca6f500-4a17-11eb-9cc0-39663fe056c6.jpg)

mingw-x86_64 is in 'ocpn-plugin.xsd' but the metadata file is not accepted.

UKTides metadata file has a checksum. Is this important?

**Comment by bdbcat** [comment]
XSD file have been updated on Beta branch.  See https://github.com/OpenCPN/plugins/issues/313
Please re-submit your PR.  Should pass validation now.

**Comment by Rasbats** [comment]
PR re-submitted. Validation correct.
