### ISSUE TITLE
weather_routing_pi  (Beta Catalog & Custom now) on Win & Ubuntu 18.04

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#32]
Have updated the Alpha meta-url for Sean's plugins.

Removed all testplugin xml.
Added xmls

- weather_routing-plugin-darwin-10.13.6.
- weather_routing-plugin-debian-10.
- weather_routing-plugin-fedora-29.
- weather_routing-plugin-flatpak-18.08
- weather_routing-plugin-mingw-10.
- weather_routing-plugin-msvc-10.0.14393.
- weather_routing-plugin-ubuntu-16.04
- weather_routing-plugin-ubuntu-18.04

On alpha channel it seems to work properly and when switched to 'Beta' catalog the plugin's toolbar icon reverts to a green puzzles just as expected.

[Added Later] However when I go back to the 'Alpha' catalog, two toolbar icons appear, the normal weather_routing icon and the green puzzle icon still shows. They both work and when I try to hide/show the toolbar, both icons still remain. When I shut OpenCPN down and reopen, while on the Alpha channel, the green puzzle toolbar icon no longer shows, and the normal weather_routing toolbar icon shows.

![Screenshot (555)](https://user-images.githubusercontent.com/2363959/74957486-961f6200-53d5-11ea-9e62-e7c18e37400e.png)

![Screenshot (556)](https://user-images.githubusercontent.com/2363959/74957494-9a4b7f80-53d5-11ea-81e3-cbab5c00646b.png)

If others could check the operation of ubuntu and the other OS on the alpha channel that would be very helpful, using this issue to report any problems.  I will also try Ubuntu 18.04 later.

However I am going to forge ahead and build a new version for the Beta Channel next, later today.

**Comment by rgleason** [comment]
I have learned that the weather_routing_pi program automation is not creating the proper tarball-url  xml field for all xml files other than msvc (which is correct), 

 for both 
Alpha catalog or rg-alpha meta-url.
Beta catalog with versio increment.
and probably Master with  version increment.

The corrected paths are attached.

Now used for rg-alpha   meta-url to Alpha Catalog
[Rg-alpha-Plugin-wxrouting-repair-tarball-url.txt](https://github.com/OpenCPN/plugins/files/4233865/Rg-alpha-Plugin-wxrouting-repair-tarball-url.txt)

Now used for Beta  (new PR made to opencpn/plugins  Beta branch
[Plugin-wxrouting-repair-tarball-url.txt](https://github.com/OpenCPN/plugins/files/4233867/Plugin-wxrouting-repair-tarball-url.txt)

Next problem is to actually fix the bad TARBALL-URL problem.

Also refer to 
Plugin Manager: Ubuntu - Alpha and Custom catalogs not working #1709
https://github.com/OpenCPN/OpenCPN/issues/1709
Ubuntu does not work.

Also see this 
Plugin Manager: WeatherRouting Ubuntu url misdirect #1708
https://github.com/OpenCPN/OpenCPN/issues/1708

This problem has to be fixed before we do anything else.

Exactly how is Beta catalog supposed to be used?

1.  Should we increment the version, because that pushes packages to my opencpn-plugins-pkg
and pushes tarballs and metadata to opencpn-plugins-prod?

2. OR for the "Beta" Catalog should we just be pushing all packages, tarballs and metadata files to opencpn-plugins-beta?

**Comment by bdbcat** [comment]
Rick...

"Exactly how is Beta catalog supposed to be used?"
I will accept PRs to the Beta catalog, containing managed plugin metadata (XML) files, and a correspondingly rebuilt ocpn-plugins.XML.  I recommend incrementing the version on each PR, so you may track progress and bug reports.


Once more I say:
The unmanaged (Legacy) packages built by your CI workflow DO NOT WORK CORRECTLY, and we have no interest in them.  Further, I think that the packages should not be published as tagged releases in your github repo, but that is your call.  They will NOT get linked on the opencpn.org download pages, since they DO NOT WORK.

I will take a look at Alpha channel.  Last time I checked, it worked OK.  But things change.
I do not intend to moderate Alpha channel closely, as it can contain redirection over which I have no control.  It will not be available to end-users when Beta test starts, anyway.  It is mostly for the convenience of developers.

**Comment by rgleason** [comment]
Dave, I have manually fixed the tarball-url for all 8 environments on both Alpha (rg-alpha branch meta-url) and Beta (see PR).

I intend to keep making packages which will be found in the -opencpn-plugin-beta directory. or separately if a release in the pkg directory. I will try to get those fixed, but I think they might be useful at sea with no inet. Although "Custom" url might work.

**Comment by rgleason** [comment]
Additionally, the original plan was for a "transition" to the new Plugin Installer. 

In my opinion, the Plugin Installer and system has been inadequately tested and proven and there are still wrinkles and bugs in it, therefore I prefer to have the reliable old packages as backup.

If I have to, I will have a link to the cloudsmith repository for the current packaged plugins which will be located at the top of each Plugin Wiki, if that is acceptable to you, since the links will no longer be supported on the website.

**Comment by bdbcat** [comment]
Rick...
Of course it is inadequately tested.  Isn't that exactly what we are doing now?

btw., as promised, your PR has been merged to Beta, available now.
I did not see the rPI builds, though....

**Comment by bdbcat** [comment]
Is alpha branch working for you now?
If so, please close this issue.

**Comment by rgleason** [comment]
I have merged Opencpn and built it in Ubuntu 18.04, and installed, then tested wxroute using Alpha and it works, but there is an extraneous green puzzle "weather_routing" icon in addition to the correct one.

Then I tried Beta catalog and Weather_routing 1.13.4 turns into "unmanaged" and there is no selection for Installing Weather_routing_pi 1.13.5     I checked the metadata in your opencpn/plugins/ Beta branch  and find the weather_routing xml for Ubuntu 18.04 there
and the URL is   
 ```
<target>ubuntu</target>
  <target-version>18.04</target-version>
  <tarball-url>
    https://dl.cloudsmith.io/public/rick-gleason/opencpn-plugins-prod/raw/names/weather_routing-ubuntu-18.04-tarball/versions/v1.13.5.0/opencpn-plugin-weather_routing-1.13.5.0-ov50-1.16_ubuntu-18.04.tar.gz
  </tarball-url>

```
and in this file https://github.com/OpenCPN/plugins/blob/Beta/ocpn-plugins.xml it is
```
<target>ubuntu</target>
    <target-version>18.04</target-version>
    <tarball-url>
    https://dl.cloudsmith.io/public/rick-gleason/opencpn-plugins-prod/raw/names/weather_routing-ubuntu-18.04-tarball/versions/v1.13.5.0/opencpn-plugin-weather_routing-1.13.5.0-ov50-1.16_ubuntu-18.04.tar.gz
  </tarball-url>

```
which I believe is the same URL.  However it does NOT appear to be reading properly and creating an "managed" instance of weather_routing 1.13.5 in the Beta catalog.  (Nor are any of the testplugin xml's showing up at all.)   Also when I try to use this same weather_routing URL in Ubuntu 18.04 Opencpn (built today) using "Custom" URL channel, it just is blank and fails or something, in any case the weather_routing plugin data does not appear in the list as expected, what shows is the list that was there before.

Also I find that using the Beta catalog,  oesenc 4.1.0 shows and installs, but oeRNC 1.0.7 URL not found 401 and fails.

Therefore I do not believe that the BETA catalog or CUSTOM URL are working properly in **Ubuntu** 18.04 or in **Windows** or there is some misconfiguration of some sort.

**Comment by rgleason** [comment]
On Alpha catalog, showing Weather_routing installing, but there is a double icon for weather-routing (normal and green puzzle)
![Screenshot (564)](https://user-images.githubusercontent.com/2363959/75047017-1c01e280-5494-11ea-9c24-c91fb7002d54.png)


weather_routing as unmanaged on Beta
![Screenshot (566)](https://user-images.githubusercontent.com/2363959/75046835-d218fc80-5493-11ea-96a9-99457626a00d.png)


oeRNC fail.
![Screenshot (567)](https://user-images.githubusercontent.com/2363959/75046696-92521500-5493-11ea-9126-c482b7ef5260.png)

**Comment by bdbcat** [comment]
Rick...
OK, sorted this out.  Bottom line:  We cannot parse special characters in XML files, at the moment.  When we encounter a special character, everything after this point in the XML is dropped. This needs sorting out.
Meanwhile,  I have updated Beta catalog to conform, and it should work now.  Does for me.
Beta catalog now offers a managed update of WeatherRouting to 1.13.5

@Hakan...
I manually edited the Radar plugin "Authors" field to simplify your name, substituting the "å" character, temporarily.  Please discuss with Kees and correct your scripts accordingly.  I will figure out how we can make this work, and let you know when you may get your real name back.

Dave

**Comment by bdbcat** [comment]
Rick...
I cleaned Alpha branch. The only thing left there is your redirection metafile.

**Comment by rgleason** [comment]
This is considerably better on both Alpha and Beta!  Great find!  I still haven't figured out Hakan's special ascii though.  Many stars have to align, I hope it gets easier for everyone.

I am stilll a bit puzzled by Custom URL and will play with it.
I still need to properly automate the creation of the Tarball-url so I don't need to correct them all manually.

Hope closing is ok
