### ISSUE TITLE
watchdog  patch from Seans repository needed for Depth

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#333]
Sean did not merge my PR and then created a new alarm for Depth which is very useful and frequently requested. 
His work includes reformating with wxFormBuilder.
The changes are here  [add depth alarm](https://github.com/seandepagnier/watchdog_pi/commit/29cfd7784778d45896e7495e5a9aff84410a994d)

How would I make a patch of just these changes to apply to the leamas-libs branch in my watchdog repository?
Also is this the right way to do this?
I would then make a new PR back to Sean with all the changes since Jan 15.

He has also done this with Statusbar_pi, so perhaps a patch will work with that too?

Perhaps Alec would give some guidance?

**Comment by jongough** [comment]
If Sean's changes are now in his master do a fetch all from his repository, create a new branch in you repository from the branch you want as the base in your repository, i.e. the leamas-libs branch and do the merge/build/testing in that branch. You can then rebase this branch on Sean's work and see what happens. Hopefully there will not be too many conflicts. If it all falls apart you can go back to the base branch and start clean again.

Hopefully Sean's changes will not impact on frontend2, but....

**Comment by rgleason** [comment]
Done with rasbats help. Thank you.
