### ISSUE TITLE
Plugin build environments vs Use- Where to focus effort?

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#340]
We have been considering frequency of Plugin use in another Issue   
https://github.com/OpenCPN/OpenCPN/issues/2169#issuecomment-783628858

Cloudsmith keeps download data, which might help us understand what is being used and what is not, so we can perhaps trim the number of environments used?

It would be helpful to understand what environments Users are using the most and one resource is Cloudsmith downloads, looking inside each Opencpn Organization Plugin Repository where download data is presented.

https://help.cloudsmith.io/docs/download-logs
The repository download logs show you a detailed list of every file that was downloaded from the repository:
Counting Docker image downloads is a little different.

For example here is **aisradar PROD repository**
https://cloudsmith.io/~opencpn/repos/aisradar-prod/groups/

    Windows 2192
    raspian armhf buster 754
    MacOS 257
    Flatpak 74
    Ubuntu 18.04 bionic 72
    raspian armhf stretch 15
    The rest are ones and twos!

**Logbookkonni   Beta** 
https://cloudsmith.io/~opencpn/repos/logbookkonni-prod/groups/

    Windows 1750
    raspian armhf 10 buster 508
    Darwin 255
    ubuntu 20.04 gtk3 158
    ubuntu 18.04 bionic 102
    flatpak 94
    raspian armhf 9.4 21
    the rest are ones and twos and 0

Also You can also see the total downloads for each plugin/repos from the main Opencpn Organization Page
https://cloudsmith.io/~opencpn/repos/

It would also be useful to understand the frequency of use for various environment builds of OpenCPN itself.

There are pros and cons about this related to time spent updating plugin build environments that failed due to changes in the underlying docker or orb, or changes due to deprecated and dropped programming language.  Where there are 0,1, or 2 downloads it may not be worthwhile fixing build errors for that environment.  It may be better to focus on the more frequently used plugins and builds.  Certainly we can "check all boxes" to try and build all environments (and some will not build or deploy to Cloudsmith.).

However each additional environment adds to our use of Cloudsmith storage, something we should perhaps consider.

**Comment by rgleason** [comment]
Bdbcat thoughts  https://github.com/OpenCPN/OpenCPN/issues/2169#issuecomment-783847001

**Comment by leamas** [comment]
First: as I see it, the decision to  support a given platform is basically up to whoever maintains the plugin (or act as  a packager by forking and modifying it to work with workflows like frontend).  There cannot be a policy which mandates which platforms to support. Of course, there should be some advice, but that's basically it.

**Comment by bdbcat** [comment]
Yes, that is my opinion as well.
It is completely OK for devs to decide which plugins should get priority in their work.After all, we are all volunteers here, setting our own priorities dynamically.
I just think about the CF question: "Where is plugin "ABC" for my machine "XYZ"?
Two answers:
a) Sorry, not finished or available yet.  On the list, and we will get to it....
..or..
b) Sorry, we are not going to do that one, because no-one seems to want it....

Rhetorically, which is the preferred answer?

**Comment by leamas** [comment]
@bdbcat  said:

> And why do we want to trim the number of environments?

Rick has talked about the shere build time aspects. It *is* a factor, but perhaps not that important.

As I see it, the question is about the oldest platforms, like Trusty/14.04 now. Trusty support means that we need to work with really old compilers, cmake and support stuff  (notably python).  Supporting these old versions when they are obsolete both in Debian and upstreams takes a quite hight toll.  It could of course be worth it, if we have a substantial amount of users on these old platforms. But if not, this is man hours in vain.

Personally, I don't think we should support anything not supported by Debian/Ubuntu. For Ubuntu  this would mean that we drop Trusty/14.04 now, and Xenial/16.04  April this year. 

Yes, we might get the question "Why don't you build this and that plugin for Trusty". But to be honest, the same question for aarch64 Arm seems more likely. And the answer "use existing plugins or update your OS" is actually perfectly ok for Ubuntu.

But then again, it's up to whoever maintains the plugin.

**Comment by leamas** [comment]
We also have a plugin lifecycle thing here: when eventually dropping  builds for an old platform like Trusty, the idea of keeping the four latest builds in a repo collapses:   new builds will push the old but still valid Trusty builds out of the repo. At this point it would probably make sense to store them someplace where they are still kept around for some time. After all, they should still work.

**Comment by rgleason** [comment]
Helping us on this somewhat, is that if it does not build, it does not deploy, but there are times that a plugin deploys but does not work. That is the problem.

**Comment by rgleason** [comment]
> Rick has talked about the sheer build time aspects. It is a factor, but perhaps not that important.

It is important to me.  I get concurrency limits and delays on pushes and as it is, it takes 30-47 minutes to complete all environments. Right now I did two pushes to different repositories. It will be almost 1.5 hrs until they are done. Also I cannot build more than two environments locally so I am dependent on circleci or appveyor or travis to build which takes many minutes, then I have to check and see what errors resulted.  Progress is slow, particularly when in mode "monkey pushing buttons on a black box." 

Jon has suggested installing circleci CLI to speed things up, but I have not done that yet. Which I may do.

I think key environments to build at this point are:
Flatpak
Ubuntu 20.04 Focal   (only GTK3)
Ubuntu 18.04 Bionic 
Ubuntu 18.04 Bionic GTK3 
Raspberry Armhf 
Raspberry Arm64  Bionic 18.04 64
Windows
MacOS
Android  (2) if possible

10 environments, adding another package file (deb, exe, pkg) makes that 20 files + 10 metadata files.

Outdated in my opinion  (fewer than 2 users)
Ubuntu 14.04 Trusty and Ubuntu 16.04 Xenial

Unfortunately, now MacOS builds are failing with watchdog and android no longer works except on Mike's fork.

**Comment by leamas** [comment]
As stated earlier, the decision to drop trusty and/or xenial is yours. Personally, I don't think it makes sense to support platform which  has been dropped by Ubuntu. Following that logic trusty should already have been dropped, and xenial should be dropped in April.

Another possibility is of course to spread the builds on more builders. There are certainly candidates out there. Somewhat messy, but probably less job than to install a private CI server -- this is a non-trivial issue. However, Github has a concept of self-hosted runners which looks interesting, seems much easier to set up than a complete CI server.

**Comment by Rasbats** [comment]
Just for the record... I have not made any Android builds for Watchdog. Maybe confusing these with armhf builds, which did work.

**Comment by rgleason** [comment]
Ok I am dropping trusty and Xenial now.  Any suggestions about Travis problem and android?
I'm just going to comment out that stuff for the time being.

**Comment by rgleason** [comment]
Thanks for the correction Mike,  I am going to close this now. Can be reopened
