### ISSUE TITLE
GetpPrivateApplicationLocation  question

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#376]
Should this be used for user writable data for just the OS where there are problems?  ..or should it be used universally for all OS?

I've been using it universally so far.

**Comment by bdbcat** [comment]
Rick..
Need a little more context, please.
Code reference?

**Comment by rgleason** [comment]
Thank you.

This is to fix watchdog issues created by User data being written to the wrong data location, in particular, flatpak and maybe ubuntu and macos, but that is not confirmed.

See https://github.com/rgleason/watchdog_pi/issues/16#issuecomment-856379311
Please see the attached txt file for the full procedure in question
[watchdog-standardpath.txt](https://github.com/OpenCPN/plugins/files/6615862/watchdog-standardpath.txt)

The current branch I am working with is master-update  https://github.com/rgleason/watchdog_pi/tree/master-update.

Any help would be appreciated.  This situation is a little like [logbookkonni which took me days to get working right with Alec's initial help](https://github.com/rgleason/LogbookKonni_pi/blob/master/src/logbook_pi.cpp)   see line 725 and below, and it might be easier this time.  In that plugin I getPrivateApplicationLocation was used for all user configurable environments, and the icons data continued to use getPluginDataDir which the user can't write to.

**Comment by rgleason** [comment]
Thanks, bdbcat.  I think it should  be applied universally to all OS as I've been doing in plugins. Closing.
