### ISSUE TITLE
Broken metadata in master branch -- commit process problems

### ISSUE THREAD

**Issue by leamas** [OpenCPN/plugins#383]
We have broken download urls in master branch, see https://github.com/OpenCPN/OpenCPN/issues/2315.  Some of these urls are recent updates.

There is a need of a process which ensures that we at least don't commit broken metadata. This includes that the tarball url actually exists (https://github.com/OpenCPN/OpenCPN/issues/2315) and also that the checksum is OK (#365).

**Comment by rgleason** [comment]
I thought the action script validated links?

**Comment by leamas** [comment]
Seemingly not. For example there is a weatherfax_pi link https://dl.cloudsmith.io/public/opencpn/weatherfax-prod/raw/names/weatherfax_pi-1.9.17.0-flatpak-x86_64-18.08-flatpak-arm64-tarball/versions/v1.9.17.0/weatherfax_pi-1.9.17.0-x86_64_flatpak-18.08.tar.gz which fails (404). 

This link originates from metadata/weatherfax_pi-1.9.17.0-flatpak-x86_64-18.08-flatpak-arm64.xml, last commit  Wed Jun 2 16:04:01 2021 -0400. Just an example of a recent commit with broken link(s)

**Comment by rgleason** [comment]
Thanks Alec. I am sure that Jon and I can get these fixed. May take some days however.

**Comment by jongough** [comment]
The plugin xml validation only validates that the xml is syntactically correct not that the referenced tar files actually exist. The merge action makes sure that the catalog is updated with the xml files that are in the pull request if they are syntactically correct.

If file validation of the tar files in the cloudsmith repositories is required then this is a new requirement that someone can add to the action.

**Comment by jongough** [comment]
Master catalog has been updated with latest two builds.

**Comment by leamas** [comment]
Or, we can just start using the existing pre-commit hook. Such a hook is the usual way to check git stuff before it's committed. The existing hook lives in plugins/pre-commit. There are short usage notes in top of file.

This hook tests that the url is accessible. However, it does *not* check ckecksums. We need to script also this and add this script to the hook. Not likely to happen anytime soon, I guess.

**Comment by rgleason** [comment]
https://github.com/OpenCPN/plugins/blob/master/README.md#git-pre-commit-hook

Doesn't running check.bat or runcheck.bat  in Windows mke the same checks?

**Comment by jongough** [comment]
To have a chance to work each time the XML file is updated all links to all plugins would need to be checked/ This is heavy handed and would slow the pull/merge process. Sounds good initially, but may only be practical to think about implementing for the prod repositories.

**Comment by leamas** [comment]
The pre-commit check runs (perhaps, havn't checked) similar checks as other scripts like for example runcheck.bat. But, the checks are done automatically when doing `git commit`. And they are only run on the commit i. e., the changes;  the existing parts of the catalog are not checked. This makes it practical (I agree that checking the complete catalog is just too much).

**Comment by leamas** [comment]
OTOH, the pre-commit script is plain broken (bit rot?; #385).  I filed a PR for that (above). 

It might take some time before Dave merges the PR, he sort of busy. In the meantime, just use use this script which should be named `.git/hooks/pre-commit`. On linux, don't forget to make it executable  (`chmod 755 .git/hooks/pre-commit`)

```
#!/usr/bin/env bash
#
# Pre-commit hook: validate ocpn-plugins.xml and check whitespace errors.
#   - Requires xmllint available on $PATH.
#   - Copy to .git/hooks to activate.
#   - Use --no-verify to override.

topdir=$(git rev-parse --show-toplevel)

for f in $(git diff --cached --name-only --diff-filter=ACM); do
    if [[ $f != *.xml ]]; then continue; fi
    xmllint --schema $topdir/ocpn-plugin.xsd  $f --noout || exit 1
    python $topdir/tools/check-metadata-urls $f || exit 1
done

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached HEAD --
```

**Comment by leamas** [comment]
OK, Dave merged the PR. This means that the only thing necessary to activate the pre-commit hook is to do `cp pre-commit .git/hooks` , or corresponding command on windows. After that, the hook is active and checks all changes before that they are committed.

If the test for some reason gives false negatives, one can use the `--no-verify`option to `git commit`to disable the hook.

Note the the final decision to use the hook or not is made by the developer. There is no way to add a hook to git repo which is applied by default for all users -- user must make an active step to activare the hook.

**Comment by rgleason** [comment]
This is interesting  adding plugins
https://pre-commit.com/#plugins
Look at https://pre-commit.com/#usage
which checks for issues like fix trailing white space  and fix end of files

cp in linux is copy,  would windows would be

`copy pre-commit .git/hooks`

**Comment by rgleason** [comment]
See https://github.com/OpenCPN/plugins/pull/387

**Comment by rgleason** [comment]
The only PIM plugins with metadata errors now are 
shipdriver and plots.

I will have a new version for plots shortly.
So it think this problem is largely resolved.

**Comment by leamas** [comment]
This bug is about the process, not about the actual problems -- those are handled in https://github.com/OpenCPN/OpenCPN/issues/2315.

The issue about the process is that it is even possible to commit changes which contains broken URL:s and wrong checksums. A working process would not allow this, and thus make issues like those reported inhttps://github.com/OpenCPN/OpenCPN/issues/2315 more or less impossible. Important for the future.

The git pre-commit hook is a starter. Are you using it?

**Comment by leamas** [comment]
> The only PIM plugins with metadata errors now are shipdriver and plots.

If there is broken metadata in shipdriver, please file bug(s) against it.

**Comment by rgleason** [comment]
done

**Comment by leamas** [comment]
Back to the original issue here: although the action script validates the catalog against the xsd it does not check urls or checksums.

As @jongough says, it's not really practical to add such checks to the action  script since it works on the complete catalog, and checking urls (not to mention checksums) will take a too long time to be practical.

OTOH, we (now) have a git pre-commit hook which *does* check urls. A first step might be that those who maintains a larger set of plugins uses this hook so we get some feedback on the hook.  The hook only validates the changes, so it's much less to check i. e., it's reasonably fast.

Perhaps someone has a better idea than using thhe pre-commit hook to validate the catalog data?

@Rasbats  @rgleason : thoughts?

**Comment by Rasbats** [comment]
Ok. Will try using the pre-commit hook when making a new commit. My knowledge is too limited to be able to suggest anything else.

**Comment by rgleason** [comment]
I believe the precomit hook requires me to install yet another program and I have long ago forgotten which one Jon told me to install or the steps to implement.  I will admit that the check..bat  which uses validate.sh  takes a long time.

**Comment by rgleason** [comment]
On windooooze
```
$ cd plugins

Rick@Dart MINGW64 ~/documents/github/plugins (master)
$ copy pre-commit .git/hooks
bash: copy: command not found

Rick@Dart MINGW64 ~/documents/github/plugins (master)
$ cpy pre-commit .git/hooks
bash: cpy: command not found

Rick@Dart MINGW64 ~/documents/github/plugins (master)
$
```

**Comment by leamas** [comment]
you need xmllint besides python, as documented in https://github.com/OpenCPN/plugins/README.md

**Comment by rgleason** [comment]
Found xmlint on the chocolatey website.  After upgrade of choclatey, I downloaded and installed xmllint.
Then tried to copy it from bash first  -- no dice.
then powershell tried it


```
PS C:\Users\Rick\documents\github\plugins>
PS C:\Users\Rick\documents\github\plugins> Rick@Dart MINGW64 ~/documents/github/plugins (master)
master : The term 'master' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:47
+ Rick@Dart MINGW64 ~/documents/github/plugins (master)
+                                               ~~~~~~
    + CategoryInfo          : ObjectNotFound: (master:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Rick\documents\github\plugins> $ cpy pre-commit .git/hooks
$ : The term '$' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ $ cpy pre-commit .git/hooks
+ ~
    + CategoryInfo          : ObjectNotFound: ($:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Rick\documents\github\plugins> bash: cpy: command not found
bash: : The term 'bash:' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ bash: cpy: command not found
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (bash::String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Rick\documents\github\plugins>
PS C:\Users\Rick\documents\github\plugins> Rick@Dart MINGW64 ~/documents/github/plugins (master)
master : The term 'master' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:47
+ Rick@Dart MINGW64 ~/documents/github/plugins (master)
+                                               ~~~~~~
    + CategoryInfo          : ObjectNotFound: (master:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by rgleason** [comment]
xmllint seems to be working, but the script hiccups on renamed items.

```

Rick@Dart MINGW64 ~/documents/github/plugins (master)
$ git commit -am "plots 2.2.6.0 + android"
metadata/plots_pi-2.2.6.0-flatpak-aarch64-20.08-flatpak-arm64.xml validates
..
2 urls checked, 0 errors
metadata/plots_pi-2.2.6.0-flatpak-x86_64-20.08-flatpak.xml validates
..
2 urls checked, 0 errors
metadata/plots_pi-2.2.6.0-raspbian-armhf-9.13.xml validates
..
2 urls checked, 0 errors
[master 31a4a0a] plots 2.2.6.0 + android
 16 files changed, 133 insertions(+), 55 deletions(-)
 delete mode 100644 metadata/plots_pi-2.2.4.0-ubuntu-x86_64-14.04-trusty.xml
 rename metadata/{plots_pi-2.2.4.0-ubuntu-arm64-18.04-bionic-armh64.xml => plots_pi-2.2.6.0-android-arm64-16-android-arm64.xml} (63%)
 rename metadata/{plots_pi-2.2.4.0-raspbian-armhf-9.4-stretch-armhf.xml => plots_pi-2.2.6.0-android-armhf-16-android-armhf.xml} (63%)
 rename metadata/{plots_pi-2.2.4.0-darwin-x86_64-10.13.6-macos.xml => plots_pi-2.2.6.0-darwin-x86_64-10.14.4-macos.xml} (66%)
 rename metadata/{plots_pi-2.2.4.0-debian-x86_64-10-buster.xml => plots_pi-2.2.6.0-debian-x86_64-10-buster.xml} (71%)
 create mode 100644 metadata/plots_pi-2.2.6.0-flatpak-aarch64-20.08-flatpak-arm64.xml
 rename metadata/{plots_pi-2.2.4.0-flatpak-x86_64-18.08-flatpak.xml => plots_pi-2.2.6.0-flatpak-x86_64-18.08-flatpak.xml} (71%)
 create mode 100644 metadata/plots_pi-2.2.6.0-flatpak-x86_64-20.08-flatpak.xml
 rename metadata/{plots_pi-2.2.4.0-mingw-x86_64-10-mingw.xml => plots_pi-2.2.6.0-mingw-x86_64-10-mingw.xml} (68%)
 rename metadata/{plots_pi-2.2.4.0-msvc-x86_64-10.0.14393-MSVC.xml => plots_pi-2.2.6.0-msvc-x86_64-10.0.14393-MSVC.xml} (73%)
 rename metadata/{plots_pi-2.2.4.0-raspbian-armhf-10-buster-armhf.xml => plots_pi-2.2.6.0-raspbian-armhf-10.xml} (64%)
 create mode 100644 metadata/plots_pi-2.2.6.0-raspbian-armhf-9.13.xml
 rename metadata/{plots_pi-2.2.4.0-ubuntu-x86_64-16.04-xenial.xml => plots_pi-2.2.6.0-ubuntu-x86_64-16.04-xenial.xml} (71%)
 rename metadata/{plots_pi-2.2.4.0-ubuntu-x86_64-18.04-bionic-gtk3.xml => plots_pi-2.2.6.0-ubuntu-x86_64-18.04-bionic-gtk3.xml} (70%)
 rename metadata/{plots_pi-2.2.4.0-ubuntu-x86_64-18.04-bionic.xml => plots_pi-2.2.6.0-ubuntu-x86_64-18.04-bionic.xml} (71%)
 rename metadata/{plots_pi-2.2.4.0-ubuntu-x86_64-20.04-focal-gtk3.xml => plots_pi-2.2.6.0-ubuntu-x86_64-20.04-focal-gtk3.xml} (70%)

Rick@Dart MINGW64 ~/documents/github/plugins (master)
```

**Comment by rgleason** [comment]
Used  --no-verify  parameter to commit it.

**Comment by leamas** [comment]
To me, it looks like the first  commit, the one that you showing the console output from, actually was successful. However, it did not verify the renamed metadata files. This is a bug, which likely is fixed by this untested  patch:

```
iff --git a/pre-commit b/pre-commit
index fb0e726..8e601b0 100755
--- a/pre-commit
+++ b/pre-commit
@@ -7,7 +7,7 @@
 
 topdir=$(git rev-parse --show-toplevel)
 
-for f in $(git diff --cached --name-only --diff-filter=ACM); do
+for f in $(git diff --cached --name-only --diff-filter=ACMR); do
     if [[ $f != *.xml ]]; then continue; fi
     xmllint --schema $topdir/ocpn-plugin.xsd  $f --noout || exit 1
     python $topdir/tools/check-metadata-urls $f || exit 1
```

Note that the patch is about the pre-commit file in the repo. One needs to copy it to `.git/hooks/pre-commit` before it is activated.

I will file an issue and a PR against the plugins project later. Still sailing, lack of bandwidth and time (but a loyt of sun, 22 hours a day)

**Comment by rgleason** [comment]
Yes, have done this, but it looked the same, but have an idea.  First commit the removal metadata then add new ones and commit to avoid the renaming issue.  Hope the sailing is good.

**Comment by leamas** [comment]
A day off in the middle of nowhere... I'll try to replicate your problem to find a proper solution, might take some time

**Comment by Rasbats** [comment]
Alec ... This one affects a number of plugins which use the ShipDriver template:
[https://github.com/Rasbats/shipdriver_pi/issues/180](https://github.com/Rasbats/shipdriver_pi/issues/180)
As you will see, I tried a number of solutions, without success.

**Comment by leamas** [comment]
@rgleason: commtting   I get the following when committing https://github.com/rgleason/plugins/commit/02743ba5645464be23e5421aa21b26515e18778a.

That is, all urls are checked, also the renamed. This is done using the patch  described  [above](https://github.com/OpenCPN/plugins/issues/383#issuecomment-872103361)


```
git commit -am test
metadata/weather_routing_pi-1.13.28.1-darwin-x86_64-10.14.4-macos.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-debian-x86_64-10-buster.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-flatpak-aarch64-20.08-flatpak-arm64.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-flatpak-x86_64-18.08-flatpak.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-flatpak-x86_64-20.08-flatpak.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-mingw-x86_64-10-mingw.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-msvc-x86_64-10.0.14393-MSVC.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-raspbian-armhf-10.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-raspbian-armhf-9.13.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-ubuntu-x86_64-16.04-xenial.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-ubuntu-x86_64-18.04-bionic-gtk3.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-ubuntu-x86_64-18.04-bionic.xml validates
..
2 urls checked, 0 errors
metadata/weather_routing_pi-1.13.28.1-ubuntu-x86_64-20.04-focal-gtk3.xml validates
..
2 urls checked, 0 errors
[test 1a7d0a9] test
 14 files changed, 69 insertions(+), 43 deletions(-)
 rename metadata/{weather_routing_pi-1.13.25.0-darwin-x86_64-10.14.4-macos.xml => weather_routing_pi-1.13.28.1-darwin-x86_64-10.14.4-macos.xml} (82%)
 rename metadata/{weather_routing_pi-1.13.25.0-debian-x86_64-10-buster.xml => weather_routing_pi-1.13.28.1-debian-x86_64-10-buster.xml} (82%)
 rename metadata/{weather_routing_pi-1.13.25.0-flatpak-aarch64-20.08-flatpak-arm64.xml => weather_routing_pi-1.13.28.1-flatpak-aarch64-20.08-flatpak-arm64.xml} (82%)
 rename metadata/{weather_routing_pi-1.13.25.0-flatpak-aarch64-18.08-flatpak.xml => weather_routing_pi-1.13.28.1-flatpak-x86_64-18.08-flatpak.xml} (73%)
 rename metadata/{weather_routing_pi-1.13.25.0-flatpak-aarch64-20.08-flatpak.xml => weather_routing_pi-1.13.28.1-flatpak-x86_64-20.08-flatpak.xml} (73%)
 rename metadata/{weather_routing_pi-1.13.25.0-mingw-x86_64-10-mingw.xml => weather_routing_pi-1.13.28.1-mingw-x86_64-10-mingw.xml} (82%)
 create mode 100644 metadata/weather_routing_pi-1.13.28.1-msvc-x86_64-10.0.14393-MSVC.xml
 rename metadata/{weather_routing_pi-1.13.25.0-raspbian-armhf-10.xml => weather_routing_pi-1.13.28.1-raspbian-armhf-10.xml} (75%)
 rename metadata/{weather_routing_pi-1.13.25.0-raspbian-armhf-9.13.xml => weather_routing_pi-1.13.28.1-raspbian-armhf-9.13.xml} (76%)
 rename metadata/{weather_routing_pi-1.13.25.0-ubuntu-x86_64-16.04-xenial.xml => weather_routing_pi-1.13.28.1-ubuntu-x86_64-16.04-xenial.xml} (82%)
 rename metadata/{weather_routing_pi-1.13.25.0-ubuntu-x86_64-18.04-bionic-gtk3.xml => weather_routing_pi-1.13.28.1-ubuntu-x86_64-18.04-bionic-gtk3.xml} (82%)
 rename metadata/{weather_routing_pi-1.13.25.0-ubuntu-x86_64-18.04-bionic.xml => weather_routing_pi-1.13.28.1-ubuntu-x86_64-18.04-bionic.xml} (82%)
 rename metadata/{weather_routing_pi-1.13.25.0-ubuntu-x86_64-20.04-focal-gtk3.xml => weather_routing_pi-1.13.28.1-ubuntu-x86_64-20.04-focal-gtk3.xml} (82%)
``

**Comment by rgleason** [comment]
Alec,  thanks, will try it again. Found that if I commit the new plugin, then make a commit to remove the old, it works fine too..  Enjoy the sailing!

**Comment by leamas** [comment]
hm.... I think we missed the obvious solution to run the checks as a ci job.  I filed #425, which is a starter.

**Comment by rgleason** [comment]
Thanks!

**Comment by leamas** [comment]
However, this is *not* a reason to not use the pre-commit hook. You don't want to wait for the ci job, it's much better to get the results directly when committing.

**Comment by rgleason** [comment]
OK

**Comment by leamas** [comment]
After merging #432, the checks when making a pull request are enhanced. In particular, tarball url availability and checksums are checked besides the xsd schema validation. This should basically mean that PRs are sound when merged.

One remaining problem is tarball urls which were ok when merged but brakes later if a tarball disappears from cloudsmith. To handle this situation we need to run a check regularly (nightly?) on all plugins. I'm on it, but not prio 1 right now.

**Comment by leamas** [comment]
We now have
  - A working pre-commit hook which checks committed metadata including url availability and, if applicable, checksums.
  - An updated github actions workflow which makes the same checks
  - An nightly job which checks metadata, to pick up cases where tarballs are removed from cloudsmith.

To me, this seems like a reasonably robust scheme to avoid broken metadata, in the master branch. Closing.

**Comment by Rasbats** [comment]
I am getting an email with the results of the nightly check. How to prevent this?
Last check failed:

```
metadata/oeSENC-4.2-plugin-msvc-10.0.14393.xml: oeSENC-4.2.20.0_msvc-10.0.14393-win32.tar.gz
        metadata checksum: 'd238b6af76af5e9402f33f51f1d751dccceb3ef3c5f04a4fce91ee34aa831130'
        computed checksum: '75f20c373613ff8934cbc1b26deb40a37cb08c9460b5279b44b6513d11271a55'
```

**Comment by leamas** [comment]
You can disable the workflow in the Github UI | Settings | Actions

**Comment by Rasbats** [comment]
Thanks, done.

**Comment by bdbcat** [comment]
Mike...
When did you get the last such message?
I corrected the problem indicated, I think, with oeSENC.  So I have not gotten an error report in a couple of days, since the fix.

**Comment by Rasbats** [comment]
>When did you get the last such message?

This morning.

**Comment by bdbcat** [comment]
Well, that is strange.
I did not get a message, and the check scripts ran successfully 8 hours ago.
https://github.com/OpenCPN/plugins/runs/3358024784?check_suite_focus=true
Glitch in github?

**Comment by leamas** [comment]
Or just the fact that Mike's opencpn/plugins is not fully synchronized with yours? Each workflow runs in a fork, only your runs in the "real" master.

**Comment by Rasbats** [comment]
>Or just the fact that Mike's opencpn/plugins is not fully synchronized with yours?

Yes ... I had not fetched upstream since editing shipdriver xml metadata. Now ignoring actions from plugins.

**Comment by bdbcat** [comment]
Alec...
Yes, that must be it.  Came to the same conclusion during coffee break....

Just so you know...
My plan is to "nag" the relevant plugin author/packager when such checking errors occur, at least on the officially published master catalog.  So it would not be a bad idea to ensure that the checks run successfully on your personal fork, thus validating you own work before a PR.

**Comment by leamas** [comment]
> My plan is to "nag" the relevant plugin author/packager 

Yes, this was my thinking as well.  And

The new tooling allows that the plugin dev validates the catalog before the PR since it  isn't rebuilt if it's newer than the metadata. So, new proposed workflow for plugin devs:

  1. Add metadata as required
  2. Create ocpn-plugins.xml using the Makefile or so.
  3. Validate the catalog using tools/check-metadata-urls ocpn-plugins.xml
  4. Make the PR (which will be validated and possibly rejected by the merge hook)

We have a lot of checks here, but we should have --  it's important that these things remains stable.  Validating the complete catalog takes a long time, an alternative is to just wait until the nightly job runs.

**Comment by jongough** [comment]
This is now retrograde and convoluted. The developer should only be required to add the new metadata and check it locally works. There should be no need to create an ocpn-plugins.xml file. This should be done in git on an action. The last time this developer created the ocpn-pluginx.xml file very difficult to publish a new version of the plugin because of clashes.

If the process is going to be automated then it should be automatic. There should be less work for the developer to do not more.

**Comment by leamas** [comment]
There are different views on this. Nevertheless, if you don't create a ocpn-plugins.xml it will be created as before. But for those who prefer otherwise (I would) there is now a opportunity to create and test it before making the PR.

**Comment by jongough** [comment]
That then requires that you don't upload it. If the git creates a new version overriding the uploaded one why upload it? Surely the idea is to simplify the process not make it more complex. The simpler it is the less chance of errors. This process increases the chances of errors and frustration.

**Comment by leamas** [comment]
> That then requires that you don't upload it.

No. You can see fort yourself in ci/ga_merge.sh.
