### ISSUE TITLE
Master Catalog different for Win and Linux

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#42]
For some reason the Master Catalog seems to be different with regard to plugins between Windows and Linux, which is odd.

**Comment by bdbcat** [comment]
Different in what way?

**Comment by rgleason** [comment]
The managed plugins listed.

**Comment by bdbcat** [comment]
Master catalog has only (incomplete) squiddio in it.  What do you see?

**Comment by rgleason** [comment]
I've checked again, and squiddio is in master for Windows, but not Ubuntu.  Perhaps that is it.
Squiddio in windows only has a downgrade option, with a nice box icon.

**Comment by bdbcat** [comment]
Rick...
Read the metadata.  You will see that squiddio is only available for Ubntu 16.04.
Squiddio is incomplete.

**Comment by rgleason** [comment]
Sorry, should have thought
