### ISSUE TITLE
ci: Bug(s) and overall need of cleanup.

### ISSUE THREAD

**Issue by leamas** [OpenCPN/plugins#427]
The last commit 30ff67f ci script broke because there was no change in the metadata. As this is the case for any commit affecting tooling, this needs to be fixed. 

Furthermore (my bad) there is now a both a circleci script and github actions (GA). This is needlessly complicated, we need to merge things --easiest would be to just use  GA.

Looking at current GA scripts, they need an overhaul. Here are things like incomplete/wrong help messages, unassigned backticks output, strange quoting and also some needlessly complicated logic.

Digging deeper into the unchanged metadata problem above: It would make sense to allow (not require) pull requests to build the ocpn-plugins.xml file. This would make testing easier. The script could validate that ocpn-plugins.xml matches the current metadata and use it as-is if it's ok (and re-build it otherwise as today). This would open for more workflows without breaking any eggs.

See also #383

**Comment by bdbcat** [comment]
All sounds reasonable.
For sure, having (and maintaining) multiple redundant CI scripts (or GA's) seems like a bad idea. Hard enough to keep one set from bit-rotting away.

**Comment by leamas** [comment]
My current thinking is that we need three scripts:

  - One when merging. Today's script unconditionally rebuilds ocpn-plugins.xml. An update should make sure that it only updates this if required. This would solve  the  error when there is no metadata chnage, and also allow a PR to actually update it (which means that a plugin dev can test the complete ocpn-plugins.xml before submitting the PR)
  - One when making a PR. This should be as a complete check as possible; if it takes some time, so be it. It should only check the files actually changed in the PR, partly for performance reasons, partly because errors in this test should only be about the PR as such.
  - One nightly check (new). We need such a script to pick up URL:s which was OK when entered, but later broke when the tarball was removed from cloudsmith -- this seems to happen from time to time.  This raises questions how to notify who, but this is a too deep rabbit hole right now.
