### ISSUE TITLE
How to build locally?

### ISSUE THREAD

**Issue by transmitterdan** [OpenCPN/plugins#468]
With all the work to build plugins via CI it seems we have broken the ability to build some plugins locally.  In OpenCPN we took care to check if we are building in a CI environment or not so as to allow local builds to continue working.  But it seems now most/all plugins no longer build locally.  For example, the AIS radar plugin no longer builds on my Windows 11 machine.  It complains that it cannot find OpenGL and wxWidgets even though the OpenCPN build easily finds these components.

Do we plan to allow plugins to build locally or will we always need CI to build for us? It seems extra difficult to me to debug plugins without building locally.

**Comment by leamas** [comment]
The local build procedure depends on the template set used, Shipdriver or Testplugin.

Shipdriver plugins are shipped with a generic INSTALL.md file which describes the steps top make a local build.
