### ISSUE TITLE
Build ocpn-plugins.xml

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#47]
Using the format described in OpenCPN/plugins for the python command

```
C:\Users\Rick\Documents\GitHub\plugins>python tools/ocpn-metadata generate --userdir metadata --destfile ocpn-plugins.xml
Traceback (most recent call last):
  File "tools/ocpn-metadata", line 137, in <module>
    main()
  File "tools/ocpn-metadata", line 132, in main
    generate(args.userdir, args.destfile, args.version)
  File "tools/ocpn-metadata", line 90, in generate
    subtree = ET.parse(str(path))
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 14, column 2
```

```
C:\Users\Rick\Documents\GitHub\plugins>python tools/ocpn-metadata generate --userdir metadata --destfile ocpn-plugins.xml
Traceback (most recent call last):
  File "tools/ocpn-metadata", line 137, in <module>
    main()
  File "tools/ocpn-metadata", line 132, in main
    generate(args.userdir, args.destfile, args.version)
  File "tools/ocpn-metadata", line 90, in generate
    subtree = ET.parse(str(path))
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 14, column 2
```
Also adding --force does not work. 

Then tried 

```
C:\Users\Rick\Documents\GitHub\plugins>python tools/check-metadata-urls metadata
Traceback (most recent call last):
  File "tools/check-metadata-urls", line 85, in <module>
    main()
  File "tools/check-metadata-urls", line 78, in main
    tree = ET.parse(path)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 585, in parse
    source = open(source, "rb")
PermissionError: [Errno 13] Permission denied: 'metadata'
```

Then tried to fix the permissions.  This is unusable really.

The older script worked.

**Comment by rgleason** [comment]
This is a big problem for me. I am not going to do this by hand, so I cannot create a new ocpn-plugins.xml

**Comment by rgleason** [comment]
In oesenc_pi  (Bdbcat repos)  and  certainly in squiddio (rgleason repos)

LINE 12  is put out this way
`  <info-url>https://opencpn.org/OpenCPN/plugins/sQuiddio.html </info-url
`	
Missing the final   ">"   is that what would cause all this gibberish?
This is true for all xml files produced.  I have looked at the various files and have been unable to determine where it is wrong. I expect it it the script in the final file.

Also Why can I run the python file and then check it all in one file!!!!
That would be much easier, and it was the way it worked before.

**Comment by rgleason** [comment]
Fixed the errors and it made ocpn-plugins.

Several things need fixing here:
1. Comprehensible output for plugin devs when there is an error in the xmls.
Show xml plugin name and line for the error please.
2. Run this check script on ocpn_plugins instead of each individual plugin, so we can fix it from the combined file?  - some pros and cons to this because the individual files are not fixed.

Tell me where to fix oesenc and squiddio files so this does not occur  (missing ">" in line 12.

**Comment by rgleason** [comment]
I generated it to 

C:\Users\Rick\Documents\GitHub\plugins>python tools/ocpn-metadata generate --userdir metadata
Generated new ocpn-plugins.xml at C:\Users\Rick\AppData\Local\ocpn-plugins.xml

Why not make it land where it should land?

**Comment by rgleason** [comment]
This one works properly:
```
C:\Users\Rick\Documents\GitHub\plugins>python tools/ocpn-metadata generate --userdir metadata --destfile ocpn-plugins.xml
Generated new ocpn-plugins.xml at ocpn-plugins.xml

```

**Comment by bdbcat** [comment]
Rick...
Congratulations on finding _and identifying the root cause_ of a real error.
This is what we do....

Dave

**Comment by rgleason** [comment]
Ready to put up 12 environments .xml for VDR_pi
Getting these errors which mean nothing to me.

```
C:\Users\Rick\Documents\GitHub\plugins>python tools/ocpn-metadata generate --userdir metadata --destfile ocpn-plugins.xml
Traceback (most recent call last):
  File "tools/ocpn-metadata", line 137, in <module>
    main()
  File "tools/ocpn-metadata", line 132, in main
    generate(args.userdir, args.destfile, args.version)
  File "tools/ocpn-metadata", line 90, in generate
    subtree = ET.parse(str(path))
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 6, column 34

```

Garbage out = No upload.

**Comment by rgleason** [comment]
OK so which on is it supposed to be?

```
<?xml version="1.0" encoding="UTF-8"?>
<opencpn-plugin version="1">

```

OR

```
<?xml version="1.0" ?>
<plugins>
```

Thiss is a bit of a PITA.

**Comment by rgleason** [comment]
From ocpn-plugins.xsd

```
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="plugins">
  <xs:complexType>
```

Also the location of the info-url is incorrect.
This is all due to a bad file for xml format

**Comment by rgleason** [comment]
The file is named  <plugin>-plugin.xml.in   
These same files  in rgleason/squiddio_pi,  rgleason/vdr_pi and  bdbcat/oesenc_pi are WRONG!!!

BAD FILE

**<?xml version="1.0" encoding="UTF-8"?>
<opencpn-plugin version="1">     -----> CORRECT  <plugin version="1"> 
  <name> VDR </name>
  <version> ${PACKAGE_VERSION} </version>
  <release> ${PKG_RELEASE} </release>
  <summary> Voyage Data Recorder & Player </summary>

  <api-version> ${PKG_API_VERSION} </api-version>
  <open-source> no </open-source>
  <author> ${PKG_AUTHOR} </author>
  <source> https://github.com/SethDart/vdr_pi/ </source>
  <info-url>https://opencpn.org/OpenCPN/plugins/vdr.html </info-url>

  <description>
VDR Voyage Data Recorder Use Voyage Data Recorder (VDR) to record and play NMEA files.
Save NMEA stream to a file.  Replay NMEA stream previously saved. Plugin by Seth Dart
  </description>

  <target>${PKG_TARGET}</target>
  <target-version>${PKG_TARGET_VERSION}</target-version>
  <tarball-url> ${TARBALL_URL} </tarball-url>
</opencpn-plugin>       ---------->> CORRECT </plugin>     **

**Comment by rgleason** [comment]
I have changed all xml files to be bracketed by
```
<?xml version="1.0" encoding="UTF-8"?>
<plugin version="1">
</plugin>

```

I also relocated the  <info-url>  line up to where it should be located in a number of xml files, and checked all the files.  They should work now.

However:
C:\Users\Rick\Documents\GitHub\plugins>python tools/ocpn-metadata generate --userdir metadata --destfile ocpn-plugins.xml --force
Traceback (most recent call last):
  File "tools/ocpn-metadata", line 137, in <module>
    main()
  File "tools/ocpn-metadata", line 132, in main
    generate(args.userdir, args.destfile, args.version)
  File "tools/ocpn-metadata", line 90, in generate
    subtree = ET.parse(str(path))
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: mismatched tag: line 24, column 2

This is totally Indeysixriferabble.

**Comment by rgleason** [comment]
There must be something wrong with this file, but I cannot determine what is wrong.
VDR_pi, Weather_Routing_pi and Squiddio_pi show all show as Managed Plugins that can be installed, when you are on the Alpha channel.

![PI-MANAGER](https://user-images.githubusercontent.com/2363959/76898294-d0144480-686b-11ea-879c-f06678077115.png)

[ocpn-plugins.xml.txt](https://github.com/OpenCPN/plugins/files/4345684/ocpn-plugins.xml.txt)

I could use some help figuring this out.

**Comment by rgleason** [comment]
I've determined that the Alpha catalog is not being seen at all. I removed weatherrouting and that does not show as an installable Managed plugin when the Alpha catalog is used.

**Comment by bdbcat** [comment]
Rick...
This change seems right:
```
<?xml version="1.0" encoding="UTF-8"?>
<opencpn-plugin version="1">     -----> CORRECT  <plugin version="1"> 
  <name> VDR </name>
...
```
But this does not:
```
<?xml version="1.0" encoding="UTF-8"?>
<plugin version="1">
</plugin>

I will correct oesenc now, and verify that it works on Beta branch

```

**Comment by bdbcat** [comment]
Rick...
the last line in the error report:
`xml.etree.ElementTree.ParseError: mismatched tag: line 24, column 2`
Have you looked at this line?

**Comment by bdbcat** [comment]
Rick...
oesenc xml.in file corrected.  Python merged of all XMLs proceeds without error.
Thanks for the catch.

**Comment by rgleason** [comment]
DAVE,
I made that [change](https://github.com/OpenCPN/plugins/issues/47#issuecomment-600218362) from  <opencpn-plugin version="1"  to <plugin version="1"
Because it did not work!!

Because I looked carefully at the [ocpn-plugins.xsd](https://github.com/OpenCPN/plugins/issues/47#issuecomment-600197013)

```
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="plugins">
  <xs:complexType>

``` 

So I am really confused because the Beta ocpn-plugins.xml is

```
<?xml version="1.0" ?>
<plugins>
  <version>0.0.0</version>
  <date>2020-03-10 20:31</date>
  <plugin version="1">
    <name> WeatherRouting </name>
```

We've been using just   "plugins" all along and the SCHEMA is  "plugins"

So why doesn't that work and shouldn't that   xsd  file be changed too if there were changes?

**Comment by rgleason** [comment]
Dave, what file does this apply to?

```
the last line in the error report:
xml.etree.ElementTree.ParseError: mismatched tag: line 24, column 2
Have you looked at this line?
```

**Comment by bdbcat** [comment]
Rick...
This is the error problem in at least one of the XML input files.
But I see that you have corrected all, and submitted a good PR to Beta.
So we can close this?

**Comment by rgleason** [comment]
This is the ocpn-plugins.xml  file I just pushed to rg-alpha (meta-url from Alpha)

https://github.com/rgleason/plugins/blob/rg-alpha/ocpn-plugins.xml

So what should I change it to?

**Comment by bdbcat** [comment]
It looks fine.
Does it work?  If not, what, if any, error indication do you see?

**Comment by rgleason** [comment]
Well, I rebooted the machine, and now Opencpn seems to be working better, in particular Beta.
However Alpha does not show the opportunity to install the new version, even when I have uninstalled it under Beta.

![Screenshot (627)](https://user-images.githubusercontent.com/2363959/76915414-a66f1380-6893-11ea-8bf3-1df4aeae3d60.png)

**Comment by bdbcat** [comment]
Rick...
This file:
https://github.com/rgleason/plugins/blob/rg-alpha/ocpn-plugins.xml
still has the ampersand character in it.

**Comment by rgleason** [comment]
Thanks, I believe I fixed it now.  Also updated all the metadata VDR_pi files on Beta and my branch rg-alpha so hopefully this ampersand does not creep back in!  (unless someone has already pulled!)

I hope you will merge soon.

**Comment by rgleason** [comment]
> Rick...
> This is the error problem in at least one of the XML input files.
> But I see that you have corrected all, and submitted a good PR to Beta.
> So we can close this?

So I have to check all 12 files for some error on 

`xml.etree.ElementTree.ParseError: mismatched tag: line 24, column 2`

why can't we get the filename?  Or is this too demanding?

**Comment by rgleason** [comment]
Dave added to the script to print the filenames as they are done! Thank you.
