### ISSUE TITLE
 PIM Download Script not working #205 

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#477]
https://github.com/jongough/testplugin_pi/issues/205

**Comment by bdbcat** [comment]
I do not know who created this script.  I do not use it...
@leamas ??

**Comment by rgleason** [comment]
Actually I think it was Jon to help automate work.  I am going to try your suggestions.

**Comment by leamas** [comment]
> @leamas ??

No. Only Jon has commits in that script, he  seem to be maintaining it. 

BTW: Last change was June 20, so whatever changed it isn't that script

**Comment by rgleason** [comment]
I think my problem is env var for python.  Sorry a bout the noise. Will try in morn.
