### ISSUE TITLE
CommonName Problem:  2 Instances of a plugin in the list

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#48]
I found my recent version of Squiddio had a "CommonName" problem, which is manifested by having 2 separate instances of the plugin in the Plugin List. The problem is one of the squiddio plugins, either the old one or the new one (most likely) is not using the proper "CommonName" so the program creates two separate instances, thinking it is two different plugins.
![Squiddo-Common-Name-Problem](https://user-images.githubusercontent.com/2363959/76692022-22185880-6627-11ea-90ca-bbe761acfa83.png)

Always use the CommonName in the right places in the CMakeLists.txt file.

First find the correct CommonName by searching the squiddio_pi.cpp file for "GetCommonName" you will find a line

```
wxString squiddio_pi::GetCommonName() {
    return _("Squiddio");
}
```

Now in the CMakeLists.txt find the Line

SET(VERBOSE_NAME Squiddio)   #Commonname

and make sure it is the same.

**Comment by rgleason** [comment]
That did not work..  Looks the same and I do not get the new version of the plugin at all.
Which CMakeLists.txt variable does the CommonName go into?

**Comment by bdbcat** [comment]
Rick..
Don't use a CMake variable.  
Edit and fix the file: squiddio-plugin.xml.in

**Comment by rgleason** [comment]
That makes sense to me now. The OpenCPN Plugin Manager can only see the squiddio metadata.xml file, so the  <name> field must match the "Commonname" as found by going to src/squiddio_pi.cpp  and searching for "GetCommonName" function.  Then use exactly the name shown. Capitals matter.

Have changed 
```
<opencpn-plugin version="1">
  <name> Squiddio </name>
  <version> ${PACKAGE_VERSION} </version>
  <release> ${PKG_RELEASE} </release>
  <summary> Repository of sailing destination waypoints and Bouy Reports </summary>

```
In CMakeLists.txt  have set this line back to what it was:

`SET(VERBOSE_NAME squiddio)  
`

This is also where I can fix the darn missing ">" in this line

`  <info-url>https://opencpn.org/OpenCPN/plugins/sQuiddio.html </info-url
`

Which causes grief when joining all the plugins environment  xmls together into ocpn_plugins.xml

Thanks.
