### ISSUE TITLE
dashboard_tactics_pi  Common Name Question

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#484]
@bdbcat 

I believe I had the wrong common name with version 1.6.6.0  what should be done?
I would prefer to stick with the right common name,  "dashboard_tactics_pi"  as Petri had it set up, because he uses a common_name variable throughout the plugin and I think it should be correctly done.

But what artifacts will be left in user's PIM with this situation?
Should they simply clean the cache/metadata of the old version 1.6.6.0 ?

**Comment by bdbcat** [comment]
1.  Remove the offending plugin, using the PIM if possible.
2. Clear the cache.
3. download a fresh catalog.

**Comment by rgleason** [comment]
Thanks, unfortunately, version 1.6.6.0 is in the catalog right now, but when I update, it will disappear.
Then users may need to clear the cache too.
