### ISSUE TITLE
PI Manager:   VERSION (MAJOR, MINOR, PATCH)   missing

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#49]
Can we please have the three version designations?
Currently it is just Major, Minor.

**Comment by bdbcat** [comment]
More context needed.
What/where?

**Comment by rgleason** [comment]
Sorry if I was not clear. In the Plugin List, after the plugin name, all that is provided is Major.Minor

**Comment by bdbcat** [comment]
OK, so this is an issue for OpenCPN, not "plugins".
I'll take a look.
