### ISSUE TITLE
Jailed plugin on RPi Debian Buster

### ISSUE THREAD

**Issue by Hakansv** [OpenCPN/plugins#490]
Dear Linux gurus.
I'm trying to get a plugin granted from Dirk for AIS voyage data to a class A transmitter up and running.
It's working fine on Windows but when I try to use it on Debian it's a mess. The tarball builds fine but it's jailed at runtime.
The plugin is called ais-vd_pi and the last code tried is here: https://github.com/Hakansv/ais-vd_pi/tree/test
See the log extract below. The "undefined symbol: _ZTV8aisvd_pi" is the mystery. There's nothing in the repository named "ZTV8.." so it would be mismatch somewhere. 
Any help to  trace this would be really appreciated. - No hurry!
Thanks/Håkan

home/pi/.local/lib/opencpn/libais-vd_pi.so
19:17:50.228 MESSAGE pluginmanager.cpp:2148 Plugin is compatible by elf library scan: true
19:17:50.228 MESSAGE pluginmanager.cpp:2283 PlugInManager: Loading PlugIn: /home/pi/.local/lib/opencpn/libais-vd_pi.so
19:17:50.233   ERROR dlunix.cpp:162 /home/pi/.local/lib/opencpn/libais-vd_pi.so: undefined symbol: _ZTV8aisvd_pi
19:17:50.233 MESSAGE pluginmanager.cpp:2347    PlugInManager: Cannot load library: /home/pi/.local/lib/opencpn/libais-vd_pi.so 
19:17:50.236 MESSAGE pluginmanager.cpp:2351 Jailing: /home/pi/.local/lib/opencpn/libais-vd_pi.so

**Comment by rgleason** [comment]
Where did you get this code from?  Which repository?

**Comment by bdbcat** [comment]
Are you building on CI, or locally?
Can you post a copy of the build log?  Also, a copy of  libais-vd_pi.so, if possible.

**Comment by Hakansv** [comment]
@rgleason 
For the code please see:  https://github.com/Hakansv/ais-vd_pi/tree/test
I'm so sorry if I've cached things from you. I'm not a thief so I may have make a mistake. Most plugin manager stuff are from shipdriver. But what "metadata" do you refer to? I can't find that.

@bdbcat 
I'm testing locally so far. The plugin manager parts are still kind of foggy.
Cmake log and ..._pi.so attached.
Thanks /Håkan

[CMakeOutput.log](https://github.com/OpenCPN/plugins/files/7509765/CMakeOutput.log)

[libais-vd_pi.so.pdf](https://github.com/OpenCPN/plugins/files/7509761/libais-vd_pi.so.pdf)

**Comment by bdbcat** [comment]
Hakan...
Root problem:  Your class aisvd_ppi is not being fully built, so the vtable is missing.  You need top call the constructor of the base class (opencpn_plugin_116).

in aisvd_pi.cpp,  add this line after line 56, so it looks like this:

```
aisvd_pi::aisvd_pi(void *ppimgr):opencpn_plugin_116(ppimgr)
         :opencpn_plugin_116(ppimgr)

```

**Comment by rgleason** [comment]
Not a problem Hakan, i am just trying to help.

**Comment by Hakansv** [comment]
Dave..
":opencpn_plugin_116(ppimgr)" was already there but on the same row? Move it down yields no difference.

It may be something connected to the default.icon handle. After jailing the plugin manager's ais-vd icon is at least ten times bigger than normal. 
Since other plugins and OCPN runs fine after local build also on the RPi it would be something related to the code in ais-vd_pi that acts different on RPi compared to Windows. I've to investigate more and try.
Thanks

**Comment by Hakansv** [comment]
Rick.
OK, very good! 
"in PIM catalog" I don't understand. I have to read more Plugin Manager background I suppose.

**Comment by rgleason** [comment]
Haken, we are building tarballs with associated metadata.xml files which are included in the github.com/opencpn/plugins/metadata directory (bdbcat accepts PR).  This catalog of metadata is what the program Opencpn pulls down when the user clicks "update catalog"   The builds for up to 12-15 OS and configurations is generally included for each plugin (MacOS, Win, RPI, Ubuntu  (about 3-4 versions) and Flatpak (3 versions) and also android for some plugins.

PIM is my shorthand for the new PI Manager   (as opposed to the previous PI Installer)  found by going to Options > Plugins

**Comment by Hakansv** [comment]
Strange.. My Linux error described above gives the same extended icon "default_pi.xpm" as described on today's forum post: https://www.cruisersforum.com/forums/f134/opencpn-beta-5-5-1109-rc1-released-257723.html#post3518327
For me not seen on Win though.

![bild](https://user-images.githubusercontent.com/7202854/141339229-39509504-2734-4447-a8ff-c9335358c522.png)

**Comment by Hakansv** [comment]
The "extended" plugin default icon is no longer there. Now it's as normal probably due to the OCPN code update?

I've tried to learn using Code:Blocks and debug my issue. No luck so far.
I think it's the function "pic->m_library.Load(plugin_file)" in pluginmanager.cpp: 2293 that fails to load ais-vd_pi. But it's hard for me to follow into wxWidgets and: "dlunix.cpp:162 /home/pi/.local/lib/opencpn/libais-vd_pi.so: undefined symbol: _ZTV8aisvd_pi"  to see when the symbol gets corrupt, or what's happening. Since other plugins are working there would be something in my code causing this.
As said it's working very fine in Win but then is of course "dlunix.cpp" not involved.
The code is somewhat changed. Not less using all from Shipdriver as a template so it wouldn't be related to the build process that runs wo errors?  
code: https://github.com/Hakansv/ais-vd_pi/tree/test

**Comment by Hakansv** [comment]
Problem solved!
If more novices like me are here the problem was an "old" declaration not needed. Windows gently accepted but Linux not.
Håkan

```
class aisvd_pi : public opencpn_plugin_116 
{
  -DECLARE_EVENT_TABLE()
  public:
    aisvd_pi(void *ppimgr);
	  ~aisvd_pi();
```

**Comment by rgleason** [comment]
Hakan, have has the same problem on about 4 plugins,  at Jon's suggestion, I looked in the ini file because I knew the toolbar icon was not loading, and I found that the %localappdata"/opencpn/plugins/Polar_pi   data directory was capitalized. I tried changing it to lower case and the images were found!  Then went back to the code to make the right changes.

**Comment by Hakansv** [comment]
Yes, Windows is simple and forgiving!?
-- No, I don't want a debate! I'm just joking in a communion where I'm the underdog? :-)

**Comment by rgleason** [comment]
Hakan.    I was unclear when I wrote "This was working on Windows...."  very sorry.
The plugin failed forever on Windows no matter what I did., 
I looked at the error codes in the ini and guessed that if I changed the data directory  "Polar_pi" to "polar_pi" it would work and it did work

Windows was also so forgiving, it just keeps the "Polar_pi" folder as it was with a capital "P" even though the installation config had a lower case "p" designated.  So after having removed all vestiges of Polar_pi from the computer, it then worked when I reinstalled! 

Very important to remove PI vestiges (on Windows anyway) after making the necessary changes.

**Comment by jongough** [comment]
I think you mean you looked for error codes in the log file as the ini file will not have any of these as it is the configuration file.

**Comment by rgleason** [comment]
Yes

**Comment by bdbcat** [comment]
Hakan...
If I understand correctly:
You "declared" an event table, but did not include the actual table itself in the .cpp code.
Correct?

**Comment by Hakansv** [comment]
Dave..
Yes, something like that. I'm not sure when the "declaration" appeared. This plugin has a journey before I inherited it. It's probably recycled from another. I could as well have copied something wo a clear view.
All this pushed me to learn more about event handling. Reading [this](https://docs.wxwidgets.org/3.0/overview_events.html) gave a lot.
Thanks
Håkan
