### ISSUE TITLE
Missing: Plugin catalogue GUI

### ISSUE THREAD

**Issue by leamas** [OpenCPN/plugins#5]
Technically this is about the https://github.com/OpenCPN/OpenCPN/pull/1457 PR. However, there is no natural way to file issues against a PR so doing it here.

Exploring the ideas in #2: Users can select to fetch the catalogue from different channels, a GUI could be like

![catalog-mgr-1](https://user-images.githubusercontent.com/405541/68601422-9342d600-04a4-11ea-8589-85d20c274c37.png)

The default version is the one in the data directory -- it was placed there during installation. A possible override lives in the user location, that's the active version possibly updated by user. The latest available + available channels is found by probing the server (likely github).

Adding a way for plugin devs to use  a custom url could be like: 

![catalog-mgr-2](https://user-images.githubusercontent.com/405541/68601477-ae154a80-04a4-11ea-9a7c-42098fbf2c76.png)

**Comment by leamas** [comment]
Input is welcome. The dialogs shown here are just empty mock ups,  there is not invested in them.

**Comment by bdbcat** [comment]
Alec...
Nice.
This level of detail should probably require an "Advanced'..." button to access.  There maybe should be a simple button (one level up) that says "Check available plugins using latest plugin catalog", or something a little less wordy...

**Comment by leamas** [comment]
Dave,
Thanks for feedback!

>  There maybe should be a simple button [...]

My idea is that there is a control when ocpn starts. It must be in a separate thread, to not delay the overall startup. Likewise, we need to check the "catalog server" if changing channel/branch or URL.

Having such a button was also my initial idea, but I rejected it when trying to create a reasonable UI. However, it was a quick decision, and I'm certainly not sure. 

A modal progress dialog when opening this page where the check is done?
   
> This level of detail should probably require an "Advanced'..

It's already hidden under a *Settings* button in the plugin list. Just call it *Advanced Settings* and be done with that?

**Comment by leamas** [comment]
> A modal progress dialog when opening this page where the check is done?

Thinking about it, why not? That is, showing something like below when accessing the Plugin Catalogue Manager above. Clicking OK takes us to said manager.

![load-catalogue](https://user-images.githubusercontent.com/405541/68624074-4ed02e00-04d6-11ea-9574-725eb3604ce3.png)

This way we can avoid implicit and almost always useless tests at startup, without forcing user to push a button with a label which almost for sure will be confusing.

**Comment by bdbcat** [comment]
Alec...
I think, again, too complex for basic UI.

1.  We should not automatically go to network on every startup in order to query the server.  We do not own the user's bandwidth.  User should choose to update the plugin configuration, in their own time.

2.  With all respect, our average user is not skilled in logic driven decision trees.  They are sailors, running Windows, and pushing buttons.  Our UI designs must be simple to comprehend at high level, with any additional complexity available by drill-down.

3.  Recommend two buttons on the plugin page:
a.  "Update plugin catalog" This fetches the current general catalog, and updates the UI.
b. "Advanced..."

**Comment by leamas** [comment]
> We should not automatically go to network on every startup 

Right, I have already come to the same conclusion (see above)

> Recommend two buttons on the plugin page [...]

This is (obviously) the right approach, agreed.  Good to have this discussion now and not later...

Whichever button pressed, it will show the progress dialog in https://github.com/OpenCPN/plugins/issues/5#issuecomment-552636059 and then either be done or open the advanced dialog.

Seems like the pieces start to fall in place.

**Comment by rgleason** [comment]
The advanced button looks very interesting, however I think 90% of users will just hit the "Update" button, which essentially is like the Chart Download  "Update Catalogue" button.

I am interested in what happens in the background after the button is hit.

**Comment by leamas** [comment]
I'm on this, but it's some actual coding to do. Occasionally, my employer implies I have to work, and I'm doing some work in my apartment. 

In summary, it is gonna take some time. Currently, my best guess is next weekend. Stay tuned...

**Comment by leamas** [comment]
> which essentially is like the Chart Download "Update Catalogue" button.

BTW: English is (obviously) not my native language. That said, is British spelling ("catalogue") or American ("catalog") the default?

**Comment by rgleason** [comment]
Sorry Alec, for the confusion, that is me. I believe Pavel used Catalog in the chart downloader. We understand, you are doing a great service for all users. Thank you!

**Comment by leamas** [comment]
Never mind, just a clarification: Does this mean that American English is the default spelling?

**Comment by rgleason** [comment]
Yes, I guess so, since Pavel has used "catalogs" in Chart Downloader (just checked), but I am sure we can understand and read British too. :-)

**Comment by leamas** [comment]
This is now available in https://github.com/OpenCPN/OpenCPN/pull/1457. There are rough edges, but is supposed to be functionally complete. Please feel free to file bugs against the UI here.

Closing
