### ISSUE TITLE
Test Report: PI operational review for most PIM

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#501]
Tested operation of all plugins in the Plugin Manger.
Objective: To make sure the PI is well behaved and does not crash OpenCPN

### Method:
1. From PIM, Update catalog and install all plugins. 
2. From PIM,  Enable plugin after updates and installation. 
3. Preferences opened and something selected or changed,
4. Preferences closed
5. From the toolbar, click on icon to open menu.  (These actions are generally standard and expected by the user)
6. From the toolbar,click on icon to close menu. (These actions are generally standard and expected by the user)
7. Ability to close the menu from the upper right X  (Did not check this)
8. From PIM, Disable plugin.

### Response
Note: which Plugins crash OpenCPN and which action caused the crash.
Remove the plugin from the catalog if possible or notify the author.

### Report
1. Climatology  - Disable - Crashes Opencpn - Removed from Catalog
2. Polar - Disable - Crashes Opencpn - Removed from Catalog 
3. LogbookKonni - Disable - Crashes Opencpn  - Removed from Catalog
3. Findit - In PIM clicking on Icon does not close the menu. (not removed)
4. Squiddio - In PIM clicking on icon does not close the preferences dialog (not removed)

### Slightly different operation
5. Radar - works differently because of the persistent screen popup menu.
6. NmeaConverter - does not have a toolbar Icon and is programmed from Preferences dialog.
6. Windvane  - works as expected after a question is answered.
7. Testplugin  - works as expected after a question is answered.
8. Autopilot_Route - no menu or toolbar icon, it uses Preferences.
9. Chartplotter - no toolbar icon, integrated with Opencpn menus.
10. VDR - play or record opens a browser to select or create a file. The close action is done at the upper right X

**Comment by bdbcat** [comment]
Climatology...More detail on crash, please?
LogbookKonni...More detail on crash, please.

Both of these plugins load on linux, although with some icon errors.  No crashes immediately evident.

**Comment by rgleason** [comment]
Dave, thanks for trying these.Both plugins in windows, immediately crash OpenCPN,  when they are open in options> plugins and the Enable checkbox is "unchecked". As some as the action to uncheck is taken, Opencpn fails and crashes and the entire application disappears. Same is happening with polar_pi.I did do some work on icons too but was careful, following mike's lead and help using shipdriver code. I think these icon errors should also be fixed though. Maybe that is what causes the crash in windowsWe are in Mystic and having dinner tomorrow with two other couples. No TG with family this year. I hope you and Kathi have a good TG. It must be beautiful there this time of year. I love all the reds yellow and browns right now.  No ice on the river yet, but it is coming. A good time for boat projects.BestRickOn Nov 24, 2021 10:48 AM, bdbcat ***@***.***> wrote:
Climatology...More detail on crash, please?
LogbookKonni...More detail on crash, please.
Both of these plugins load on linux, although with some icon errors.  No crashes immediately evident.

**Comment by bdbcat** [comment]
Rick...
Logbook corrected, PR in your repo.  Good Luck

**Comment by rgleason** [comment]
Thanks Dave. Happy  Thanksgiving. to you and Kathi!

**Comment by bdbcat** [comment]
Likewise to you and yours.
Dave

**Comment by bdbcat** [comment]
Rick,
Climatology corrected, PR in your repo.
Good Luck

**Comment by rgleason** [comment]
Thanks Dave.  Closing
