### ISSUE TITLE
Plugin ais-vd. macOS test

### ISSUE THREAD

**Issue by Hakansv** [OpenCPN/plugins#529]
Not an issue (yet?) but I'd like some help to test a plugin candidate on macOS. 
The plugin is meant to be a help for those having a AIS class A transponder to edit the static voyage data. 
There may be a macOS issue with the date and time selection boxes if I understand it correct. Now I haven't yet made any actions but want to first clear out if I've a problem.
The Tarball here would be useful for a PIM import: [ais-vd_pi macOS](https://dl.cloudsmith.io/public/opencpn/ais-vd-alpha/raw/names/ais-vd-1.1-darwin-wx315-10.13.6-tarball/versions/1.1.30+100.0c1785e/ais-vd-1.1.30+100.0c1785e_darwin-wx315-10.13.6-x86_64.tar.gz)
When installed the plugins would be present in Options->Ships->AIS static
This is how it shows up in Windows and RPi. 
Thanks /Håkan

![bild](https://user-images.githubusercontent.com/7202854/145450047-437af542-7890-4a3a-aefe-2e9b6372a477.png)

**Comment by bcn2** [comment]
Date format mish-mash confirmed on a M1 macMini, macOS 12.0.
![Captura de pantalla 2021-12-09 a las 20 15 29](https://user-images.githubusercontent.com/19633222/145461534-7e8e7450-43f7-4cf1-bb7f-21dcea7fab6c.png)
1

**Comment by Hakansv** [comment]
OK. Is it possible to edit the time and date in these odd boxes?
I may also agree about the "strange" date format that would be SI formed if your country is set to Spain?
If you click "Send to AIS" is the $ECVSD format correct? (The send button text info will change)

But my intention for the time box is "00" seconds and that's not understood by macOS. So I may have to tweak a little.
May I come back asking you being a test pilot?
Thanks for the test.
Håkan

**Comment by bcn2** [comment]
ETA time and date do move
![Captura de pantalla 2021-12-09 a las 21 40 21](https://user-images.githubusercontent.com/19633222/145472779-5472b742-009e-442c-aaf5-acad038755d4.png)

**Comment by Hakansv** [comment]
Ok thanks.
The VSD is though correct formatted.
So if it's possible to edit the date and time in a convenient way it may be good enough?

**Comment by bcn2** [comment]
ETA Date is in a wrong local format.
Editing is fine - well, sufficient: click on (sub)entry and use the dial. Not the most convenient, but does work. As the entry is nothing you will touch every five minutes....

**Comment by Hakansv** [comment]
What happens if you change to Spanish. On Win/Linux there's a change than

**Comment by bcn2** [comment]
December, 11th
I did just look at DD/MM/YYYY in contrast to the US format ot MM/DD/YYYY.
"-" or better "." as delimiters would be more correct of course.

**Comment by Hakansv** [comment]
Reading wxWidgets datepickercntrl it should format according to the local PC's settings. Could you verify? Compare my picture.
My regional settings for "short date" is "2021-11-09".  What about yours?

**Comment by bcn2** [comment]
After sleeping well and looking again into the date settings, everything is just ok.
The local setting on the macOS of the system renders dates as shown - DD/MM/YYYY.
So nothing to complain.

**Comment by Hakansv** [comment]
Very good. Thanks for your help.
