### ISSUE TITLE
Updates and Maintenance of Plugins:  Poorly thought out, too many actions

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#53]
There has been little to no thought or consideration of the multiple duplicate actions required to "publish" a plugin. It seems like every effort has been to make it more work for the developer to publish to a catalog.

Instead of a single well formed XML file containing the multiple environmental xml for a given plugin, we are asked to check each env xml in a ridiculous multi stage procedure which occurs at every step of the process from Cloudsmith to finally pushing to plugins.

These steps are totally unnecessary. The developer should be given a single well formed ocpn-plugins.xml file uploaded to cloudsmith, that can be downloaded and then uploaded to plugins.

**Comment by bdbcat** [comment]
Rick....
You somehow seem to be doing this the hard way.
Once the CI build files for a particular plugin are complete and correct, the process is pretty smooth.
In particular, there should be no need to edit any of the generated metadata files.  If you find that to be not true, then there is something missing in your process.

**Comment by rgleason** [comment]
I am not doing anything the 'hard' way, or at least not intentionally. I would like a single perfect xml file to copy into the plugin directory. 

Downloading multiple environment files from cloudsmith, then copying them to the plugin directory, then executing the python file which creates files that are incorrect or generate gibberish is not simple. 

I agree with this
"In particular, there should be no need to edit any of the generated metadata files."

Can you verify that this is correct?

```
<?xml version="1.0" ?>
<plugins>
  <version>0.0.0</version>
  <date>2020-03-17 17:34</date>
  <plugin version="1">
		<name> VDR </name>

```

Can you verify that this is what the python script produces?
(It was not what my python script produced this morning, and I downloaded all branches this morning.)  The python program produced this

```
<?xml version="1.0" ?>
<opencpn-plugins>
  <version>0.0.0</version>
  <date>2020-03-17 17:34</date>
  <plugin version="1">
		<name> VDR </name>

```
Which I believe is INCORRECT.  Has this been fixed?

**Comment by bdbcat** [comment]
Rick...
Nothing has been changed.  It all works fine for me without editing.
Have you looked at vdr-plugin.xml.in and any of the 12 resulting vdr-plugin.xml files carefully?  Maybe post them here, and I'll take a look.

**Comment by rgleason** [comment]
I have reviewed and torn apart vdr-plugin etc and put it back together over the last couple of days, same with squiddio.  

The error codes are no help at all when run on 33 files.

This morning I decided to move all 33 metadata files into a temporary folder and then one by one move them back and  run 
`python tools/ocpn-metadata generate --userdir metadata --destfile ocpn-plugins.xml --force `

until I found the exact file and filename with the errors. This is tedious and unnecessary if the exact filename was listed with the error.  I found about 3 errors.  The 33 files are comprised of testplugin, squiddio, vdr and weatherrouting.  Then with all the files together it ran reliably. 

I would prefer to have a single perfect (or imperfect) XML file for each plugin that can be downloaded and copied to the plugin directory.  It would save a lot of labor, however if that is not possible, it is mandatory, in my opinion, that the filename be included with any error listed.

I have reloaded the meta-url and added a batch file that is useful attached below.
[runcheck.bat.txt](https://github.com/OpenCPN/plugins/files/4355433/runcheck.bat.txt)

I hope someone will add the filename at the very least.

**Comment by rgleason** [comment]
PS: Dave  I believe that at some point  xml  template changed to using  "opencpn-plugins" or ocpn-plugins" which started the whole problem. I have no idea where it came from.

Since you haven't stated it explicitly yet, the accepted (from experience) XML format appears to be:

```
<plugins>
     <plugin>
           Plugin XML for a given environment in here.
     </plugin> 
</plugins>
```

Anything other than that, if found or appearing from some plugin, is wrong.

**Comment by bdbcat** [comment]
Rick...
The correct format is as you say.
I looked in history, and cannot find anything other than that.  No sign of "opencpn-plugins".

What exactly was the error in the the three "bad" XMLs?
Dave

**Comment by rgleason** [comment]
One was an "o"  that I had carelessly left in front of "plugins" tag.
One was a missing ">" at an ending tag  left over from a bad format in plugin code that I had corrected on all 8 or 10 metadata files earlier.
One was obviously a typo while working on some other document, because the <info-url>
has a return and was "url" with no >

I still think we need the name of the file listed in the output with the error.

**Comment by bdbcat** [comment]
Rick...
It seems that all of these errors would not occur if the xxx-plugin.xml.in file was correct from the start.  I just want us to become convinced that the CI process will not build a bad XML file if the xxx-plugin.xml.in file is correct.

**Comment by bdbcat** [comment]
Rick...
Added console output to ocpn-metadata python tool, all three branches.

```
dsr@dsr-HPE-580t:~/Projects/plugins$ python3 tools/ocpn-metadata generate --userdir metadata --destfile ocpn-plugins.xml --force
Processing:  metadata/weather_routing-plugin-darwin-10.13.6.xml
Processing:  metadata/oesenc-plugin-darwin-10.13.6.xml
Processing:  metadata/oesenc-plugin-ubuntu-gtk3-18.04.xml
Processing:  metadata/weather_routing-plugin-raspbian-9.4.xml

```

**Comment by rgleason** [comment]
Yes, xxx-plugin.xml.in  should be correct!   ...but thank you. This will help a lot.
