### ISSUE TITLE
MacOS Plugins not available

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#543]
See this [CF Thread](https://www.cruisersforum.com/forums/f134/macos-pim-plugins-testing-258613.html#post3537286)
we should have a goal to gradually get these plugins built for MacOS.

**NO MACOS VERSION IS AVAILABLE**
AutoTrackRaymarine 0.3.4.12 Coded for Win only --Not Tested
NmeaConverter 1.2.0.2 Not Visible Not Tested
TwoCan Plugin 2.0.0.0 Not Visible Not Tested
sar 2.8.2.0 Not Visible Not Tested
Javascript Almost released, Not Tested  - Javascript is in the Beta catalog  seen with [plugins] CatalogExpert=1
Twocan 2.0.0.0 - Steve advises that this very useful PI will have to wait.
Race Start Timer 1.1.0.0 - Steve advises will languish, it is in Tactics PI
Logbook    - working on update now.

**TESTED OK**
    vfKaps 3.1.0 - Pushed to PIM DONE
     Engine Dashboard, v1.4.1.0 Push to PIM DONE
     Photolayer 3.5.1  OK
    VDR 1.3.12.0  OK,  clarify opening status.
    oTcurrent 3.2.0 OK
    AIS-vd 1.5.0 OK
    UKTides 1.1.0 OK
    Radar 5.3 from Beta catalog - OK
     Celestial Navigation 2.3.11.0 -- OK Info button slow/does not work.
     Autopilot Route 0.4.4.0 -- Has issues see Dave Wright & Scarns rep

**Comment by bdbcat** [comment]
I'll take a look at VDR.  Seems the most popular on the list....

**Comment by rgleason** [comment]
Thanks, Dave. I don't mind updating it if you want me to.

**Comment by bdbcat** [comment]
Rick...
Well, OK,  since it is sort of "yours" anyway.  I stand by to help if necessary.

Thanks
Dave

**Comment by rgleason** [comment]
Tnanks it will give me a chance to learn the next version of Shipdriver template.

**Comment by rgleason** [comment]
VDR is done now. I believe Mike has also done several recently.
Perhaps it is time for another MacOS test?
See  https://www.cruisersforum.com/forums/f134/macos-pim-plugins-testing-258613.html

**Comment by rgleason** [comment]
Steve has pushed EngineDashboard now, for both MacOS.

**Comment by rgleason** [comment]
VDR_pi v1.3.16 makes changes you suggested. Will be merged to catalog sometime today.
Also Logbook v1.4.26 is in the catalog now.
Please try these and advise.
I also think Mike made some plugin changes which can be tested.
Earthexplorer

**Comment by rgleason** [comment]
MacOS PI are available now.
