### ISSUE TITLE
process: how it works?

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#6]
1. A plugin author joins their plugin with the Plugin Installer process by 
    - Adding appropriate files, scripts and cmake, and modifying them appropriate.y.
    - Getting accounts with circleci and cloudsmith.
    - Issuing a new version, uploading new binaries and an xml file for PI Installer
    - The PI author will want to test his uploaded xml file for proper operation.
    - Once confirmed, does he notify someone, or add a notice that his plugin available for update? file?
    - What happens if the PI author gets notified or realizes his recent changes need to be reverted and opencpn-plugin.xml has already been updated?

2. How is a signal sent to opencpn-plugin.xml operation that a plugin is available for update?
   - What triggers rebuild of opencpn-plugin.xml?
   - How is it checked?
   - How is it reverted?

3. Are there actions that can be automated?
4. Are some actions necessary to be manual for security or other reasons?

**Comment by bdbcat** [comment]
Rick...
1.  It should not be a requirement that CircleCI and Cloudsmith be used.  Whatever process the PI author wants to use to create the binary tarball and XML copy should be sufficient.

2.  To start, I suggest the author simply notify upstream (me) that a new plugin is available.  After a simple smoke-test, I will tweak the current opencpn-plugin.XML, make an announcement on CF, and we may consider the plugin "published".

3,  Reversions/modifications done as we do today:  Notify upstream of new XML contents as needed.

4.  I see no reason immediately to overly automate this process.  It is not a question of control.  More like removing the possibility of malicious abuse.  I want users to be confident that when they update opencpn-plugin.XML, some minimal executive validation has occurred, and the results are trustworthy.  Imagine, if you will, a malware plugin that pushes advertising onto OCPN app.... A trivial plugin that would destroy OCPN reputation overnight.  Nope.

**Comment by rgleason** [comment]
Great. That sounds very practical and should hopefully make things easier for Alec. Agreed about the need for care.

I think as a practical matter, that most plugin authors are not going to rethink or configure the process Alec has created, but agree that the scripts and services could be changed by an talented programmer.  

I believe it will be helpful to have some simple guidance for implementation of PI Installer in the Dev Manual and have added a couple of pages, and I'm trying to keep them current. Is this ok (referencing your trustworthy requirement)?

[Installer Summary](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:pi_installer_summary)
[
Installer Build-Deploy](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:pi_installler_build_deploy)

**Comment by leamas** [comment]
> To start, I suggest the author simply notify upstream (me) that a new plugin is available

Right. Typically done by a PR against OpenCPN/plugins which provides the new or updated xml file(s).

**Comment by rgleason** [comment]
Nice!

**Comment by rgleason** [comment]
Any suggestions? 
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:pi_installler_build_deploy#deployment_procedure

**Comment by leamas** [comment]
> Any suggestions?

The first impression is that this is a *lot* of information. Perhaps it could be condensed somehow, dunno. That said, I miss 2 pieces:

  - The procedure to generate a private ocpn-plugins.xml so that the uploaded tarballs can be tested. This  is more or less described in the  new plugins project (README.md).

  - The final part should be fixed to describe that a pull request typically contains four XML files, one for each platform.

**Comment by rgleason** [comment]
Thanks, added those to the bottom [here](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:developer_manual:pi_installler_build_deploy)
