### ISSUE TITLE
ocpn-install: Cannot parse plugin name from tarball name

### ISSUE THREAD

**Issue by leamas** [OpenCPN/plugins#60]
Currently, ocpn-install parses the plugin from tarball name, using a simple heuristic the any plugins called *name_pi* has a plugin name (common name *name*.

This heuristic does not hold. The only reliable way to get the filename is from the xml metadata. See  discussion in https://github.com/bdbcat/oesenc_pi/issues/79

**Comment by rgleason** [comment]
It's good this is happening now, as it will be a little disruptive to creating good catalogs.

**Comment by rgleason** [comment]
From   [Tarball Names](https://github.com/leamas/opencpn/wiki/Tarballs#tarball-names)
"plugin name>-<version>[-release]_<target os>-<target os version>.tar.gz"

However in the  "Tarball-URL"  here is one example:

`weatherfax-darwin-10.13.6-macos-tarball/versions/1.9.4.1+178.01c1c13/weatherfax_pi-1.9.4.1-ov50-1.16_darwin-10.13.6-macos.tar.gz`

In this case I know that the CommonName is actually  "WeatherFax".
Also there are additional designations at the end or the beginning (don't know which).
- Beginning:  " weatherfax-darwin-10.13.6-macos-tarball"
- Middle:  "versions/1.9.4.1+178.01c1c13/"  what is it for?
- End:  "weatherfax_pi-1.9.4.1-ov50-1.16_darwin-10.13.6-macos.tar.gz"

**Comment by leamas** [comment]
> From Tarball Names
"plugin name>-[-release]_-.tar.gz"


The actual quote is `<plugin name>-<version>[-release]_<target os>-<target os version>.tar.gz`

Which means that *weatherfax_pi-1.9.4.1-ov50-1.16_darwin-10.13.6-macos.tar.gz* will be parsed as 
name: weatherfax_pi
version: 1.9.4.1
release: ov50-1.16
target-os: darwin
target-os-version: 10.13.6-macos

Everything here is just fine besides target-os-version which should be 10.13.6 (drop the -macos suffix, it duplicates the darwin part)

**Comment by rgleason** [comment]
Thanks.
"it will not be possible to force plugins to use the common name"
Why not?  It makes perfect sense to use the "CommonName" for consistency.
Is it the capitals or something?  Or just to chicken to change it? 

So the Tarball Name is at the "end" and should be:
_weatherfax_pi-1.9.4.1-ov50-1.16_darwin-10.13.6.tar.gz_

What are the "Beginning" and "Midddle" parts of the Target-URL?
