### ISSUE TITLE
build-focal-armhf

### ISSUE THREAD

**Issue by Hakansv** [OpenCPN/plugins#607]
@leamas 
I tried to get my plugin to build for ubuntu-armhf so I copied "circleci-build-focal-armhf.sh" from o-charts and corresponding code to config.yml
Now I get this circleci error:
```
#!/bin/bash -eo pipefail
ci/circleci-build-focal-armhf.sh
/bin/bash: ci/circleci-build-focal-armhf.sh: Permission denied
Exited with code exit status 126
CircleCI received exit code 126
```
See [here](https://app.circleci.com/pipelines/github/Hakansv/ais-vd_pi/28/workflows/aa073f46-1fab-4e86-a702-ee66c0443c6c/jobs/295)
What permission may I've missed?
Code [here](https://github.com/Hakansv/ais-vd_pi)
Thanks/Håkan

**Comment by leamas** [comment]
Linux uses execute permissions on batch scripts. If you list that script on the original (source) host you would see something like
 
    $ ls -l ci/generic-build-flatpak.sh
    -rwxrwxr-x 1 mk mk 2529 Jan  6 17:54 ci/generic-build-flatpak.sh

The three x'es here means that the file is executable for owner, group and world i. e. everyone.

If you list your file it will look like

    $ ls -l ci/generic-build-flatpak.sh 
    -rw-rw-r-- 1 mk mk 2529 Jan  6 17:54 ci/generic-build-flatpak.sh

i. e., it has no execute permissions. Fix by doing something like `chmod ugo+x ci/circleci-build-focal-armhf.sh` which adds execute permissions for user, group and others. If you know octal representation `chmod 755`does the same and is less to print.

**Comment by Hakansv** [comment]
Thanks.
Now I'm on Win but using Git Bash show this 
```
$ ls -l circleci-build-focal-armhf.sh
-rwxr-xr-x 1 HAS-WIN 197121 3302 Jan 20 02:39 circleci-build-focal-armhf.sh*
```
Isn't that good enough?
And using:
`$ chmod 755 circleci-build-focal-armhf.sh`

make no difference:
```
$ ls -l circleci-build-focal-armhf.sh
-rwxr-xr-x 1 HAS-WIN 197121 3302 Jan 20 02:39 circleci-build-focal-armhf.sh*
```

**Comment by Hakansv** [comment]
And BTW the other files where circleci builds fine are having the same permissions.

**Comment by leamas** [comment]
You cannot really cope with this on WIndows, the file system does not support these permissions. git-bash does it's best and sees all files that like like scripts as executable, but it doesn't mean the file actually  have anything ot the kind.

That said, good that you have opened your git-bash prompt. One of the nice parts of git-bash is ssh, which make it easy to login to whatever linux host you have on your network. And, not least, also works when logging in to the CircleCI builders where you can poke around, check permissions etc.

But in the end, you basically cannot add execute permissions in windows. Git, whih knows about these permissions, offers a loophole  and can add them so they becomes visible when checked out on a host which understands them. See [stackoverflow question](https://stackoverflow.com/questions/21691202)

**Comment by leamas** [comment]
> And BTW the other files where circleci builds fine are having the same permissions.

Did you check that on Windows? Because if you did, it just doesn't work.

**Comment by leamas** [comment]
This is what I see in your cloned repo: 

```
]$ ls -l ci
total 72
-rwxrwxr-x 1 mk mk 1853 Feb 14 22:25 check-key-password
-rwxrwxr-x 1 mk mk 1795 Feb 14 22:25 circleci-build-android.sh
-rw-rw-r-- 1 mk mk 2722 Feb 14 22:25 circleci-build-bionic-armhf.sh
-rwxrwxr-x 1 mk mk 2010 Feb 14 22:25 circleci-build-debian.sh
-rwxrwxr-x 1 mk mk 3981 Feb 14 22:25 circleci-build-flatpak.sh
-rw-rw-r-- 1 mk mk 3302 Feb 14 22:25 circleci-build-focal-armhf.sh
-rwxrwxr-x 1 mk mk 2389 Feb 14 22:25 circleci-build-macos.sh
-rwxrwxr-x 1 mk mk 1726 Feb 14 22:25 drone-build-raspbian.sh
-rwxrwxr-x 1 mk mk 3048 Feb 14 22:25 generic-build-raspbian-armhf.sh
-rwxrwxr-x 1 mk mk 8444 Feb 14 22:25 git-push
-rwxrwxr-x 1 mk mk  303 Feb 14 22:25 git-push.sh
-rwxrwxr-x 1 mk mk 3144 Feb 14 22:25 new-credentials
-rw-rw-r-- 1 mk mk 2031 Feb 14 22:25 travis-build-win32.sh
-rwxrwxr-x 1 mk mk  822 Feb 14 22:25 upload.bat.in
-rwxrwxr-x 1 mk mk  966 Feb 14 22:25 upload.sh.in
-rw-rw-r-- 1 mk mk  361 Feb 14 22:25 windows-ldd

```
It's pretty clear that  circleci-build-bionic-armhf.sh and  circleci-build-focal-armhf.sh are 644 i. e., they have no execute permissions.

**Comment by Hakansv** [comment]
Many thanks for the link above!
By Git on Windows:
`C:\Builds\OCPN\ais-vd_pi>git add --chmod=+x ci\circleci-build-focal-armhf.sh`
That did the thing!!
Now all builds!
Good lesson. (And I managed wo bash!! :) )
Håkan

**Comment by leamas** [comment]
OK. Note my EDITs above

**Comment by leamas** [comment]
... and please close the issue. We should not really be using issues for these kind of discussions. 

Mike, Rick and I have a channel on zulip, a chat program. Could perhaps make sense?

**Comment by Hakansv** [comment]
The issue method was selected since I though something in the process went wrong and I've never seen that error before.
Of course I close an issue when solved. That's how thing works all time - or?

**Comment by leamas** [comment]
>  The issue method was selected since I though something in the process went wrong and I've never seen that error before.

ok, i didn't understand that. case closed.
