### ISSUE TITLE
Duplicated meta-url in Alpha

### ISSUE THREAD

**Issue by leamas** [OpenCPN/plugins#610]
b2e9c7e5f78f3ccc6833fbdd02330dcd0220be58 introduced a copy of Rick's meta-url in the wrong place, making the catalog unparsable.

IMHO this commit should be reverted. 

See: https://github.com/OpenCPN/OpenCPN/issues/2568

**Comment by rgleason** [comment]
There is nothing in my meta-url

```
<?xml version="1.0" encoding="UTF-8"?>
<opencpn-plugin version="1">
  <name> Rick Gleason Alpha Plugins meta-url </name>
  <version> 1.0 </version>
  <release> 0 </release>
  <summary> meta-url rgleason Alpha Plugins </summary>
  <api-version>  </api-version>
  <open-source> yes </open-source>
  <author>  </author>
  <source>  </source>
  <description>  </description>
  <target>all</target>
  <target-version> </target-version>
  <target-arch>noarch</target-arch>
  <tarball-url>  </tarball-url>
  <meta-url> https://raw.githubusercontent.com/rgleason/plugins/Alpha/ocpn-plugins.xml </meta-url>
</opencpn-plugin>
```

It must be something else

**Comment by leamas** [comment]
> It must be something else

No, it's not. Please read my post. Note:

  - It says that "b2e9c7e introduced a copy of Rick's meta-url in the wrong place, making the catalog unparsable."
  - It contains a link which describes exactly where this copy is placed.

Just to be clear, since my explanation seemingly are not sufficient. There are two lines with "your" meta-url in the catalog:

    $ git checkout Alpha
    $ git grep rg-alpha  ocpn-plugins.xml
    ocpn-plugins.xml:    <meta-url> https://raw.githubusercontent.com/rgleason/plugins/rg-alpha/ocpn-plugins.xml </meta-url>
    ocpn-plugins.xml:    <meta-url> https://raw.githubusercontent.com/rgleason/plugins/rg-alpha/ocpn-plugins.xml </meta-url>

One of these is the bogus copy introduced byb2e9c7e.

Don't know how to explain this so it's possible to understand. Is my English too bad to actually be read?

**Comment by rgleason** [comment]
I Figured out last night that the reason it is "unparsable" is because in updating some Shipdriver based plugins, I followed instructions to setup the auto branch on plugins, thereby removing my rg-alpha branch.
The reason the error is occurring is because that branch no longer exists.

I think the script should check to make sure the meta-url exists and if it doesn't send a message and ignore it.

**Comment by rgleason** [comment]
I will next reinstate the branch.

**Comment by leamas** [comment]
The meta-url solution is somewhat of a kludge, and we would certainly be better off removing it completely. If not, there is a need to update the xsd files, but only in the Alpha branch which is a pain. 

However, as developer you and others need to publish your own catalog. There is now documentation available in the TESTING.md file [here](https://github.com/OpenCPN/plugins/blob/master/TESTING.md#publish-a-private-catalog) on how to create a "personal" catalog which you can publish and use as "Custom URL". This is a much lighter and cleaner solution. It's also not that complicated. IMHO, the best now would be if you give this a try and thus makes the need for meta-url obsolete.

**Comment by leamas** [comment]
> Alec, I can't help to notice your snide disdain.

Well, I'm not a native Englisch speaker, you shouldn't interpret too much. And not use  such complicated such complicated words as above which I need to google.  

> I think the reason the error is occurring is because that branch no longer exists.

No, it's because there are two copies of your meta-url, one of which bogus. This bogus copy was introduced  July 23. 2021. All of which available in link in my first post.

I think the basic conclusion here is that the meta-url thing sort of disturbs workflows.  Yet another reason to try to get rid of it.

**Comment by rgleason** [comment]
Ok, I see your point, and I saw your proposal/commit to use Custom url's in a similar way for testing. 

I haven't used this feature much, but it would be very convenient to be able to simply test plugins by having a custom url that you could point users too, that does not require acceptance of the commit, and as long as it does not interrupt Alpha.

I will fix it for now.

**Comment by rgleason** [comment]
https://github.com/OpenCPN/plugins/pull/611

There were two metadata versions of my url, an earlier one and a more recent one. Now have just one there.
Also removed rgleason/plugin  metadata because that branch does not exist right now.
Will recreate it and make it empty of plugins.

**Comment by rgleason** [comment]
Both Jon's and my meta-url refer to our remote ocpn-plugins.xml   

- jongough/plugins/ocpn-plugins.xml
- rgleason/plugins/ocpn-plugins.xml

Therefore, I have cleaned out my ocpn-plugins.xml and pushed that up to my remote
https://github.com/rgleason/plugins/commit/f0f1d4b42f70a8212b23f4644376d851aca38ea8

**Comment by rgleason** [comment]
Reviewing the new instructions for Custom catalog I have the following thoughts:

- I use master and beta and auto for plugins a lot, so involving them is a bad idea.
- Keeping the plugins repository clean and clear for working on PI  is important to me.
- So I don't want to mess plugins up with meta-url and then have to change it again.
- They are really two separate things.  Publishing and a chance to publish for Testing.

Testing
https://github.com/OpenCPN/plugins/blob/master/TESTING.md#publish-a-private-catalog
> The web browser URL window will display an url like https://raw.githubusercontent.com/some-user/plugins/master/ocpn-plugins.xml This is the custom url, take a note or just copy it.

So why couldn't I have a "test" repository that works the same way as plugins but provides for us to set up "meta-url"?   

Is that possible? 

The advantages are it is used for publishing plugins that need to be tested.
It has a dedicated URL

`github.com/<username>/test/ocpn-plugins.xml`

which is totally separate from Alpha.

**Comment by rgleason** [comment]
Yes maybe that is a good way to do it, similar to my original "rg-alpha"  but somehow I knocked that out with git operations on my remote plugin.  I am going to have to be more careful I guess.

Alec, this proposed custom catalog approach isn't using meta-urls is it?

**Comment by leamas** [comment]
No, here are no meta-urls involved. As I see it  a major advantage.

**Comment by rgleason** [comment]
I will eventually give this a try.

**Comment by leamas** [comment]
The duplicated meta-urls are fixed. Closing
