### ISSUE TITLE
Polar_pi v 1.1.25

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#634]
This has been added to "plugins"  https://github.com/OpenCPN/plugins/tree/master/metadata
but is acting very strangely.  
1. When I remove it an try updating the catalog to 2022-03-19 14:36 , polar_pi does not appear in the PIM LIst.
2. Earlier after update when clicking on Polar_pi in the PIM list there were no choices to install, but it could be enabled.
3. I can "import plugin" the immediate predecessor as a test and it works fine.
4. The files all seem to exist in Cloudsmith https://cloudsmith.io/~opencpn/repos/polar-prod/packages/
5. I've tried closing Opencpn and reopening it and Polars is still completely missing from the PIM list even though it exists in the plugins catalog.
6. What is going on here?

I am very puzzled about this.

**Comment by bdbcat** [comment]
Please read the OCPN logfile.  Search for all references to "polar_pi".  This will tell something.

**Comment by rgleason** [comment]
Thanks. Found the issue was the nmea0183 version used does not match the standard version, so  pushed a new version to plugins.
