### ISSUE TITLE
OS: RPI  Plugins: TP 1.0.194  not showing in toolbar

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#639]
https://www.cruisersforum.com/forums/f134/os-raspberry-specific-rpi-201366.html#post3597921

Uwe reports this.  "Installed now the 64 Bit-version (bullseye) on my raspberry and trying to install OpenCPN without much hazzle, I used Flatpak. "

Involves many recently updated TP 1.0.194 plugins.
Celestial-Navigation, Climatology, Findit, OCPN Draw, Plots, Polar, squiddio, VDR, Watchdog, Weatherfax, Climatology, Tactics  Polars and finally Weatherrouting,.

Is it the TP build or is it OpenCPN?

We need some RPI Testers.

**Comment by bdbcat** [comment]
And then we need to read the logfiles.

**Comment by rgleason** [comment]
Fixed
