### ISSUE TITLE
Plugin Testing - Volunteer Roster

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#660]
We need a group of volunteer testers for all of the plugins.
Before releasing plugins we need users to at least **Basic Test** all the plugins available in their OS and to advise of any problems. This will avoid a lot of trouble for everyone.

Please indicate your OS, name, Git Pseudonym and CruiserForum  Pseudonym  below:

Operating System  Name  Git Pseudonym   CF Pseudonym

    win10  Rick Gleason  rgleason  rgleason
    win10 Kevin sailingjazz 
    macOS Catalina Scarns Steve
    macOS wx315 Monterey version 12.3.1  Amajori Antonio
    armhf ubuntu focal (Ubuntu 20.04.4 LTS Focal Fossa ) ParL
    Android ??? ParL
    Android arm64 sailingjazz Kevin
    Flatpak     filochard  ?
    rpi armhf stretch
    rpi armhf ubuntu buster/10  Mike Grouch   mgrouch
    rpi armhf debian buster/10
    rpi armhf debian bullseye/11
    rpi armhf ubuntu focal
    bionic gtk3
    bionic
    focal gtk3 
    buster
    flatpak arm64 
    flatpak x86 2008
    flatpak x86 2008 beta
    flatpak x86 1808 

**Basic Testing** - What we are looking for is very basic operational testing. 

- Does it Install properly?
- Does it enable without errors?
- Does the Preferences menu open and close properly?
- Does the starting menu open and close properly?
- Do the menus appear to be working properly?

**Extended Testing for Operation** - Then later more complete testing.

**Comment by rgleason** [comment]
Bdbcat advises:

> "All" should be the target, but reasonably one should prioritize on the platforms that are known to be in high demand. (Windows, MacOS, ubuntu 20.04, raspios, Android, debian/11.)"

**Comment by rgleason** [comment]
### List of OS with Volunteers (to date)

    Win10 sailingjazz Kevin
    Win10 rgleason Rick
    MacOS Catalina Scarns Steve
    MacOS wx315 Monterey version 12.3.1  Amajori Antonio
    armhf ubuntu focal (Ubuntu 20.04.4 LTS Focal Fossa ) ParL
    Android ??? ParL
    Android arm64 sailingjazz Kevin

### Potential volunteers

armhf ubuntu buster  (rpi ubuntu buster 18.04.1)   mgrouch
???   Hakan
Flatpak???  Filochard

**Comment by rgleason** [comment]
Plugin testers needed for these OS:

    rpi armhf stretch
    rpi armhf ubuntu buster/10
    rpi armhf debian buster/10
    rpi armhf debian bullseye/11
    rpi armhf ubuntu focal
    bionic gtk3
    bionic
    focal gtk3
    buster
    flatpak arm64
    flatpak x86 2008
    flatpak x86 2008 beta
    flatpak x86 1808

Please add your OS, name, github pseudonym, CruiserForum
pseudonym

**Comment by Jon-Hacking** [comment]
Win10 Jon Hacking Jon.Hacking Jon Hacking

**Comment by filochard** [comment]
flatpak 20.08 linux x86-64  (Mageia 8)
and linux x86-64 (Mageia 8) which I used to build packages for (when it was still possible)
github pseudo filochard

**Comment by rgleason** [comment]
That is  great filochard. Thank you!

**Comment by rgleason** [comment]
I've started a discussion under git community discussions which was moved to Github Actions
How to manage Plugin Development 
https://github.community/t/how-to-manage-plugin-development/246926/2

**Comment by rgleason** [comment]
We are still looking for PI Testers for these OS:

13 |   | rpi armhf stretch
14 |   | rpi armhf debian buster/10
15 |   | rpi armhf debian bullseye/11
16 |   | rpi armhf ubuntu focal
17 |   | bionic gtk3 bionic
18 |   | focal gtk3 buster
20 |   | flatpak arm64
21 |   | flatpak x86 2008
22 |   | flatpak x86 2008 beta
23 |   | flatpak x86 1808

**Comment by rgleason** [comment]
Here is the second draft of the spreadsheet.  Added links to Cloudsmith  beta packages and a Current Testing row.

[Google Spreadsheet](https://docs.google.com/spreadsheets/d/19JvjTHTXqzE-atlgQ_SPdqTaAxfCUAiQ5_1vXa1ENb0/edit?usp=sharing)

**Comment by rgleason** [comment]
Weatherfax 1.9.32.1 Flatpak Only, in the Beta Catalog. These are new builds. We need the four "Flatpak" versions tested to see if they work!

Please report the results of your tests in the [Testing Spreadsheet](https://docs.google.com/spreadsheets/d/19JvjTHTXqzE-atlgQ_SPdqTaAxfCUAiQ5_1vXa1ENb0/edit?usp=sharing) or in the [Cruiser's Forum Weatherfax thread](https://www.cruisersforum.com/forums/f134/weatherfax-97533.html)


Note that this version is just to test flatpak.

**Comment by nocheinpeter** [comment]
> Operating System Name Git Pseudonym CF Pseudonym

Android arm64 Peter nocheinpeter nocheinpeter

I have a Samsung Galaxy Tab A (Android 11) und would like to contribute for openbCPN PyPilot and watchdog pi. I use a PCNautic PyPilot. I can also contribute for dashboard pi

**Comment by rgleason** [comment]
Peter, I have added you and your OS to the [Test Spreadsheet](https://docs.google.com/spreadsheets/d/19JvjTHTXqzE-atlgQ_SPdqTaAxfCUAiQ5_1vXa1ENb0/edit#gid=0)  however I need your email, preferably a gmail.  Please Private Message me from Cruiser's Forum to "rgleason"  I need to add that to the spreadsheet so you have access.

**Comment by nocheinpeter** [comment]
Done. Thanks.

Rick Gleason ***@***.***> schrieb am Fr., 10. Juni 2022,
01:12:

**Comment by nocheinpeter** [comment]
Just tested the status bar plugin on Android. Got no update on beta but on master catalog. Now it works. Thanks!

**Comment by rgleason** [comment]
Thank you all for testing. I am closing this now.
