### ISSUE TITLE
Engine dashboard doesn’t show up

### ISSUE THREAD

**Issue by mgrouch** [OpenCPN/plugins#667]
If I hide engine dashboard by doing right click on it and unchecking and then click on toolbar to show it then engine dashboard doesn’t reappear 

thanks

**Comment by TwoCanPlugIn** [comment]
Expected behavior. 

When you right click & uncheck, you are saying "do not show this dashboard", 
You need to go into the preferences and check "show this dashboard" to re-enable it.

BTW, the normal dashboard exhibits the same behavior.

**Comment by rgleason** [comment]
@mgrouch  Please close. Thanks.
