### ISSUE TITLE
Weatherfax - Australia BOM - opencpn download issues

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#674]
Evidently weatherfax_pi is using the opencpn download routine which is failing and causing the plugin to no longer work for Aus-BOM urls.

We have tried using ftp because the Aus-BOM provides an ftp website for their files, but this is not as convenient or as good as using the normal http:// downloads because the weatherfaxInternetRetrieval _Australia.XML file is already set up for using http://

AUS-BOM is a very important source for a large part of the world and the plugin currently does not have that available.

In both LInux and Windows we get
![wxfax-AUS-BOM](https://user-images.githubusercontent.com/2363959/167276067-da30f481-d0b1-4515-bc56-b3392c245ed2.png)

However both Ozolli and I do not believe there is an internet problem. We think it is related to weatherfax or OpenCPN downloads.

Please see the weatherfax Issue  [Bug: Download URL's fail in particular Australia BOM #75 ](https://github.com/rgleason/weatherfax_pi/issues/75)

In particular, please note this post
https://github.com/rgleason/weatherfax_pi/issues/75#issuecomment-1120313204

Can anyone advise regarding this, to shed some light on why the plugin is having difficulty with downloads of URL's?

Also there have been some changes on the AUS-BOM and it may be better if we could use ftp to download because they have an ftp server.  Is this possible and how would it be done?

**Comment by bdbcat** [comment]
Rick...
First thing:
Please try to download that URL in the error dialog   (http://www.bom.gov.au.....003.png)  with simple Web browser.
Can it be downloaded?
Dave

**Comment by ozolli** [comment]
The URL can be downloaded using a regular web browser but using curl it is blocked.
The simple way to bypass this is to set a user agent in curl like so:
`curl -A "Mozilla/5.0 Gecko/20100101 Firefox/81.0" http://www.bom.gov.au/fwo/IDY00030.202205070600.png --output IDY00030.202205070600.png`
Can this be done in OCPN_downloadFile ?

**Comment by rgleason** [comment]
This one works in the browser. Does not in wxfax.

http://www.bom.gov.au/fwo/IDY00030.202205071800.png

**Comment by rgleason** [comment]
Ok, Good Morning.  Australia Test using the attached WeatherFaxInternetRetrieval [WFIR] _Australia xml file

[WeatherFaxInternetRetrieval_Australia.zip](https://github.com/OpenCPN/plugins/files/8646879/WeatherFaxInternetRetrieval_Australia.zip)

Added this rRegion
```
      <Region Name="Australia Test"> 
         <Map Url="IDY00030.202205071800.png"
             Contents="Surface Pressure Analysis" Area="Australia" />
		 <Area Name="Australia" lat1="55S" lat2="0S" lon1="90E" lon2="180E" />	 
     </Region>
```

Two screenshots
![Aus-Test-wxFax](https://user-images.githubusercontent.com/2363959/167294366-879400c5-429b-44af-929a-a1964dc96136.png)
![Aus-Test-Firefox](https://user-images.githubusercontent.com/2363959/167294370-d9450dc5-5bfe-4aa5-84d0-5e3444a4bff2.png)

Dave Please note these comments in the other thread.
https://github.com/rgleason/weatherfax_pi/issues/75#issuecomment-1120223155

We then looked at the copyright and some statements made on the website
https://tgftp.nws.noaa.gov/fax/otherfax.txt
https://www.cruisersforum.com/forums/f134/weatherfax-97533.html#post3618114
GordotheGrey found the ftp website
https://www.cruisersforum.com/forums/f134/weatherfax-97533.html#post3619125
I have found that the files are available via FTP from
ftp://ftp.bom.gov.au/anon/gen/

I started looking into the ftp server, what was there

Then Ozolli reported about "web scraping"
https://www.cruisersforum.com/forums/f134/weatherfax-97533.html#post3619173

Copyright found
https://github.com/rgleason/weatherfax_pi/issues/75#issuecomment-1120232209
Copyright at the bottom of the page: http://www.bom.gov.au/catalogue/anon-ftp.shtml
All products available via the anonymous FTP service are subject to the default terms of the [Bureau's copyright notice](http://www.bom.gov.au/other/copyright.shtml): you may download, use and copy that material for personal use, or use within your organization but you may not supply that material to any other person or use it for any commercial purpose. Users intending to publish Bureau data should do so as [Registered Users](http://www.bom.gov.au/other/charges.shtml).

Are we outside the copyright? .being opensource? ..are OpenCPN users part of the OpenCPN organization?

https://github.com/rgleason/weatherfax_pi/issues/75#issuecomment-1120233882
No we are not outside the copyright. OpenCPN provides no BOM resource to the end user, it provides a way to get those resources for their own personal use.   - and I agree.

Using the FTP Service http://www.bom.gov.au/catalogue/anon-ftp-hints.shtml

https://github.com/rgleason/weatherfax_pi/issues/75#issuecomment-1120230839

**Comment by rgleason** [comment]
Where does this leave us? 
See https://github.com/rgleason/weatherfax_pi/issues/75#issuecomment-1120313204

Big tar files can be downloaded from the ftp website if we were able to use ftp,  but they are not good for sailors. too big
https://github.com/rgleason/weatherfax_pi/issues/75#issuecomment-1120315318

Ozolli reports https://github.com/rgleason/weatherfax_pi/issues/75#issuecomment-1120230839

 managed to download the right image with lftp on linux:
CoreELEC:~ # lftp ftp.bom.gov.au
lftp ftp.bom.gov.au:/> get anon/gen/fwo/IDY00030.202205070600.png
184433 bytes transferred in 5 seconds (39.5 KiB/s)
lftp ftp.bom.gov.au:/> exit

This seems like the best route if it will work for other os

**Comment by ozolli** [comment]
For me the easy solution is to fake a regular web browser user agent so the weathefax Australia xml file works ok, but this is not what BOM wants.

The copyright compliant way is to be able to set a binary ftp file download in OCPN_downloadFile and we make a new Australia xml file with what's available on the BOM ftp server.

**Comment by rgleason** [comment]
Hopefully Dave has some suggestion.

**Comment by ozolli** [comment]
I can reconstruct the xml if needed.

**Comment by rgleason** [comment]
I wonder if faking the web browser agent will require a change in the ocpn_plugin.h. the plugin api? If so it will be some time before this gets fixed that way.  

Also, does it make sense to ask for this feature in any case for the future?

**Comment by bdbcat** [comment]
Rick/ozolli...
Let's start by reconstructing the XML file to contain the correct ftp links.  It may just work without other changes if that is done.
Dave

**Comment by ozolli** [comment]
Dave, I tried this already. OpenCPN downloads the file as ASCII instead of binary as I explained here: 
https://github.com/OpenCPN/plugins/issues/674#issuecomment-1120367327

**Comment by bdbcat** [comment]
OK, so this will need more work.
It is possible that this cannot be done by the current plugin API. In that case, we will need to add a direct curl ftp module to the plugin.  That is a piece of work, not too involved, similar to what is done with o-charts_pi.  But it will take a bit of coding and testing.
I'll take a look.  What branch on your weatherfax_pi repo is currently being used?

**Comment by rgleason** [comment]
Dave,
I just committed and built and tested locally the plugin work (except for 3-4  major bugs).  There is an Australia-Test Region with 4one weatherfax file,  in the Australia-BOM which fails, as does the rest of Australia BOM.  This is the most current issue.

https://github.com/rgleason/weatherfax_pi    Master branch   It is building now.  Version 1.9.30.5
The recent commit will push built plugins to Cloudsmith Opencpn Weatherfax-beta directory
https://cloudsmith.io/~opencpn/repos/weatherfax-beta/packages/?q=1.9.30.5


There is another bug you might be able to help us with, That is the Retrieve > Update Data failing because it is configured for just one file "weatherInternetRetrieval.xml, rather than the 12 separate files that we now have in the data directory (EG WeatherInternetRetrieval_Australia.xml   That function never got reconfigured.  See https://github.com/rgleason/weatherfax_pi/issues/74

**Comment by rgleason** [comment]
@bdbcat   Re: the Retrieve > Update Data bug, Thomas Traub has provided a PR which has been merged, which appears to solve the Retrieve > Update Data feature.   https://github.com/rgleason/weatherfax_pi/pull/80   

2-3 are updating various weatherfaxinternetretrieval files so we are making progress.

**Comment by bdbcat** [comment]
Rick...
I forked your master, and it fails immediately on Internet Retrieve.  Is this a known issue, or am I not driving correctly?
The current version in PIM master also fails in the same way.

**Comment by rgleason** [comment]
Ok, just checked  Retrieve > Internet  and several files are retrieved.

If you just pick  Retrieve > Internet  > "Australian BOM"  > Then pick Australia-Test  or any of the Regions and highlight and select to download.
![Screenshot (402)](https://user-images.githubusercontent.com/2363959/167523593-d3cecd4b-c2cb-4636-b8c7-cde166f864bb.png)
![Screenshot (403)](https://user-images.githubusercontent.com/2363959/167523596-911f401f-6c47-48e0-9a4b-4e1e0fb53a92.png)

**Comment by bdbcat** [comment]
OK, got it.
And where are the urls defined?  Some data file?

**Comment by bdbcat** [comment]
Rick...
OK, making progress here.  Found the URL definitions file(s).
I added ftp download capability to wefax, and it tests OK.  So this seems to be the way to go for AUS bom access.
Will take a few days to implement/test for all platforms.  There are some GUI bugs on linux, surprising that they have not been noticed in the field. 
Please stand by.

**Comment by ozolli** [comment]
I will then begin to organize the ftp charts and prepare the new WeatherFaxInternetRetrieval.xml file

**Comment by rgleason** [comment]
@bdbcat  Awesome Dave. Thank you for saving us lots of work changing files used.  
@ozolli  Thank you for doing this. It sure would be nice to shorten the name of the files to save typing. Maybe WFIR _  ? But would advanced users understand that?

**Comment by bdbcat** [comment]
ozolli..
I am using a "hand-crafted"  WeatherFaxInternetRetrieval.xm for testing.  I will await your final modifications before submitting a PR.  You may notify me here, and send direct to me, or do PR to Rick's repo, whichever suits.

**Comment by ozolli** [comment]
Hello Dave,
Except for a few IDY00030 there is not much in the fwo subdir. Many more interesting charts in the difacs subdir so
`<Server Name="Australia bom" Url="ftp://ftp.bom.gov.au/anon/gen/">`
and we will prefix either subdir in the Map Url entries.

fwo meaning: I am French so not to much at ease with english acronyms. Maybe forecast weather something?

**Comment by bdbcat** [comment]
ozolli...
OK, I understand.
I am fine now for testing, awaiting your updates.

**Comment by bdbcat** [comment]
OK, I'll take a look.  Probably have a PR ready later this evening.
Dave

**Comment by bdbcat** [comment]
Rick.ozolli...
A very strange thing.
On Windows, if I use the new WeatherFaxInternetRetrieval_Australia.xml file, and associated new CoordinateSets.xml file, with the current Production master catalog version of WeatherFax_PI, it works without my new FTP code.
Is this a Windows only situation?  What's going on here?
I also notice that it will not work with OpenGL.
Suspicion:  The new Retrieval file seems to be downloading .gif files.  And these are evidently not corrupted by the OCPN_Download problem that affects .png files.
So, Question:  Are the desired files available as .png files, or are we stuck with poor quality .gif files from Australia?

**Comment by ozolli** [comment]
.gif only
Probably to be as lightweight as possible.

**Comment by rgleason** [comment]
Just back from the Boatyard.  The ftp downloads seem to work with Win10, however they are requiring use of Image Wizard.

**Comment by bdbcat** [comment]
Rick...
How exactly did you use with Image Wizard?  Does it work on OpenGL without Image Wizard?

**Comment by ozolli** [comment]
Works fine on Win10 vmware virtual machine with opengl.

The image wizard opens the first time because the CoordinateSets.xml in the user's appdata folder is not used; It's the one in ProgramData\opencpn\plugins\weatherfax which is used instead.
I have the same issue on linux Flatpak version : The installed CoordinateSets.xml is in $HOME/.var/app/org.opencpn.OpenCPN/data/opencpn/plugins/weatherfax_pi/data but the one that is read is in $HOME/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/weatherfax

**Comment by rgleason** [comment]
`The image wizard opens the first time because the CoordinateSets.xml in the user's appdata folder is not used; It's the one in ProgramData\opencpn\plugins\weatherfax which is used instead.`


Right I forgot

**Comment by ozolli** [comment]
> I thought the
> programdata/opencpn/plugins/weatherfax/data/coordinateSets.xml
> Just held the specific changes to coordinates by Image Wizard, but I may be wrong about that.

I think you're wrong about this on Windows and Flatpak linux at least. This is quite confusing as a plugin update does not update this file on the right location.
You're right on RPi as there is only one coordinateSets.xml and that's better.

**Comment by rgleason** [comment]
OK now I recall, before we had PIM,
C:\Program Files (x86)\OpenCPN\plugins\weatherfax_pi\data\ with coordinateSets.xml and WeatherfaxInternetRetrieval.xml
C:\ProgramData\opencpn\plugins\weatherfax\data (user writable directory)  with coordinateSets.xml and images downloaded.

I believe the C:/programdata version of coordinateSets.xml  contained just the user changes to coordinates, and the C:/Program Filex (x86)\  version of coordinateSets.xml  was referred to if there were no changes by the user.

**Comment by ozolli** [comment]
Yes I figured this out. The one where coords are saved and used in Windows is in programdata, and for linux Flatpak in $HOME/.var/app/org.opencpn.OpenCPN/config/opencpn/plugins/weatherfax. I have renamed coordinateSets.xml.save the other one and all is ok.

**Comment by rgleason** [comment]
Good idea for testing. Thanks. I should write this up in the manual in clearer terms.

**Comment by bdbcat** [comment]
Rick...
Please, let us close this issue here, and restart in your WEFAX repo Issues list, if necessary.
We will do better by isolating issues to one limited exhibited problem (e.g "ftp download for AUS", or " storage policy per platform".  That way we can fix and close things in a trackable way.

Thanks
Dave

**Comment by rgleason** [comment]
Agreed.  Sorry, was just communicating.   Perhaps I should push this to PIM Beta now, if I can get an updated TP frontend2.
Thank you for all your help David.
