### ISSUE TITLE
wx315 has been retired and wx32 is the replacement but not available for darwin

### ISSUE THREAD

**Issue by jongough** [OpenCPN/plugins#752]
Trying to build plugins for darwin-wx32 is not possible due to the pre built wxwidgets from:
https://download.opencpn.org/s/MCiRiq4fJcKD56r/download
is for wx315 not wx32.
The removal of wx315 from the plugins xml appears to have been premature. An example error message is:
`metadata/ocpn_draw_pi-1.8.17.0-darwin-wx315-x86_64-11.4-macos.xml:17: element target: Schemas validity error : Element 'target': [facet 'enumeration'] The value 'darwin-wx315' is not an element of the set {'all', 'android-arm64', 'android-arm64-v8a', 'android-armeabi-v7a', 'android-armhf', 'darwin', 'darwin-arm64', 'darwin-wx32', 'debian-armhf', 'debian-wx32-armhf', 'debian-gtk3-armhf', 'debian-x86_64', 'debian-wx32-x86_64', 'debian-arm64', 'debian-wx32-arm64', 'flatpak-aarch64', 'flatpak-x86_64', 'mingw', 'mingw-x86_64', 'msvc', 'msvc-64', 'msvc-wx32', 'raspbian-armhf', 'ubuntu-armhf', 'ubuntu-gtk3-armhf', 'ubuntu-gtk3-x86_64', 'ubuntu-x86_64'}.`

How can darwin-wx32 be built?

**Comment by jongough** [comment]
We are also back to the problem of the xsd in Alpha and Beta does not match what is in Master/Prod.  So the problem was only found when the plugin was attempted to be put into the master branch. The xsd for plugins should be consistent across all branches, with the most advanced being in alpha to give developers a chance to workout and bugs. Currently it appears that master is the development branch.

**Comment by bdbcat** [comment]
Yes, yes, yes.  Thanks for the reminder.
Other PI devs are indeed mostly using master for final publication, after local debugging.  But using alpha and beta is , or should be, ok too.
Done in github now.

**Comment by jongough** [comment]
The needs to be consistency between all branches of the repository. Changes should start in alpha and be migrated through to prod. There should also be a deprecation process, just changing on a whim the labels and types causes issues for developers and users.

**Comment by bdbcat** [comment]
" Changes should start in alpha and be migrated through to prod."
If you like, but this is certainly not required to publish a plugin.  The chances of a tester carefully following an Alpha-Beta-Prod testing workflow are frankly, pretty low in my experience.

Trust me, this work is not done on a "whim".  Work as done on the basis of priority.  Settling the plugin scheme has been deferred until some devs were actually ready to build new plugins.  The build process has started now, and so the priority is raised.  And we fix bugs as encountered.

**Comment by jongough** [comment]
If using FE2 then a push by the owner to a non-master branch will build into the alpha cloudsmith (any non master branch without a tag), if a tag is created it will go to beta, if the branch is merged into master it will build in beta and if a tag is created it will build into prod. So the process is semi automatic. It just takes the downloading of the xml and pushing that to this repository. That is part of the reason for changing version numbers when accepting multiple commits, it allows easier collection of the xml via the scripts and then checking that they are consistent with xsd that is to be used.

**Comment by Rasbats** [comment]
@antipole2 Is building for OpenCPN 5.6.2. Because he makes a target of darwin-wx315 his PR does not validate. Will raise an issue seperately.

**Comment by Rasbats** [comment]
https://github.com/OpenCPN/plugins/issues/815

**Comment by nohal** [comment]
There now is the final O5.8 WX dependency bundle available and the ABIs in place and working. I think we can close this.

**Comment by rgleason** [comment]
I believe Jon is overseas right now. You may not hear from him.

**Comment by leamas** [comment]
@jongough ^

**Comment by rgleason** [comment]
Jon this needs to be closed now. Thanks.
