### ISSUE TITLE
Potential Script Problem: Plugin script deletes metadata that should not be deleted

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#753]
We are not rebuilding plugins for OpenCPN v5.6.2!
Yet the plugin script will delete them!
We want to keep the plugins for OpenCPN v5.6.2 available.
I don't want to go to the trouble of having to Push them again.
I believe someone should fix this now before we start Pushing new plugin metadata.
Automation is nice but it needs to be maintained.

**Comment by bdbcat** [comment]
What script, please?

**Comment by rgleason** [comment]
Dave, I am thinking of the checking and verification script for the opencpn/plugins  pushes.

**Comment by bdbcat** [comment]
Rick...
Not using your workflow, so unfamiliar.  Can you point to the exact script you are using?

**Comment by rgleason** [comment]
Ah, very good point!  I believe it is the script that I use with bash, to automatically bring the metadata.xml files into my local opencpn/plugin repository, which I believe automatically removes the previous xml.  I will check this.

They are  C:\Users\fcgle\source\plugins\download_xml.sh
and  C:\Users\fcgle\source\plugins\download_xml_bash.sh

There are two lines

```
REPO="https://cloudsmith.io/~$3/repos/"
echo "Issuing command: wget -q -O - $REPO$1-$4/packages/?q=*$2*.xml"
my_array=()
echo "Show current files that match criteria"
ls metadata/$1*-$2*xml -la
echo "Deleting current files that match criteria"    <--------------------------------
rm metadata/$1*-$2*xml                                        <-------------------------------This one
echo "Finding files on remote cloudsmith repository"   
delimiter="href=\""
delimiter1=".xml\" title"
my_array=();
while read -r line; do
	if [[ $line == *$delimiter* ]] && [[ $line == *$delimiter1* ]]; then
		start=`awk -v a="$line" -v b="$delimiter" 'BEGIN{print index(a,b)}'`
		start=$((start + ${#delimiter} - 1))
		end=`awk -v a="$line" -v b="$delimiter1" 'BEGIN{print index(a,b)}'`
		end=$((end + 3 - start))
		line=${line:$start:$end}
		my_array+=( $line );
		echo "found: $line"
	fi
done < <(wget -q -O - "$REPO$1-$4/packages/?q=*$2*xml")

echo "Downloading files found that match criteria"
for URL in "${my_array[@]}"
do
```

**Comment by jongough** [comment]
This script deletes the current xml files that match the current download request. It does it locally only. This avoids having too many versions of the same version when multiple builds have been done.
Basically all plugins being made available should have unique version numbers otherwise there is no way of telling what is being installed.

**Comment by bdbcat** [comment]
I agree with Jon...
As long as you do not commit the deletion of files, the older files will remain in the catalog.
Please verify with the full workflow, and report results.

**Comment by rgleason** [comment]
**OK, for macos**

**Older, found in ocpn_draw-prod**
OpenCPN 5.6.2 Version:  ocpn_draw_pi-1.8.17.0-darwin-wx315-x86_64-11.4-macos-metadata==v1.8.17.0

**Newer, found in ocpn_draw-alpha**
OpenCPN 5.7.1  Version?:  ocpn_draw_pi-1.8.17.0-darwin-x86_64-11.4-macos-metadata==1.8.17.0+4746.fb18d05
OpenCPN 5.7.1 Version?  ocpn_draw_pi-1.8.17.0-darwin-wx315-x86_64-11.4-macos-metadata==1.8.17.0+4748.fb18d05

Are these for OpenCPN v5.7.1?   I can't tell the difference, but we need to keep both metadata types.


**For Windows**
**Older, found in ocpn_draw-prod**
ocpn_draw_pi-1.8.17.0-msvc-x86_64-10.0.14393-MSVC-metadata==v1.8.17.0

**Newer, found in ocpn_draw-alpha**
OpenCPN 5.7.1  ocpn_draw_pi-1.8.17.0-msvc-x86_64-10.0.14393-MSVC-metadata==1.8.17.0+803.fb18d05
ocpn_draw_pi-1.8.17.0-msvc-x86_64-10.0.14393-MSVC-metadata==1.8.17.0+812.fb18d05

We need to keep the older files too.  I believe that these lines remove the older files don't they?

**```
echo "Deleting current files that match criteria"    <--------------------------------
rm metadata/$1*-$2*xml                                        <-------------------------------This one
```**

**Comment by bdbcat** [comment]
Taking MacOS for example.
The two new builds are not named very well, even if they are built correctly.
We would need to look at the contents of these two XML files to sort this out.

1) ocpn_draw_pi-1.8.17.0-darwin-x86_64-11.4-macos-metadata==1.8.17.0+4746.fb18d05

2) ocpn_draw_pi-1.8.17.0-darwin-wx315-x86_64-11.4-macos-metadata==1.8.17.0+4748.fb18d05

I suspect that the first is actually the misnamed wx32 version, and the second is the wx315 version.  But we need to confirm this by examining the XML, and then correct the (FE2?) template to generate the correct unique filenames.

**Comment by rgleason** [comment]
Shouldn't the names of the metadata files reflect the Opencpn Version or something, so we don't get all screwed up maintaining and updating plugins. I can't imagine having to inspect contents of each file when there is a problem. I will get totally screwed up doing that with multiple plugins to update.

**Comment by bdbcat** [comment]
Rick...
Do you have a CI build that I can look at?

**Comment by rgleason** [comment]
I'am just going to update weatherfax to FE2 from Jon's current testplugin and will build it, so we can see.

**Comment by bdbcat** [comment]
Ok, I'll be busy today.  Later....

**Comment by jongough** [comment]
The problem is the inconsistent way that widgets, gtk, etc. are incorporated into the xml and then the building of the xml & tar files to match this. The numbers/letters on the end are added by build process to identify different automated builds. This is not done by FE2.

**Comment by bdbcat** [comment]
Rick...
Still waiting to see a test build on CI, for investigation.
