### ISSUE TITLE
wxWidgets 3.2.1 to build PI for OpenCPN v5.7.1

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#758]
I am having trouble getting setup to build plugins for OpenCPN v5.7.1
How do I setup wxWidgets 3.1.2 (opencpn5.6.2)  and wxWidgets 3.2.1 (opencpn5.7.1) to build properly?

OpenCPN build appears to have wxWidgets 3.2.1  located in 
C:\Users\fcgle\source\OpenCPN\cache\wxWidgets-3.2.1
C:\Users\fcgle\source\OpenCPN\buildwin      headers and stuff

----------

wxWidgets-3.2.1 is also found here

C:\Users\fcgle\source\OpenCPN\cache
C:\Users\fcgle\source\OpenCPN\buildosx
C:\Users\fcgle\source\OpenCPN\cache\buildwintemp\OCPNWindowsCoreBuildSupport-0.3\buildwin

---------

To build Opencpn 5.6.2  Plugins I have wxWidgets 3.1.2 in
C:\Users\fcgle\source\wxWidgets-3.1.2
With paths all defined.accordingly, and it should work.

--------

What are the steps I should take now to build plugins for v5.7.1 with respect to wxWidgets-3.2.1?
Can I install wxWidgets-3.2.1 alongside wxWidgets-3.1.2 here?
C:\Users\fcgle\source\wxWidgets-3.1.2
C:\Users\fcgle\source\wxWidgets-3.2.1

What do I set as the environment paths to avoid mix ups?
Where are these paths set in Cmake?  or is it using findwxWidgets now?

Confused.   I don't do this every day, so it does not seem very simple to me.

**Comment by rgleason** [comment]
I also need to get MSVS 2022 working properly, evidently something is wrong with it.  When I set the project folder to
C:\Users\fcgle\source\OpenCPN

Also when I try to set the sln file to opencpn.sln  under the build directory, no files show to select!  So something is wrong.

I get this error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:
    Change Dir: C:/Users/fcgle/source/OpenCPN/out/build/x64-Debug/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_3118e && 
    CreateProcess failed. Command attempted:
    ""C:\PROGRA~1\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe"    -o CMakeFiles\cmTC_3118e.dir\testCCompiler.c.obj -c C:\Users\fcgle\source\OpenCPN\out\build\x64-Debug\CMakeFiles\CMakeTmp\testCCompiler.c"
    ninja: fatal: CreateProcess: The file or directory is corrupted and unreadable.

  CMake will not be able to correctly generate this project.		C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/CMakeTestCCompiler.cmake	69	
```

Should I try updating MSVS 2022?

**Comment by rgleason** [comment]
I think I need to configure Cmake manually. Using similar settings to the MSVC 2017 version that builds, but I will need to copy some wxWidgets 3.2.1 files into the new cloned local repository.

These are the settings I need to follow from the MSVS 2017 setup

Top
![cmake-config-0](https://user-images.githubusercontent.com/2363959/206913713-f391b49f-d823-457f-a9ba-9a09a633c771.png)

Middle
![cmake-config-1](https://user-images.githubusercontent.com/2363959/206913721-31b9ba50-d7f9-4a7a-b3e7-daf8143cd04f.png)

Bottom - Before hitting config and generate
![cmake-config-2](https://user-images.githubusercontent.com/2363959/206913769-2be77ef3-78d3-4bf0-ad6f-45910450e4d0.png)

Bottom - After hitting config and generate
![cmake-config-3](https://user-images.githubusercontent.com/2363959/206913793-8c2dc3c7-8d32-444b-b1dd-51fd2e69b4fe.png)

**Comment by rgleason** [comment]
There is no "cache" directory in the newly cloned 
 C:\Users\fcgle\source\repos\OpenCPN

Copied entire "cache" folder of 443mb from C:\Users\fcgle\source\OpenCPN to the new location.
Next will try to setup the cmake file.   There are some other wxWidget files that are needed.

**Comment by rgleason** [comment]
I think I need to reinstall msvs 2022 and pick the right computer selection. What would that be?  86_64 ?

**Comment by bdbcat** [comment]
Rick...
I f you have time for Anydesk, I can help fix this up.
Dave

**Comment by rgleason** [comment]
Dave, that would be great. Would 5 pm est be okay, or any time later? Have to reco nnect the computer.

**Comment by bdbcat** [comment]
5 EST is fine.  see you then.

**Comment by rgleason** [comment]
Yes. Thanks

**Comment by rgleason** [comment]
Dave, 

I copied the compiled weatherfax_pi.dll from 
C:\Users\fcgle\source\weatherfax_pi\build\RelWithDebInfo
to
C:\Users\fcgle\AppData\Local\opencpn\plugins  
after renaming the existing weatherfax_pi.dll to weatherfax_pi.dll.temp

Then ran 5.7.1+6ecd688  and this 5.7.1 version of weatherfax_pi works OK.

![Screenshot (196)](https://user-images.githubusercontent.com/2363959/207135894-e9937608-0749-48a0-ba75-2d810e6ee8d7.png)

I then closed that and tried Opencpn 5.6.2  and got this.

![Screenshot (197)](https://user-images.githubusercontent.com/2363959/207136052-edb0abf5-581f-4c80-bfe3-df4bb6a84211.png)

Because we are using the same directory C:\Users\fcgle\AppData\Local\opencpn\plugins   for both versions of OpenCPN, all the plugins will have to be reloaded for that older version, every time you want to use it.

**Comment by rgleason** [comment]
Dave, I am not really understanding... I just swapped weatherfax_pi.dll (wx3.1.2)   for weatherfax_pi.dll  (wx3.2.1) in the directory  C:\Users\fcgle\AppData\Local\opencpn\plugins.   Is this how you expect it to work?  Whenever someone switches from OpenCPN v5.6.2 to v5.7.1 OR v5.7.1 to v5.6.2,  they have to reload and install all external plugins?

**Comment by bdbcat** [comment]
No user is going to do what you, as a dev/packager, are doing.
So, yes, if a curious user wants to switch between 562 and 571+, they will need to reload plugins to do it.
I ask, somewhat rhetorically, "who, other than a dev, would want to switch back to O562 after adopting O58?"  And especially,"who would want to do that on a regular basis?"

**Comment by rgleason** [comment]
Shouldn't there be a  
C:\Users\fcgle\AppData\Local\opencpn\plugins\wx32  folder
C:\Users\fcgle\AppData\Local\opencpn\plugins\wx31  folder

Just like the build-wx32 you showed me?

**Comment by bdbcat** [comment]
Nope.  The AppData folder is is fixed in OCPN core.  He always looks for plugins there.

**Comment by jongough** [comment]
I am not sure I understand what the FE2 naming issue is?

**Comment by bdbcat** [comment]
BTW, the exact same thing happens if you try to dowgrade Firefox.  All you AddOns (e.g.plugins) need to be found and reloaded.  This is not an uncommon pattern.

**Comment by jongough** [comment]
This is a new requirement for appbuilder and FE2. I will have a look at it.

**Comment by jongough** [comment]
With appveyor there does not appear to be any logic that can be applied to build for wx312 and wx32x within the same stream. I presume batch files have to be used to do this, but again it is two build streams. There will still be a need to build with the older widgets for fixes, etc. and systems that will not be able to run with the latest versions for whatever reasons.

**Comment by bdbcat** [comment]
SD plugin does indeed use a batch file that loops to build the two targets.  For inspiration, take a look at ci/appveyor.bat in the o-charts "sdt" branch.

**Comment by jongough** [comment]
Not really. I can see the two builds, but it is still using a new visual studio and I am not sure how it goes putting stuff to cloudsmith as it seems to store it in github. I can see what I can do, but.... Appveyor has never been as friendly as circleci and is much more limited to single builds, not really templating. 

I also, currently, don't see where you are setting the TARGET_TUPLE in the appveyor.bat file. This would be needed to show the different builds.

**Comment by rgleason** [comment]
What does SD do now? Build all 64 files old and new? I will run out of cloudsmith credits!

Also I would like to see filenames with "wx32" for all wx32 versions!  For human readable consistancy!

Old PI will keep old version number and be retained in clouds.ith (in -prod we retain all files now)  New pi will geat a new version number

**Comment by bdbcat** [comment]
"Old PI will keep old version number and be retained in clouds.ith (in -prod we retain all files now) New pi will geat a new version number"
This is what I am doing for o-charts.

It is indeed a simplification to build only for wx32.  This is the generally agreed plan.  But of course each plugin dev may do as they wish, so long as the published plugins are compatible and functional.
I suggest at this point in the cycle, to modify FE2 such that it produces only the wx32 plugins for win and Mac, and only the new debian-wx32-xx plugins for linux.  This is a greatly reduced number of builds, and will allow us to get to Beta testing on O571 expeditiously.

**Comment by rgleason** [comment]
I suppose the circleci/config.yml  could have old (wx312) builds that are turned off and new builds (wx321) that are turned on, and the ci/ directory could contain all the old (wx312) files as well as the new ones, then there might be some hope of recreating and rebuilding 5.6.2 plugins, but with the  opencpn/plugins guarddog scripts changing, we would never be able to push any changes for old plugins!

**Comment by rgleason** [comment]
I am again having trouble with cmake finding wxWidgets-3.2.1
I can't even get it to complete configuration in CMake GUI anymore.

wxWidgets-3.2.1 is now located here:
```
C:\Users\fcgle\source\wxWidgets-3.2.1   - copied from current OpenCPN cache directory
C:\Users\fcgle\source\wxWidgets-3.1.2   - git download and built.
```

System Environment under "System Variables" (type env in the search)
```
wxWidgets_INCLUDE_DIRS  %WXDIR%\include
wxWidgets_LIB_DIR              %WXDIR%\lib\vc14x_dll
wxWidgets_LIBRARIES           %WXDIR%\lib\vc14x_dll
wxWidgets_ROOT_DIR           %WXDIR%
WXDIR                                   C::\Users\fcgle\source\wxWidgets-3.2.1
```

System Environment  also under "Sytem Variables"  PATH has these
```
%wxWidgets_INCLUDE_DIR%
%wxWidgets_LIB_DIR%
%wxWidgets_LIBRARIES%
%wxWidgets_ROOT_DIR%
%WXDIR %

```
In weatherfax_pi CMakeLists.txt  changed
```
# define minimum cmake version
cmake_minimum_required(VERSION 3.24.1) 
```

I have also removed the extraneous  wxWidgets-3.1.2 folder under C:/wxWidgets-3.1.2
and have tried removing the copy of Opencpn "cache" folder from weatherfax_pi

Well, possibly I have to reboot. When I hit "Environment" (In the  "search" line to the right)  in CMake Gui I get a wrong "vc_dll" 
When I close CMake GUI and open it, I see that the paths are correct now, but when I run "Configure"
wxWidgets is not found still.

![wxWidgets-not-found](https://user-images.githubusercontent.com/2363959/207887933-d3d4c17a-b04d-416f-ab93-9301441aabc7.png)

**Comment by rgleason** [comment]
I tried to build Opencpn in  C:\Users\fcgle\source\repos\OpenCPN  and got some errors about Net Framework. So I decided to install Desktop Net Framwork using Microsoft Visual Installer.  Now VS 2022 has 
Desktop development with C++,  Linux and embedded development with C++,  .NET Desktop development.
Is .NET Desktop Development required?

**Comment by rgleason** [comment]
Removed all files under build directory and used CMake, entering win32 and v143 at the prompt and "configured"
Got a warning 
```
Building with bundled wxcurl
CMake Deprecation Warning at libs/wxcurl/CMakeLists.txt:8 (CMAKE_POLICY):
  The OLD behavior for policy CMP0077 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


SVG support enabled...

but configuring was done
```
and generate was done
but the panel is red and   wxWidgets_wxrc_EXECUTABLE-NOTFOUND

**Comment by rgleason** [comment]
When I open VS 2022 and it tries to build, I get
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error:
  Running

   'C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe' '-C' 'C:/Users/fcgle/source/repos/OpenCPN/out/build/x64-Debug' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:9211: bad $-escape (literal $ must be written as $$)		C:\Users\fcgle\Source\Repos\OpenCPN\   ninja		

```

**Comment by rgleason** [comment]
After reboot of the machine and rerunning CMake "configuration" and "generation" the red screen went away, but 
wxWidgets_wxrc_EXECUTABLE-NOTFOUND  was still there.

**Comment by rgleason** [comment]
I think we're just about there insofar as local build  and building windows with circleci  closing.
