### ISSUE TITLE
minimum cmake version  is not  3.24.1

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#761]
We are getting lots of fails in build for flatpak and ubuntu see
https://github.com/rgleason/weatherfax_pi

 it is possibly this.
cmake_minimum_required(VERSION 3.18.4) 

but it is more likely something less, because all the fails were using 3.18.4 and they failed.
So what should we be using? 3.16?

**Comment by rgleason** [comment]
Also what should we do with setting  CMP0043 policy.
This is going to be depricated.

```
if(COMMAND cmake_policy)
    if(POLICY CMP0043)
        cmake_policy(SET CMP0043 NEW)
    endif(POLICY CMP0043)
    cmake_policy(SET CMP0048 NEW)
# Need cmake 3.13 to implement this, but raspbian builds are at 3.7.2 and bionic at 3.10 and xenial builds at 3.5.1
#    cmake_policy(SET CMP0076 NEW)
    if(POLICY CMP0077)
        cmake_policy(SET CMP0077 NEW)
    endif(POLICY CMP0077)
```

**Comment by jongough** [comment]
You are trying to use a version of cmake that is not available for the build you are doing. You can see in the middle of your code section that I found that not all platforms are at the same level. So cmake needs to be set no higher than the lowest level for any platform.

Currently the minimum supported for all platforms is 3.5.1. This just means that the build will fail if it is below that level. You can use higher versions if you want, just make sure that if you specify it that it is available on all platforms you want to build for.

**Comment by rgleason** [comment]
> Currently the minimum supported for all platforms is 3.5.1. This just means that the build will fail if it is below that level.

So should I just set it back to 3.5.1?

**Comment by jongough** [comment]
Unless you have a reason to need to use a newer version leave it at 3.5.1. The 'current' version for the build should be installed, just to run the cmake scripts requires this version or newer.

**Comment by rgleason** [comment]
Thanks Jon
