### ISSUE TITLE
Generating new Ocpn-Plugins.xml

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#8]
https://github.com/rgleason/plugins/commits/master

I have pushed testplugin...xml up to my plugins repository here

https://github.com/rgleason/plugins/commits/master

I have python 3.5 and  I have tried this but it fails. How to fix it?

```
C:\Users\Rick\Documents\GitHub\plugins>python tools/ocpn-metadata generate --userdir metadata --destfile ocpn-plugins.xml
Traceback (most recent call last):
  File "tools/ocpn-metadata", line 137, in <module>
    main()
  File "tools/ocpn-metadata", line 132, in main
    generate(args.userdir, args.destfile, args.version)
  File "tools/ocpn-metadata", line 90, in generate
    subtree = ET.parse(path)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 585, in parse
    source = open(source, "rb")
TypeError: invalid file: WindowsPath('metadata/bsb4-plugin-darwin-10.13.6.xml')

```

**Comment by rgleason** [comment]
I made a PR for #9  from your repository, and ran it once successfully and it seemed to work and make a new ocpn-plugins.xml

Now I just tried it again, and it fails for some reason.

```
C:\Users\Rick\Documents\GitHub\plugins>python tools\ocpn-metadata generate --force --destfile ocpn-plugins.xml --userdir metadata
Traceback (most recent call last):
  File "tools\ocpn-metadata", line 137, in <module>
    main()
  File "tools\ocpn-metadata", line 132, in main
    generate(args.userdir, args.destfile, args.version)
  File "tools\ocpn-metadata", line 90, in generate
    subtree = ET.parse(str(path))
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 1195, in parse
    tree.parse(source, parser)
  File "C:\Users\Rick\AppData\Local\Programs\Python\Python35\lib\xml\etree\ElementTree.py", line 596, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 14, column 14

C:\Users\Rick\Documents\GitHub\plugins>
```

**Comment by rgleason** [comment]
Now using python commands with generated xmls for testplugin_pi a new opencpn-plugins.xml is made. 

When pushed to my github plugins repos, 
https://github.com/rgleason/plugins/blob/master/ocpn-plugins.xml

and when Opencpn-msvc-with-PI-Installer is loaded and Advanced URL loads my opencpn-plugins.xml,   

![Screenshot (309)](https://user-images.githubusercontent.com/2363959/70172079-fee02380-169d-11ea-9b68-600efa8f3dd7.png)

![Screenshot (308)](https://user-images.githubusercontent.com/2363959/70172105-07d0f500-169e-11ea-9215-4ba5864b9fe1.png)

Testplugin_pi gets loaded, but without Icons!
![Screenshot (310)](https://user-images.githubusercontent.com/2363959/70172135-161f1100-169e-11ea-8560-76a8ff6c24d2.png)

![Screenshot (311)](https://user-images.githubusercontent.com/2363959/70172173-233c0000-169e-11ea-9a62-f6a75b3b26a5.png)

**Comment by rgleason** [comment]
The files used here were from Testplugin_pi   opencpn-plugins   (unstable).
https://cloudsmith.io/~rick-gleason/repos/opencpn-plugins/packages/

**Comment by bdbcat** [comment]
Closing, obsoleted by recent developments
