### ISSUE TITLE
Using xz instead of gz

### ISSUE THREAD

**Issue by hreuver0183** [OpenCPN/plugins#80]
Is there still a reason to use tar.gz instead of for example tar.xz?
Nowadays gz is only used when compatibility of different systems is really an issue.
Since you have some basic requirements for linux systems already, you might as well include xz-utils which is pretty standard.

The difference in syntax should be something like "tar cJf <file>" instead of "tar cxf <file>".

Size difference of some repackaged tarballs:
`$ du gz xz2`
`6044	gz`
`3956	xz2`

**Comment by keesverruijt** [comment]
These tarballs end up being unpacked by OpenCPN itself, so it would need to add an extract library for xz. This is not the same scale of effort of adding a dependency and changing a flag.

**Comment by hreuver0183** [comment]
My mistake, I confuse xz sometimes with bzip2 (and bzip2 is off course obsolete).
The compression algorithm for xz is lzma/lzma2, which is included in the same archive.h as gzip.

Only reason gzip is still used nowadays is for compatibility with Open/Free/NetBSD.
I think that is hardly an issue for OpenCPN with the possible exception of MacOS.

In my opinion the change is more about policy and less about code.

**Comment by leamas** [comment]
Well... this is not only about unix, but also windows and Macos. There are options in both cases, but tar.gz is simple enough and ubiquitous. 

To be honest, I don't see the advantages of xz (primarely size) motivates a change. Might be wrong, for sure.
