### ISSUE TITLE
Plugins: ci/circleci-build-macos.sh   deprication + wget missing

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#83]
Brew appears to be a moving target right now.
Change the top as shown.
Need at least this, but it is still failing
https://github.com/rgleason/testplugin_pi/commits/master
after pulling from jongough/testplugin_pi/commits/jongough_fixup
but I did not see any potential problems of this sort from the changes.

```
if [ -n "$CI" ]; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi
	brew unlink python@2
	brew upgrade python
	brew ls python3
        brew install wget
       brew install cmake    <---need this too
wget -q http://opencpn.navnux.org/build_deps/wx312_opencpn50_macos109.tar.xz

```

Note:  This is working right now.

**Comment by rgleason** [comment]
Now the build says the cmake command is not found!  
Something basic is missing.
https://app.circleci.com/pipelines/github/rgleason/testplugin_pi/75/workflows/ba123d47-aab1-4eb8-9a84-afa2422f9ac8/jobs/449

**Comment by rgleason** [comment]
Now going to add 
    brew install cmake

**Comment by pa2wlt** [comment]
@rgleason FYI: Currently wget -q http://opencpn.navnux.org/build_deps/wx312_opencpn50_macos109.tar.xz returns the OpenCPN.org homepage.

**Comment by rgleason** [comment]
What are you trying to do?  Retrieve wx312?  This is closed.

**Comment by pa2wlt** [comment]
All fine @rgleason I just wanted to let you know that this line in the script did not work.
