### ISSUE TITLE
Plugins: Now raspbian buster armhf is failing.  How much of moving target is this?

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#84]
With so many environments it seems like there is always something failing. Or is this a cyclical thing?
I think we should publish generic fixes to scripts here,  for easy reference and general notification, so that the various plugin authors can make fixes perhaps.  

Or alternatively, and perhaps better, would be to have the fixes already done in a selected repository dependent on which frontend is used  IE Frontend1 and Frontend2

Right now I am hoping someone already has a solution for the raspbian 10 buster armhf script.
Which I can confirm is using the  "travis --wait" command.

https://github.com/rgleason/testplugin_pi/runs/590415418

**Comment by rgleason** [comment]
At 18 minutes it made it down to 
CPack: Create package using TGZ
CPack: Install projects
CPack: - Run preinstall target for: testplugin_pi

but it will just sit there for a very long time, start running again and then fail on time at 40 minutes.

**Comment by rgleason** [comment]
https://stackoverflow.com/questions/48711342/what-does-the-cpack-preinstall-target-do

> Apparently, this only happens if the CMake Generator / CPACK_CMAKE_GENERATOR you are using is Unix Makefiles, and is the result of CMake install commands not carrying any target dependency information with them.
> 
> One possible workaround is lying to CPack about what generator you're using, for example by setting CPACK_CMAKE_GENERATOR to Ninja.

**Comment by rgleason** [comment]
Failed again after 40 minutes:

CPack: Install projects
CPack: - Run preinstall target for: testplugin_pi
Timeout (40 minutes) reached. Terminating "sleep infinity"
The command sleep infinity exited with 137.

**Comment by bdbcat** [comment]
Rick...
I went thru this last night, but failed to notify you yet. Sorry...
Please check Frontenc#1 on oesenc_pi github master now.  It builds on all platforms, with proper metadata included in tarball.
Changes required on Mac build, and also the final "tar" commands to create the merged tarball, in several places.

**Comment by rgleason** [comment]
I see those changes now. I will need to update Frontend1 in squiddio.
However, looking at the travis-raspbian script, they both look pretty much the same at the top, and then for Frontend2, Jon is using another cloudsmith-upload.sh.in and I think that is where there is a problem in the buster 10 upload.  Somehow that version in travis has trouble uploading.

**Comment by bdbcat** [comment]
Where is your arm/buster travis build log, please?

**Comment by rgleason** [comment]
Dave, 
I hesitate because I don't want to take your time, but here it is

Log: https://travis-ci.com/github/rgleason/testplugin_pi/jobs/319801514
Travis: https://github.com/rgleason/testplugin_pi/runs/590415418
Testplugin: branch:Master  https://github.com/rgleason/testplugin_pi/commits/master

Travis script:
https://github.com/rgleason/testplugin_pi/blob/master/ci/travis-build-raspbian-armhf.sh
Cloudsmith-upload script:
https://github.com/rgleason/testplugin_pi/blob/master/cmake/in-files/cloudsmith-upload.sh.in
 
Thank you

**Comment by bdbcat** [comment]
Strange error.
So try the workaround:
At line 115 of testplugin_pi/cmake/PluginPackage.cmake, add this:

set(CPACK_CMAKE_GENERATOR Ninja)

Looks ugly, I know.
But we shall see.

**Comment by rgleason** [comment]
That works, and it builds faster. https://travis-ci.com/github/rgleason/testplugin_pi/jobs/319972929

Actually everything builds faster, but the Trusty build fails now with a permission problem.
https://app.circleci.com/pipelines/github/rgleason/testplugin_pi/77/workflows/fce8f355-6e8f-4307-8c33-5f964616a65a/jobs/469

Trusty script: https://github.com/rgleason/testplugin_pi/blob/master/ci/circleci-build-trusty.sh
PluginPackage.cmake  https://github.com/rgleason/testplugin_pi/blob/master/cmake/PluginPackage.cmake

I don't know if this is a new problem or one created by use of ninja.  Maybe an "if"  trusty don't ninja would work?

**Comment by bdbcat** [comment]
Rick...
This is a new problem, not caused by use of ninja.
You might try to "rerun" that particular job.

**Comment by rgleason** [comment]
That worked. I guess I should always rerun even when it is a permissions issue. Thanks.
