### ISSUE TITLE
Plugins:  Squiddio_pi  Branch:frontend1  fails

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#85]
https://github.com/rgleason/squiddio_pi/tree/frontend1

https://app.circleci.com/pipelines/github/rgleason/squiddio_pi/284/workflows/a57b41a1-41fe-4d4e-8600-f6781f6971bf/jobs/1290
These are identical to oesenc_pi
- [circleci-build-flatpak.sh](https://github.com/rgleason/squiddio_pi/blob/frontend1/ci/circleci-build-flatpak.sh)  
- [circleci-uload-flatpak.sh](https://github.com/rgleason/squiddio_pi/blob/frontend1/ci/circleci-upload-flatpak.sh)

https://app.circleci.com/pipelines/github/rgleason/squiddio_pi/284/workflows/a57b41a1-41fe-4d4e-8600-f6781f6971bf/jobs/1290

```
+ sudo ls -la squiddio_pi-flatpak-1.3.1.4
ls: cannot access 'squiddio_pi-flatpak-1.3.1.4': No such file or directory
Exited with code exit status 2
```

**Comment by rgleason** [comment]
In the upload error report  this is one of the files listed:

`drwxr-xr-x  4 root     root        4096 Apr 16 16:10 oesenc_pi-flatpak-1.3.1
`
I should be  "squiddio_pi" , 

I have checked  org.opencpn.OpenCPN.Plugin.squiddio.yaml and that is all squiddio.
In Cmakelists.txt Line 47     PROJECT(squiddio_pi)

**Comment by rgleason** [comment]
Needed to change this line in CMakeLists.txt to use the Verbose_name (my line 283)

        COMMAND ${TAR}
            -czf ${PKG_NVR}_${PKG_TARGET_NVR}.tar.gz
            --transform 's|.*/files/|${VERBOSE_NAME}-flatpak-${PACKAGE_VERSION}/|'
            ${CMAKE_CURRENT_BINARY_DIR}/app/files
    )
    return ()
endif()

I assume this will fix it.

**Comment by rgleason** [comment]
Well, it fixed something but there is still a problem.

```
+ sudo tar xf /home/circleci/project/build/squiddio_pi-1.3.1-4_flatpak-18.08.tar.gz
+ sudo ls -la
drwxr-xr-x  6 root     root        4096 Apr 16 23:23 .
drwxrwxr-x 16 circleci circleci    4096 Apr 16 23:19 ..
drwxr-xr-x  4 root     root        4096 Jan  1  1970 app
-rw-r--r--  1 root     root       13513 Apr 16 23:20 CMakeCache.txt
drwxr-xr-x  6 root     root        4096 Apr 16 23:20 CMakeFiles
-rw-r--r--  1 root     root        1485 Apr 16 23:20 cmake_install.cmake
-rw-r--r--  1 root     root        4560 Apr 16 23:20 Makefile
-rw-rw-r--  1 root     root         101 Apr 16 23:20 pkg_version.sh
drwxr-xr-x  3 root     root        4096 Apr 16 23:23 root
drwxr-xr-x  4 root     root        4096 Apr 16 23:23 squiddio-flatpak-1.3.1
-rw-r--r--  1 root     root     5529684 Apr 16 23:23 squiddio_pi-1.3.1-4_flatpak-18.08.tar.gz
-rw-rw-r--  1 root     root        1150 Apr 16 23:23 squiddio-plugin-flatpak-18.08.xml
+ tar_dir_here=squiddio_pi-flatpak-1.3.1.4
+ sudo ls -la squiddio_pi-flatpak-1.3.1.4
ls: cannot access 'squiddio_pi-flatpak-1.3.1.4': **No such file or directory**

```

Is this reversed for some reason?
 squiddio_pi-1.3.1-4_flatpak-18.08.tar.gz

**Comment by bdbcat** [comment]
Rick...
There is a small bug in my script.  I will fix.
But meanwhile, if you change 'Release' from '4' to '0', your script should work.

**Comment by rgleason** [comment]
Many thanks. Would not have found that!  Will watch for it.

**Comment by rgleason** [comment]
Dave's repository:  https://github.com/bdbcat/oesenc_pi/commits/ci
