### ISSUE TITLE
Exception while testing Autopilot_route 0.4.11.2

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#862]
NOTE: I should preface all this with the note that the exceptions occurred when I "Imported Plugin" autopilot_route 0.4.11.2    Perhaps the Import Plugin feature is not working right.

Don't know if it is the PI or Opencpn,  most likely Autopilot_route.
Exception thrown at 0x726F7461 in opencpn.exe: 0xC0000005: Access violation executing location 0x726F7461.
![Screenshot (1330)](https://user-images.githubusercontent.com/2363959/229288571-f1266b04-6b48-4900-a724-d467d768b891.png)

**Comment by rgleason** [comment]
![Screenshot (1332)](https://user-images.githubusercontent.com/2363959/229288733-14f8939a-78f8-4b16-9df2-bab5aa956d09.png)

continuous loop between these two screens above.

**Comment by rgleason** [comment]
I then stopped debugging and closed VS.  Restarted VS and started debugging OpenCPN again.  The safe mode prompt came up, picked safe mode. Then there were other exceptions as below.
![Screenshot (1333)](https://user-images.githubusercontent.com/2363959/229289075-3da274f1-b045-4028-bdd4-9dbac66a7f1f.png)
![Screenshot (1334)](https://user-images.githubusercontent.com/2363959/229289082-3f5d2c99-62dc-435c-b411-4b837514d5e5.png)

![Screenshot (1335)](https://user-images.githubusercontent.com/2363959/229289091-813f74bf-fc2e-46de-b9d1-d130d202eb19.png)

I then closed VS again, and restarted VS and then Opencpn, picked safemode and it loaded without exceptions.

I then looked at the log file and attach it below. I did find this error:

```
07:45:35.611 MESSAGE plugin_loader.cpp:1187 PluginLoader: Loading PlugIn: C:\Users\fcgle\AppData\Local\opencpn\plugins\vdr_pi.dll
07:45:35.611 MESSAGE base_platform.cpp:271 PlugInManager: Using data dirs from: C:\Users\fcgle\AppData\Local\opencpn\plugins;C:\Users\fcgle\source\repos\OpenCPN\build\RelWithDebInfo\plugins
07:45:35.611 MESSAGE base_platform.cpp:290 Warning: no data directory found, using ""
07:45:35.611 MESSAGE icons.cpp:69 Loading toolbar icon: data\vdr_record_toggled.svg
07:45:35.611 MESSAGE base_platform.cpp:271 PlugInManager: Using data dirs from: C:\Users\fcgle\AppData\Local\opencpn\plugins;C:\Users\fcgle\source\repos\OpenCPN\build\RelWithDebInfo\plugins
07:45:35.611 MESSAGE base_platform.cpp:290 Warning: no data directory found, using ""
07:45:35.611   ERROR ffile.cpp:57 can't open file 'data\vdr_panel_icon.png' (error 3: The system cannot find the path specified.)
07:45:35.611   ERROR ffile.cpp:57 can't open file 'data\vdr_panel_icon.png' (error 3: The system cannot find the path specified.)
07:45:35.611   ERROR image.cpp:2678 Failed to load image from file "data\vdr_panel_icon.png".
07:45:35.611 WARNING vdr_pi.cpp:87 VDR panel icon has NOT been loaded
```

plus the missing tide data error.

[opencpn5.log.txt](https://github.com/OpenCPN/plugins/files/11129530/opencpn5.log.txt)

I am going to reinstall VDR next.

**Comment by rgleason** [comment]
But before doing that, all external plugins have green puzzles right now.
![Screenshot (1336)](https://user-images.githubusercontent.com/2363959/229289710-3d4d153a-48a1-49a5-929e-6da5db5477d1.png)

VDR shows as -1.0.0  version and has "TBD" as a button where normally "Reinstall"
Many other plugins show TBD too, including, Shipdriver, Tactics, UKtides, Watchdog,
but Weatherfax and Weather_routing do not, they show "Reinstall"

![Screenshot (1338)](https://user-images.githubusercontent.com/2363959/229290025-fdf770b2-6a37-4a94-8cf4-ffaacc7c6654.png)

![Screenshot (1340)](https://user-images.githubusercontent.com/2363959/229290032-1917e671-4ca0-49fc-9a72-86acee2e9a07.png)

**Comment by rgleason** [comment]
I then noticed that UKtides had  a "TBD" and also had a version number of  -1.0.0  similar to VDR, so I tried uninstalling that. It uninstalled with a message, success.  The VDR plugin then changed into a brown box and no longer had "TBD" and had "Reinstall"  so I reinstalled it, now it looks right.

![Screenshot (1345)](https://user-images.githubusercontent.com/2363959/229290447-6326efab-1d30-4115-a1f7-6ede875503e6.png)

![Screenshot (1346)](https://user-images.githubusercontent.com/2363959/229290451-f284c756-5862-427a-95e6-ccdec6074cd4.png)

**Comment by rgleason** [comment]
However there are still green puzzles in the PI list.

**Comment by rgleason** [comment]
After struggling to get the TP1.0.230 upgrade to autopilot_route_pi working properly, it started working on Standard XTE setting, at a speed factor of 12 (which is too fast for testing really), then it went off track and my next restart of the testing just failed.   I don't know what caused it to start working so nicely and then fail.  Perhaps a clean environment helped.
![Screenshot (1351)](https://user-images.githubusercontent.com/2363959/229291902-27f33ca9-a1df-4a8c-a402-39ddc64f4384.png)

![Screenshot (1352)](https://user-images.githubusercontent.com/2363959/229291904-9dc94aba-9e4b-494e-b04c-394ca87a1ff2.png)

**Comment by rgleason** [comment]
At least it works sometimes.  (:-)

**Comment by rgleason** [comment]
NOTE: I should preface all this with the note that the exceptions occurred when I "Imported Plugin" autopilot_route 0.4.11.2    Perhaps the Import Plugin feature is not working right.

**Comment by leamas** [comment]
This is a great bug report, but in the wrong place: this repo is about the catalog and related tools. It is not a general place to file bugs against plugins.

The correct place to file this is actually your own repo  https://github.com/rgleason/autopilot_route_pi or perhaps Sean's upstream repo. You could for example file a very simple bug with a link to this.

**Comment by rgleason** [comment]
Well, at the time I also suspected PIM was playing games too.

**Comment by rgleason** [comment]
I guess you want this closed and think that the PIM issues are resolved.
