### ISSUE TITLE
GPS-Odometer_pi  unresolved external symbol "bool_ cdecl ParseN2K

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#876]
Lennart and I are having great difficulty getting the windows version to build, when the linux builds all work.

The error is  error LNK2019: unresolved external symbol "bool __cdecl ParseN2kPGN129029(class std::vector<unsigned char,class std::allocator
```
Creating library C:/Users/fcgle/source/GPS-Odometer_pi/build/RelWithDebInfo/gpsodometer_pi.lib and object C:/Users/fcgle/source/GPS-Odometer_pi/build/RelWithDebInfo/gpsodometer_pi.exp
odometer_pi.obj : error LNK2019: unresolved external symbol "bool __cdecl ParseN2kPGN129029(class std::vector<unsigned char,class std::allocator<unsigned char> > &,unsigned char &,unsigned short &,double &,double &,double &,double &,enum tN2kGNSStype &,enum tN2kGNSSmethod &,unsigned char &,double &,double &,double &,unsigned char &,enum tN2kGNSStype &,unsigned short &,double &)" (?ParseN2kPGN129029@@YA_NAAV?$vector@EV?$allocator@E@std@@@std@@AAEAAGAAN333AAW4tN2kGNSStype@@AAW4tN2kGNSSmethod@@13331423@Z) referenced in function "private: void __thiscall odometer_pi::HandleN2K_129029(class ObservedEvt)" (?HandleN2K_129029@odometer_pi@@AAEXVObservedEvt@@@Z) [C:\Users\fcgle\source\GPS-Odometer_pi\build\gpsodometer_pi.vcxproj]
```

The thread we are using is under Testplugin https://github.com/jongough/testplugin_pi/issues/300#issuecomment-1510002263

If anyone can help with this, it would be appreciated.

**Comment by rgleason** [comment]
Note that Appveyor is using wxWidgets 3.1.2

**Comment by jongough** [comment]
Appveyor with VS2017 is using wxwidgets 3.1.2 and with VS2022 wxwidgets 3.2.1 . As this is a template process if it is needed that only 3.2.1 will work then then change the two lines 42 & 43 to reflect this as well as lines 57 & 58.

**Comment by rgleason** [comment]
@bdbcat  What version of wxWidgets should O58 plugins be using?  Since we are going to be rebuilding all the TP plugins should we use the same version as OpenCPN 5.8?   Which one is that?  wxWidgets 3.2.2 or 3.2.2.1?

**Comment by bdbcat** [comment]
Yes.
Though as a practical matter, 3.2.2 is functionally equivalent for a plugin build,  There is no ABI difference.
