### ISSUE TITLE
Round trip Plugins o562 -->o58 --> o562 testing

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#879]
The following plugins pass the test:

- weatherfax
- ais-vd
- autopilot_route
- autotrackraymarine
- calculator
- cel nav
- dashboard_tactics  no o58 version, but there is a message.
- dashboardSK  no o562 but there is a message
- DR

The following plugins do not pass the test:
- canadiantides  0562 checksum error.
-

**Comment by rgleason** [comment]
Sorry, this is an uncompleted test that Bdbcat wanted done to check all the plugins when we first had 5.8.   I haven't finished it.  It was to see if there were bugs or hangups when changing between versions.  

I suppose this has been worked on since then.  Should it be closed.?

**Comment by bdbcat** [comment]
Close it, please.
