### ISSUE TITLE
gps-odometer   github nodes action problem.

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#924]
Since this PR 
[GPS Odometer v0.7.0.4 #843](https://github.com/OpenCPN/plugins/actions/runs/4883870390)

which the error shows a link to 
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

This appears to be due to some actions script running on opencpn/plugins which is using "node12"?????
This appears to have  caused Lennart difficultybuilding and pushing the plugin to opencpn/plugins.

Can you shed any light on this problem from the Opencpn side?

Two weeks ago Lennart built  version 0.7.0.3 and all builds compiled and deployed successfully.
https://github.com/LennartG-Sve/GPS-Odometer_pi/commits/master

When he tried to make a PR to opencpn/plugins, his PR was rejected due to this node problem, using node 12 instead of node 16.  Can you please shed some light on this strange situation?

**Comment by LennartG-Sve** [comment]
Further info:
 The erroneous version is v0.7.0.4 that is still checked for all tests on upcoming releases as the test is executed on all available releases in the compare page. It need be removed before any further PR can be generated and I appear to have no way to do it.
It is nowhere in my local or remote directories, as far as I can find. 

The 'compares' to be removed are seen om 'https://github.com/OpenCPN/plugins/compare/master...LennartG-Sve:plugins:master'. Then I may generate a new PR, not before.
The committed v0.7.0.4 and v0.7.0.5 are found at 'https://github.com/OpenCPN/plugins/actions/workflows/CI_Pull.yml?page=3' as  Pull request #886 and #887 while the others are not listed as PR's, this as the PR was not fully generated.

**Comment by bdbcat** [comment]
Not sure what is going on here.
But the node12->node16 is a simple warning, probably not the source of the trouble.
I think you should cancel the PR, and start over with clean fetch of master catalog.

**Comment by rgleason** [comment]
@LennartG-Sve  I agree with Dave.
