### ISSUE TITLE
Make .github/workflows/cronjob.yml independent of .git and send error reports to maintainers only

### ISSUE THREAD

**Issue by LennartG-Sve** [OpenCPN/plugins#928]
Reorganized my R&D structure and regenerated git plugins including fetch and pull OpenCPN/plugins, this to ensure I was fully updated.

Since then I'm getting the nightly check result for all plugin checks. The latest check listed checksum errors for 'metadata/CanadianTides' and 'metadata/ais'. Those are of absolutely no interest to me, just spam.
This is what I got:

---------------------------------------------- 
metadata/CanadianTides-v0.6.0-debian-10.xml: CanadianTides-v0.6.0_debian-10-x86_64.tar.gz
        metadata checksum: '8e2247049c17505e976d17b8deafb667d3271d170ccd19ebeee6f43033ebe5fa'
        computed checksum: '8b107ab5b6e73ad7524164c9cb041d93ad5b52f6121d056eb0e8c13338978a01'
metadata/CanadianTides-v0.6.0-debian-11.xml: CanadianTides-v0.6.0_debian-11-x86_64.tar.gz
        metadata checksum: '4e800568e616b88c997e53a0051927ec9a667a3366c44f75c61c52ec06ddd57a'
        computed checksum: '82c798cb76a458944b9082cd965794e7a9b40f9873706f0dd949f8fb478cdc7f'
metadata/CanadianTides-v0.6.0-msvc-10.0.14393.xml: CanadianTides-v0.6.0_msvc-10.0.14393-win32.tar.gz
        metadata checksum: '4263f754fe1a8ed92a6c6b5497dbf3511da88a67a45f65c744999a208886c634'
        computed checksum: '0278b104ad036f3882d796ff4a2c36b55332dcf9c44c2c0f3a24968770e0f951'
metadata/CanadianTides-v0.6.0-ubuntu-18.04.xml: CanadianTides-v0.6.0_ubuntu-18.04-x86_64.tar.gz
        metadata checksum: 'add40b0a0b92d55271c03216102d8cf46afb7664931ae41006581fa771dacb93'
        computed checksum: '4d834bd0573261ad0b08a6a46a2c4ba1a380e73efa8e287027968acd37e8b2e9'
metadata/CanadianTides-v0.6.0-ubuntu-gtk3-18.04.xml: CanadianTides-v0.6.0_ubuntu-gtk3-18.04-x86_64.tar.gz
        metadata checksum: 'c20a5d876cd5f3502ca6f0825ead54b5dd661b2f3be78c9304e53eb321e32e77'
        computed checksum: 'e83c21b886c085f7d7b2712c6715ee02c9b44a71ee2b119f27e3f265e253d4a8'
metadata/CanadianTides-v0.6.0-ubuntu-gtk3-20.04.xml: CanadianTides-v0.6.0_ubuntu-gtk3-20.04-x86_64.tar.gz
        metadata checksum: '49acb0c700dff37761f76cba5a3ddc01c434f9f566299ab597c22c522fd90782'
        computed checksum: '0ccbf8c41661a5acfee85f487ab01fba181def43a6eac7106891b12b623c7b99'
metadata/CanadianTides-v0.6.0-ubuntu-gtk3-A32-20.04.xml: CanadianTides-v0.6.0_ubuntu-gtk3-20.04-armhf.tar.gz
        metadata checksum: 'a74370d04203729db9899fb5b340c459ae953ad672aba639489ad4fcbfe5c67d'
        computed checksum: '29c2cc6fea9bff7ccafc13abee90152374552f68a102b5e623d37cc745bb5500'
metadata/ais-vd-1.8.2-android-arm64-A64-16.xml: ais-vd-1.8.2_android-arm64-16-arm64.tar.gz
        metadata checksum: '40a2fdb9677eb26d5e19fd57c29c94f4750be3ac8f030e5c7f3ae0fbf35be8d6'
        computed checksum: '6586884bfa1df070f572593670cbddecf5ecbcb2df49bb2ff3ee206901dca42f'
metadata/ais-vd-1.8.2-darwin-wx32-10.xml: ais-vd-1.8.2_darwin-wx32-10-x86_64.tar.gz
        metadata checksum: '1faea89195b87c21829d824ad3639840f190a864d6e5db7984a02da7dbcf918b'
        computed checksum: 'bac0635d208d98d1bf3eb5b935a1253702f01fe66c3eecf6951c43d53e448ba0'
metadata/ais-vd-1.8.2-debian-A32-11.xml: ais-vd-1.8.2_debian-11-armhf.tar.gz
        metadata checksum: '9bbd8196daa73951f8e56746c5deb11b038eb18abdde5913000259939b26b4db'
        computed checksum: '642a732a071388b4befb59fd9e9aa02d182562172ba3d65bc458fffde7def06a'

Error: Process completed with exit code 2.
---------------------------------------------- 

As far as I can see this is generated using a script 'plugins/.github/workflows/cronjob.yml' called from .git and in turn calling 'tools/check-metadata-urls metadata/*xml'. Although the check result could be very useful it raises two questions:

1/ Are the developer concerned getting this info? These messages has been there for some time now without getting fixed.
2/ Could it be possible to use e.g. information in 'CMakeLists.txt' to ensure only the correct developer get this information. Others have no use nor any interest in the information.

**Comment by LennartG-Sve** [comment]
Rick, suppose the idea is to use everything as set up by the plugin developers. That way I can easily do a compare to verify everything is ok. 
I assume you have your own 'git init' and have not done a fetch and pull sequence in plugins since then, that is what I had before as well. Such a setup will omit these checks that, if initiated properly, could prove useful.

**Comment by bdbcat** [comment]
Lennart,
"This is what I got:"
Where/when in your workflow did you see this output?

**Comment by LennartG-Sve** [comment]
Dave, 
that was the nightly check from this morning and I've seen the same every day since I set it up just over a week ago. 
It arrives by email to 'LennartG-Sve/plugins <plugins@noreply.github.com>' which I then get in my email inbox as 'https://github.com/LennartG-Sve/plugins/actions/runs/5528075324'.
I receive a new message every morning as 'plugins/.git' calls 'plugins/.github/workflows/cronjob.yml', then calling 'plugins/tools/check-metadata-urls metadata/*xml'

**Comment by rgleason** [comment]
Lennart,
Actually I do

- git pull upstream master    to make my local files identical to upstream (opencpn/plugins)
- git push origin master        to make my remote files identical to origin  (rgleason/plugins)

Also I believe my plugins/tools is identical to opencpn/plugins
and my plugins/.github/workflows is identical to opencpn/plugins/.github/workflows

Do you have notices turned on or something?

**Comment by LennartG-Sve** [comment]
Rick, this is called thru .git and the reason why yours and mine .git differs is another discussion. The point here is that:

1/ It is a good thing that this test is executed

2/ The test should not be called from .git as maintainers may have a differently generated .git and hence not running the test. 

3/ The test should be initiated directly through cron or any other suitable way for e.g. windows, as applicable.

3/ The test result should be sent only to the respective plugin maintainer and not to everybody. This could e.g. be controlled thru a variable in CMakeLists.txt.

**Comment by LennartG-Sve** [comment]
**@leamas** , good idea even if I appreciate the test and think it should be updated as suggested in the steps above. The test is useful and apparently needed.
In the meantime I will likely follow your advise, just have to find and install Github UI first  ;-) .

**Comment by rgleason** [comment]
I've checked as Alec suggested.  Plugins > Settings > Actions > General > Actions Permissions > "Disable Actions"

**Comment by LennartG-Sve** [comment]
**@leamas** : Thanks for the suggestion, commented out the 'run' line in cronjob.yml, no more messages (and no test executed).
Also changed the subject line to something more general reflecting the suggested alterations.

**Comment by leamas** [comment]
@LennartG-Sve : Since it is possible to just disable the tests in the github web ui, I actually don't see any need to change anything in the cronjob. This has worked fine for other users, not just Rick.

Given this, do you actually still see anything which needs to be changed?

**Comment by rgleason** [comment]
```
I've checked as Alec suggested. Plugins > Settings > Actions > General > Actions Permissions > "Disable Actions"
I'll guess it has always been that way because it is a fork.
```

This can be closed now. IMHO

**Comment by rgleason** [comment]
Good!
