### ISSUE TITLE
No plugin for 2019 iMac, latest  OS, with opencpn v 5.6.2

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#951]
David from starpath reports this.
2019  iMac, OpenCPN 5.6.2

Rick writes:
Not clear if the missing plugin is weatherfax, weather_routing, or all of the plugins

Can someone with a Mac please check if they work or even appear?  I do not have a Mac.

![Mac-Problem](https://github.com/OpenCPN/plugins/assets/2363959/91b35056-3031-406e-b2af-0f2dca6dfc13)

**Comment by rgleason** [comment]
I wrote in response to his questions:

Weatherfax should be available for your Mac, I am very surprised that it is not and this is the first that I have heard of that... but it can and should be fixed if there is a problem.

Have you updated the PIM (Plugin Manager) Catalog?  Options > PI at the bottom click on the button?

What macOS do you have?  We did a really big update and cleanup of weatherfax a little while ago and last I used it it was working very well.  Also I am going to be updating all the TP FE2 plugins over the next couple weeks, after about 2 months.  The plugin system is getting better and better, to the extent that hopefully we can focus more on bugs and RFE.

One of these tarballs should work for you

https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=1.9.58.0+darwin

**Comment by starpathnav** [comment]
I have made a short private video explaining what i was trying to say earlier, but not clearly.  again, i am likely making some stupid mistake, but this at least shows what i refer to.. namely how does someone visiting opencpn.com or using the mac version know there is a weatherfax plug in.  please see https://youtu.be/KwUo1bdhsSo  i am standing by to be embarrassed by missing something basic.

**Comment by rgleason** [comment]
Dave,

Your review of PIM (Plugin Manager) installation of plugins for Windows is exactly right.

Just so you understand, when you are showing the way Windows works, and you go to the github releases, those releases are all older builds using the deprecated process for installing plugins (ie using exe files for windows).

It should work the same way for Mac and there should be a box container shown for Mac that you can click on and select a file to download. 

We are missing something on our side I think.
For the time being you can download a mac weatherfax plugin from cloudsmith until this gets resolved. Find the cloudsmith opencpn weatherfax-prod repository and search for "1.9.60.0 darwin tarball"

https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=1.9.60.0+darwin+tarball

Let us know how that works please.

BTW, I have checked the opencpn/plugins/ocpn-plugins.xml file and both versions for "Darwin" exist.
See this screenshot.

![weatherfax](https://github.com/OpenCPN/plugins/assets/2363959/a4c5e54e-3a7d-4fea-8ebe-cac5a4bf7aea)

So I don't understand what the problem is.

**Comment by bdbcat** [comment]
Dave...
There are issues with current WeatherFAX plugin on OpenCPN Version v5.6.2/Mac.
These are all fixable, but...
Is there any particular reason that you (or your students) want or need to stay on OpenCPN V 5.6.2?
Version 5.8.4 is fully stable, with much improved performance and plugin support.

Dave

**Comment by rgleason** [comment]
Dave, do you think this O5.6.2 problem runs through all TP plugins? If so, this is the first time we have heard of the problem.

**Comment by rgleason** [comment]
At some point, it would be nice to correct it, so we can do a full run of O5.6.2 and O5.8 with all TP Plugins, before we stop providing O5.6.2 plugins which I think should be pretty soon.

**Comment by starpathnav** [comment]
Hi Dave

Thanks for the note.  I knew i must be doing something stupid, and that someone would tell me!

I have downloaded the new version and indeed there is the plugin as advertised.

I will tell our students today to update if they have not.

… and as soon as i can i will check to see if what i have working on my home mac version plugin will work with the new build.  I just added a few of the ASCAT files to the Navy file i have at home.

________

If there is time and interest to add these based on what we have done for Google Earth, then i will be glad to answer questions about it.  I have yet to make the videos to show how powerful the data are, so i can understand waiting to see that. Hopefully in Sept.

I have been delayed a bit as we are making a shorter book on ENC (ENC Essentials) that is easier to digest than our full text on use of electronic charts. This will be just about ENC. Will send you a copy when done.

Thanks again.

— david

David Burch, PhD, FRIN
Starpath School of Navigation <https://www.starpath.com/>
Seattle, WA

**Comment by rgleason** [comment]
@starpathnav   David Burch before upgrading to O5.8 on your home machine can you try installing ocpn_draw version 1.8.28.2 to see if it works?  It should be in the master catalog.

**ocpn_draw metadata for O5.6.2**
```
<name> OCPN Draw </name>
<version> 1.8.28.2 </version>
<api-version> 1.16 </api-version>
...
<target>darwin</target>
<build-target>darwin</build-target>
<build-gtk></build-gtk>
<target-version>11.4</target-version>
<target-arch>x86_64</target-arch>
<tarball-url>
https://dl.cloudsmith.io/public/opencpn/ocpn_draw-prod/raw/names/ocpn_draw_pi-1.8.28.2-darwin-x86_64-11.4-macos-tarball/versions/v1.8.28.2/ocpn_draw_pi-1.8.28.2-darwin-x86_64-11.4-macos.tar.gz
</tarball-url>
```

**weatherfax metadata for O5.6.2**
```
<name> WeatherFax </name>
<version> 1.9.60.0 </version>
<api-version> 1.16 </api-version>
...
<target>darwin</target>
<build-target>darwin</build-target>
<build-gtk></build-gtk>
<target-version>11.4</target-version>
<target-arch>x86_64</target-arch>
<tarball-url>
https://dl.cloudsmith.io/public/opencpn/weatherfax-prod/raw/names/weatherfax_pi-1.9.60.0-darwin-x86_64-11.4-macos-tarball/versions/v1.9.60.0/weatherfax_pi-1.9.60.0-darwin-x86_64-11.4-macos.tar.gz
```
They appear to be the same.  build-target "darwin"

**Comment by rgleason** [comment]
Here are some metadata for Shipdriver Template plugins

@starpathnav  does DR_pi  work?
```
<name> DR </name>
  <version> 4.0.0+622.v4.0.0 </version>
  <api-version> 1.16 </api-version>
  <target>darwin-wx315</target>
  <target-version>10.13.6</target-version>
  <target-arch>x86_64</target-arch>
  <tarball-url> https://dl.cloudsmith.io/public/opencpn/dr-prod/raw/names/DR-v4.0.0-darwin-wx315-10.13.6-tarball/versions/4.0.0+622.v4.0.0/DR-v4.0.0_darwin-wx315-10.13.6-x86_64.tar.gz </tarball-url>
  <tarball-checksum> 3ef1c29a18f5b06fe687cbd1e7c9d15b6f3c756414ee2d749d5ab3cb04622d0d </tarball-checksum>

```

@starpathnav   does Earthexplorer work?

```
  <name> EarthExplorer </name>
  <version> v1.0.0 </version>
  <api-version> 1.16 </api-version>
...
  <target>darwin-wx315</target>
  <target-version>10.13.6</target-version>
  <target-arch>x86_64</target-arch>
  <tarball-url> https://dl.cloudsmith.io/public/opencpn/earthexplorer-prod/raw/names/EarthExplorer-v1.0.0-darwin-wx315-10.13.6-tarball/versions/v1.0.0/EarthExplorer-v1.0.0_darwin-wx315-10.13.6-x86_64.tar.gz </tarball-url>
  <tarball-checksum> 2ca5b08647a2ed7c5a9ad15fd835c5436a6f6edce9416325ee650537646fc810 </tarball-checksum>
```

**Comment by rgleason** [comment]
I guess we need to use

<target>darwin-wx315</target>

and to use wxWidgets 3.1.5 to build the plugins.  (check this)

**Comment by rgleason** [comment]
Looking into this further,  
`C:\Users\fcgle\source\testplugin_pi\ci\circleci-build-macos.sh
`
Line 25 - 32
```
else
    echo "Building for WXVERSION 312";
    WX_URL=https://download.opencpn.org/s/rwoCNGzx6G34tbC/download
    WX_DOWNLOAD=/tmp/wx312B_opencpn50_macos109.tar.xz
    WX_EXECUTABLE=/tmp/wx312B_opencpn50_macos109/bin/wx-config
    WX_CONFIG="--prefix=/tmp/wx312B_opencpn50_macos109"
    MACOSX_DEPLOYMENT_TARGET=10.9
fi
```
I am a little confused now, are we supposed to be using wxWidgets 3.1.2  or 3.1.5 (as in shipdriver?)

Did TP get stomped on again by SD approach here?

**Comment by rgleason** [comment]
Regarding changing the "target"
```
Search "darwin" (2 hits in 1 file of 21 searched)  in CMAKE
  C:\Users\fcgle\source\testplugin_pi\cmake\PluginSetup.cmake (2 hits)
	Line  98:     set(PKG_BUILD_TARGET "darwin")
	Line 100:         set(PKG_TARGET "darwin-wx$ENV{WX_VER}")
```

**PluginSetup line 97-104**

```
elseif(APPLE)
    set(PKG_BUILD_TARGET "darwin")
    if("$ENV{WX_VER}" STREQUAL "32")
        set(PKG_TARGET "darwin-wx$ENV{WX_VER}")
    else()
        set(PKG_TARGET "${PKG_BUILD_TARGET}")   <--- LINE 102
    endif()
    execute_process(COMMAND "sw_vers" "-productVersion" OUTPUT_VARIABLE PKG_TARGET_VERSION)
```

Suggested change:
LINE 102   set(PKG_TARGET "darwin-wx315")  

Is this correct?  or should it be "darwin-wx312")???

**Comment by rgleason** [comment]
Related Issue:  https://github.com/OpenCPN/plugins/issues/752

**Comment by bdbcat** [comment]
Target must be "darwin-wx315".  That is the value hard-coded into Production OCPN-5.6.2 for Mac.

**Comment by bdbcat** [comment]
If you make a rebuild of WeFAX_pi in CCI, I can test by import immediately on Mac.  Let me know...

**Comment by rgleason** [comment]
Ok great,  One question. Is use of wxWidget 312 ok?
https://github.com/OpenCPN/plugins/issues/951#issuecomment-1701933624

    echo "Building for WXVERSION 312";
    WX_URL=https://download.opencpn.org/s/rwoCNGzx6G34tbC/download
    WX_DOWNLOAD=/tmp/wx312B_opencpn50_macos109.tar.xz
    WX_EXECUTABLE=/tmp/wx312B_opencpn50_macos109/bin/wx-config
    WX_CONFIG="--prefix=/tmp/wx312B_opencpn50_macos109"

**Comment by bdbcat** [comment]
Let's try it.

**Comment by rgleason** [comment]
Have pushed the change to that one line  
LINE 102 set(PKG_TARGET "darwin-wx315")

Testplugin v1.0.253.2  https://github.com/rgleason/testplugin_pi
made a format mistake, fixed it.

Dave, have pushed it should land in prod and appear here when it is done.

https://cloudsmith.io/~opencpn/repos/testplugin-prod/packages/?q=1.0.253.2+darwin

Thank you Dave. I've got to hit the hay now. You should too. (:-))

**Comment by bdbcat** [comment]
Built OK, but could not load.
So we need to try using wx315.

Please change:
ci/circleci-build-macos.sh, clause at line 26

    echo "Building for WXVERSION 315";
    WX_URL=https://download.opencpn.org/s/MCiRiq4fJcKD56r/Download
    WX_DOWNLOAD=/tmp/wx315_opencpn50_macos1010.tar.xz
    WX_EXECUTABLE=/tmp/wx315_opencpn50_macos1010/bin/wx-config
    WX_CONFIG="--prefix=/tmp/wx315_opencpn50_macos1010"
    MACOSX_DEPLOYMENT_TARGET=10.10

**Comment by rgleason** [comment]
Testplugin and Weatherfax fix for MacOS darwin-wx315

https://github.com/rgleason/testplugin_pi  
build-macos just started running after 44min https://github.com/rgleason/testplugin_pi
[v1.0.253.3 Darwin Tarball](https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=1.9.62.0+darwin+tarball)

https://github.com/rgleason/weatherfax_pi 
Well, MacOS failed https://github.com/rgleason/weatherfax_pi/runs/16418887151
Also here https://app.circleci.com/pipelines/github/rgleason/weatherfax_pi/357/workflows/24bbdd51-567c-4cbf-b18a-15ec46b8e716/jobs/4955
[v1.9.62.0  Darwin Tarball](https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=1.9.62.0+darwin+tarball+)

NOTE:  Weatherfax_pi  Jammy did not build so I "Reran with SSH" It appears to have finished, now it is waiting for something from me I think.  How do I get this to complete and deploy?

```
Use the same SSH public key that you use for your VCS-provider (e.g., GitHub).
ED25519 key fingerprint of the host is
  SHA256:KFrEkXUVFpnSlA9DLjzC0lOq5QlDcL6wqS1ud594FxQ
  MD5:f8:f7:22:fc:9a:8e:f9:bc:6b:9c:ee:0d:26:7e:86:df

rsa-sha2-512 key fingerprint of the host is
  SHA256:zP+Zj4EOXEhqz1jNF/ijZQ+BfUcWEgqPKiJ7XeXJPbs
  MD5:4b:d0:fd:7f:e3:b9:5b:05:58:01:e3:a4:14:c8:49:2d

rsa-sha2-256 key fingerprint of the host is
  SHA256:zP+Zj4EOXEhqz1jNF/ijZQ+BfUcWEgqPKiJ7XeXJPbs
  MD5:4b:d0:fd:7f:e3:b9:5b:05:58:01:e3:a4:14:c8:49:2d

RSA key fingerprint of the host is
  SHA256:zP+Zj4EOXEhqz1jNF/ijZQ+BfUcWEgqPKiJ7XeXJPbs
  MD5:4b:d0:fd:7f:e3:b9:5b:05:58:01:e3:a4:14:c8:49:2d

This box will stay up for 2h0m0s, or until 10m0s passes without an active SSH session.

```

**Comment by bdbcat** [comment]
Please correct my trivial typo:

    WX_URL=https://download.opencpn.org/s/MCiRiq4fJcKD56r/download

Note lower case "d" in "download"

**Comment by rgleason** [comment]
Have pushed that as Testplugin  1.0.253.4  links would be the same as above. Still building.

**Comment by rgleason** [comment]
@bdbcat  @starpathnav  OpenCPN 5.6.2 version of Testplugin_pi v 1.0.253.4 built successfully.
https://cloudsmith.io/~opencpn/repos/testplugin-prod/packages/?q=1.0.253.4+darwin+tarball
You can download the tarball and test by using Options>PI>Import Plugin and then install and enable.

**Comment by bdbcat** [comment]
Testplugin_pi 1.0.253.4 works fine on MacOS O562.
Good job!
weFAX next?

**Comment by rgleason** [comment]
Yes,  have pushed it here as v1.9.63.0  https://github.com/rgleason/weatherfax_pi
When/if built it will show in Cloudsmith opencpn/weatherfax-prod/  
with a search of [1.9.63.0 darwin tarball](https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=1.9.63.0+darwin+tarball)

https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=1.9.63.0+darwin+tarball

**Comment by bdbcat** [comment]
And Weatherfax_pi imports, loads and runs fine on O562/MacOS.
Thanks for the quick work,
Dave

**Comment by rgleason** [comment]
Dave, when I push the metadata to opencpn/plugins  I get an error
https://github.com/OpenCPN/plugins/actions/runs/6058099950/job/16439910971?pr=992

```
 * [new branch]        master     -> upstream/master
Processing file: metadata/weatherfax_pi-1.9.63.0-darwin-wx315-x86_64-11.4-macos.xml
metadata/weatherfax_pi-1.9.63.0-darwin-wx315-x86_64-11.4-macos.xml:17: element target: Schemas validity error : Element 'target': [facet 'enumeration'] The value 'darwin-wx315' is not an element of the set {'all', 'android-arm64', 'android-arm64-v8a', 'android-armeabi-v7a', 'android-armhf', 'darwin', 'darwin-arm64', 'darwin-wx32', 'debian-armhf', 'debian-wx32-armhf', 'debian-gtk3-armhf', 'debian-x86_64', 'debian-wx32-x86_64', 'debian-arm64', 'debian-wx32-arm64', 'flatpak-aarch64', 'flatpak-x86_64', 'mingw', 'mingw-x86_64', 'msvc', 'msvc-64', 'msvc-wx32', 'raspbian-armhf', 'ubuntu-armhf', 'ubuntu-gtk3-armhf', 'ubuntu-gtk3-x86_64', 'ubuntu-x86_64', 'ubuntu-wx32-x86_64'}.
metadata/weatherfax_pi-1.9.63.0-darwin-wx315-x86_64-11.4-macos.xml fails to validate
..
```
The important stuff

```
<target>darwin-wx315</target>
<build-target>darwin</build-target>
<build-gtk></build-gtk>
<target-version>11.4</target-version>
<target-arch>x86_64</target-arch>
<tarball-url>
https://dl.cloudsmith.io/public/opencpn/weatherfax-prod/raw/names/weatherfax_pi-1.9.63.0-darwin-wx315-x86_64-11.4-macos-tarball/versions/v1.9.63.0/weatherfax_pi-1.9.63.0-darwin-wx315-x86_64-11.4-macos.tar.gz
</tarball-url>
<info-url> https://opencpn.org/OpenCPN/plugins/weatherfax.html </info-url>
</plugin>


```


[weatherfax_pi-1.9.63.0-darwin-wx315-x86_64-11.4-macos.xml.txt](https://github.com/OpenCPN/plugins/files/12503930/weatherfax_pi-1.9.63.0-darwin-wx315-x86_64-11.4-macos.xml.txt)

**Comment by rgleason** [comment]
What the heck??   "darwin" is allowed, but there is no darwin-wx315!!!   
'android-armhf', **'darwin'**, 'darwin-arm64', 'darwin-wx32', 'debian-armhf',

**Comment by rgleason** [comment]
So I've got to change the target back to "darwin" now and it will work and be accepted?
Is it going to load?

Just asking if there parity in the "Import Plugin" with the opencpn/plugins filter?

**Comment by rgleason** [comment]
Well, I've changed  the "target" back to darwin now
https://github.com/rgleason/weatherfax_pi

**Comment by rgleason** [comment]
Dave, can you please try weatherfax 1.9.64.0 for macos????
https://github.com/rgleason/weatherfax_pi
Find it here
https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=1.9.64+darwin+tarball

**Comment by bdbcat** [comment]
Rick...
The target must be "darwin-wx315".  That is hard coded in OCPN562.  No other target will work.
I will fix the plugin repo to accept this target.  Then you may push the original changes with "darwin-wx315".
Please stand by.

**Comment by bdbcat** [comment]
OK, that is done.
A push using "darwin-wx315" should now be accepted.
Sorry for the mixup.

**Comment by rgleason** [comment]
What??  I have to redo all of that now?  They are using "Darwin" now.
Testplugin
Weatherfax
Watchdog

**Comment by bdbcat** [comment]
I have to redo all of that now?
Yes.  Sorry.

**Comment by rgleason** [comment]
Where do I  "Check MacOS on O562?
I looked at Shipdriver output for an example.  What has been happening to Shipdriver MacOS all this time?
On shipdriver the target was "darwin-wx315" so that is what I used originally.
Then the damn plugin checking only accepted "darwin"  so I changed all 3 plugins back to "darwin"
What has been happening to Shipdriver all this time when they push?

**Comment by bdbcat** [comment]
Please just do one, and let me test it before the others.
We will come back to shipdriver....

**Comment by rgleason** [comment]
Dave, I've made the change back to target darwin-wx315 for all three. It will take awhile to build them all, will push this afternoon.
Sorry got a little frustrated.

**Comment by bdbcat** [comment]
OK, I'll be back online around 16:00

**Comment by rgleason** [comment]
I think Shipdriver just builds O5.8 plugins now. That is why

**Comment by bdbcat** [comment]
Weatherfax, watchdog, testplugin for "darwin-wx315" all OK now for MacOS O562.
Ready for close...

**Comment by rgleason** [comment]
https://github.com/rgleason/testplugin_pi/commit/0e02c36f2f785c760d95eb4176e49ae6b286276c
