### ISSUE TITLE
Circleci (TP) failures can be "Rerun from failure" 

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#963]
I don't know if these failures are due to overloading the system, or if they are related to the code in the builds, but I am seeing errors in the builds for windows, macos, ubuntu and debian in addition to androids.
I tried rerunning with an SSH restart but that runs and then wants somethng from me I think.
Then I picked another build and was able to select rerun from start, which rebuilds everything, in this case it appears to be completing successfully.

These failures can generally be fixed by rerunning them.

Rerun failed tests  https://circleci.com/docs/rerun-failed-tests/

Here is a screenshot in the middle of the rebuilds
![Screenshot (1625)](https://github.com/OpenCPN/plugins/assets/2363959/7fc6feab-f63a-4e25-8212-2539a67ea0d9)

.

**Comment by rgleason** [comment]
These "late arrivals"  of metadata are not picked up by the downloads script for some reason, so if I am missing any, I have to download all the metadata for that version and copy it over into the metadata file.

**Comment by bdbcat** [comment]
We need to analyze the CCI build logs to learn what is intermittently failing in the workflow.

**Comment by rgleason** [comment]
I will keep an eye on this and take some notes.

**Comment by leamas** [comment]
Furhermore, this obviously should have been filed against testplugin rather than the plugins project

**Comment by rgleason** [comment]
Don't agree with you here.

**Comment by rgleason** [comment]
Add this new feature to reduce time and rerun just the failed build, not all of them!
https://circleci.com/docs/rerun-failed-tests/

**Comment by rgleason** [comment]
Closing. This issue persists at times, but it has become old.
