### ISSUE TITLE
RFE: Weatherfax add ASCAT data

### ISSUE THREAD

**Issue by rgleason** [OpenCPN/plugins#987]
David Burch, Starpath Navigation has added an Issue RFE to weatherfax
https://github.com/rgleason/weatherfax_pi/issues/137
 Adding ASCAT data to WeatherFax pi #137 

His blog about it is here.
http://davidburchnavigation.blogspot.com/2023/08/viewing-ascat-wind-measurements-in.html

We need a good programmer to add this capability.
Thanks.

**Comment by bdbcat** [comment]
Soon on my list, if I am a good enough programmer,,,:)

**Comment by bdbcat** [comment]
Also, this RFE is in wrong place.
Should be in the "WeatherFAX" plugin repo, not the general "plugins" repo

**Comment by rgleason** [comment]
Sorry, closing.

**Comment by rgleason** [comment]
Thanks Dave.
